### ISSUE TITLE
nlbr nunjucks filter doesn't work without the addition of the safe filter

### ISSUE THREAD

**Issue by bgantick** [apostrophecms/apostrophe#1024]

**Comment by boutell** [comment]
This filter needs to be marked safe, and it needs to check whether its input is already a SafeString and tackle that if not before applying its logic and marking the result of that safe as well.

**Comment by abea** [comment]
I think this is all cleared up thanks to Ulf. https://github.com/apostrophecms/apostrophe/commit/2b5a46d197ad069a7e7b42ca44c795765f7c4a8d

It works in my test. @bgantick Would you mind confirming?
