### ISSUE TITLE
Allow any widget module to extend how its wrapper divs are output

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe#1044]
It would be helpful to be able to pass a project level selector to `.apos-area-widget-wrapper` so that you could use CSS adjacent sibling selectors for area/widget layouts.

https://github.com/punkave/apostrophe/blob/cf79201825bd11d23adaa31d8278d520c73ab182/lib/modules/apostrophe-areas/views/widget.html#L5

**Comment by stuartromanek** [comment]
We had an ask for this at one point
https://github.com/punkave/apostrophe/pull/952/commits/5fc84163617434f03839753e25518525101a8cde

**Comment by austinstarin** [comment]
Was there a reason why we opted for not implementing?

**Comment by boutell** [comment]
See also #1162
