### ISSUE TITLE
Need more verbose errors for min and max options for strings

### ISSUE THREAD

**Issue by bgantick** [apostrophecms/apostrophe#1053]
setting `min` and `max` on strings in schemas doesn't give an explicit error (would be nice to display limits)

**Comment by arti5m** [comment]
Looked around and `apostrophe-schemas`:
- `user.js:self.convert`: see the error reporting part
- Propose we add an empty div below help in `macros.html` called `.apos-field-message` that we can use to insert more informative messages like: "Please enter a minimum of {{ field.min }} characters."

**Comment by stuartromanek** [comment]
PR here https://github.com/apostrophecms/apostrophe/pull/1180

**Comment by bgantick** [comment]
Closed via #1180
