### ISSUE TITLE
Fetching options in javascript and template code is awkward and tough to override for various situations

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1055]
Here is a detailed proposal currently under discussion to address this issue. Common use cases include:

* A button widget's "analyticsId" should have a default value...
* Except when it's on a certain page type...
* Or on a subpage of a certain page type...
* In a particular locale...
* Or the analytics id has been set explicitly for the buttons of a particular page.

Some observations:

* Modules are singletons in Apostrophe. So we can't simply compute the configuration that applies to a particular locale, page and widget and make that `self.options` for the module as this would affect all locales, pages and widgets. 

* Manipulating self.options is already frustrating because you must take care to make sure all components of the path to the option of interest actually exist.

* The use cases specific to localization and "landing pages" introduce many more situations in which options are manipulated too often and in complicated ways.

The proposed solution:

* The way to address this is to introduce a `self.getOption` method for all modules:

`self.getOption(req, 'key.subkey')`

Or:

`self.getOption(req, 'key', 'subkey')`

You could of course pass any number of dotted subkeys and/or arguments.

Inside a page template this would also be available more simply as:

`module.getOption('key.subkey')`

This method would first consider the impact of `req.data.page` (including locale-specific settings for the page type), then each of the ancestors of `req.data.page`, then locale-specific settings hardcoded for the module in question, and finally the default `self.options`.

Note that settings dynamically edited in `req.data.page` are already localized because pages and their properties are localized. The same applies to the ancestors of `req.data.page`.

If the path to the option requested does not exist this method will just return undefined, there is no exception thrown so it is much more forgiving than working directly with `self.options`.

It would be possible to access the options of a different module via `apos.moduleAlias.getOption` in both javascript and templates.

* Module-level configuration of options would proceed as it does now. Locale-level configuration would be added by `apostrophe-workflow`, such that in any module you would be able to write:

```
module.exports = {
  label: 'Products',
  localizedOptions: {
    en: {
      label: 'English Products'
    }
  }
};
```

* `self.options.localizedOptions.en.label` overrides `self.options.label` when `self.getOption` is called. Settings are not merged (it is not `_.merge`), they are overridden. If an option is an array and it is overridden at the locale level, it is not appended. You just get the override. Otherwise there is no way to turn things off if they are arrays.

However this leaves us room to consider features like `{ $push: [ ... ] }` or `{ $remove: [ ... ] }` for later implementation if desired.

* Note that locale-based overrides would cascade up the locale tree. So a locale-based setting for `en-us` would win over a locale-based setting for `us`.

* We need to be able to override certain settings when a specific page type is the current page. This is achieved via a new `overrideOptions.fixed` option to the module that manages that page type, as seen below. This allows us to map any option path to any value, beginning with `apos.` to emphasize that we are cutting across modules.

We need this capability in order to, for instance, set the style of all buttons of a certain type while on a certain page type. This is shown below.

* We also need user-editable configuration of certain settings for certain page types. That is, we need to be able to edit those settings via "Page Settings."

This is achieved by adding the schema fields to the page type normally and then configuring `overrideOptions.editable` to create a mapping between option paths and schema field names that exist for this page type, as shown below. 

### Example

```
module.exports = {
  name: 'landing-page',
  extend: 'apostrophe-custom-pages',
  addFields: [
    {
      name: 'analyticsEventId',
      type: 'string',
      label: 'Analytics Event ID',
      def: 'abc'
    }
  ],
  overrideOptions: {
    fixed: {
      'apos.analytics-button-widgets.style': 'blue',
    },
    localized: {
      'en': {
        'apos.analytics-button-widgets.style': 'purple',
      }
    },
    editable: {
      'apos.analytics-button-widgets.eventId': 'analyticsEventId'
    }
  }
};
```

Here we have `fixed` overrides, which override specific `.getOption` calls for specific modules with a fixed value when this page type is the current page, and also `editable` overrides, which override `.getOption` calls with a user-editable value when a specific page is the current page.

`localized` is like `fixed` except that it is locale based, and inherited through the locale tree.

Note that we can make good use of the `def` feature of schema fields here when working with `editable` overrides.

Here is what `widget.html` might look like for the `analytics-button-widgets` module:

```
<button 
  class="{{ module.getOption('style') }}" 
  data-analytics-event-id="{{ module.getOption('eventId') }}">
  Click Me
</button>
```

* Certain core modules, such as `apostrophe-pages`, would begin consulting `self.getOption` to determine things such as the page types array. This would not be done for everything, at least not immediately, but it would definitely be done for page types so that it would be possible to disable certain page types for certain locales via `localizedOptions`.

## Factoring

The core apostrophe module would only receive the `get` methods themselves, with support for accessing options of that module.

The workflow module would add the locale cascade.

A new `apostrophe-pages-option-overrides` module would add the cascade through the page tree with editable and fixed settings.

## Performance concerns

Implementation of the override cascade for ancestors of the current page requires that configuration-related fields always be included when fetching ancestors. Happily by default this is the case, we get all of the schema fields of the ancestors, we just don't execute joins and load areas for the ancestors.

It was suggested that the results be compiled at deployment time. Some of the work can be compiled and cached. However not everything can be cached due to the presence of options that are based on page types (which can be changed dynamically) and even individual settings within "Page Settings." Some small performance impact is to be expected. However no new database calls or asynchronous work appears to be necessary so it should be minimal.

**Comment by boutell** [comment]
Append/remove/manipulate an existing option is a required feature (think appending to an array).
Add support for overrideOptions on pieces show pages (not index).
Add support for overrideOptions on the global doc since the home page is not always present (think 404 or login).

**Comment by stuartromanek** [comment]
@boutell this is complete in `apostrophe-overrides` right?

**Comment by boutell** [comment]
We now have `getOption` for all modules, which supports dot notation out of the box, and apostrophe-overrides extends that to let you get REALLY crazy, yes.
