### ISSUE TITLE
#iOS #iPad: Adding or reordering Areas by drag and drop does not work

### ISSUE THREAD

**Issue by neonsquare** [apostrophecms/apostrophe#1062]
While it is possible to edit existing areas on the iPad it doesn't work to add new areas by touching the "plus"-Symbol. Furthermore it is not possible to drag an area around using the drag/drop-handle. Touching the reordering arrows seems to work.

**Comment by boutell** [comment]
Hi @neonsquare, we currently don't support multitouch/tablet editing in Apostrophe, which hasn't been on the to-do list for any of our clients so far, but we'd accept PRs in that direction as long as they don't unduly alter the experience for desktop/laptop users.

**Comment by boutell** [comment]
Will be a 3.x feature most likely.
