### ISSUE TITLE
Add "limit" option to apostrophe-pieces-widgets

### ISSUE THREAD

**Issue by bgantick** [apostrophecms/apostrophe#1073]
People seem to want to add things like `options: { limit: 1 }` when configuring `apostrophe-files` singletons in schemas. `apostrophe-images` uses the following to bypass straight to file picking:

```
beforeConstruct: function(self, options) {
  if (options.by === undefined) {
    options.by = [ 'id' ];
  }
}
```

This should maybe be an option for anything extending `apostrophe-pieces-widgets`

**Comment by boutell** [comment]
To clarify, these are two separate concerns: limiting how many can be picked, and limiting the ways things can be picked (just "individually" versus "individually, by tag or all"). I've retitled this ticket to be about the first one. I'm not sure what to do with the second one. We can't break sites where people have already picked files "by tag." There's already an approach (above) if you want to lock it down for a specific project.

**Comment by bgantick** [comment]
Yes, sorry - thanks for the clarification Tom.
