### ISSUE TITLE
Piece index, turn on Contextual True by default?

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1076]
Should Add New Piece by turned on by default on the Page menu on an index

**Comment by boutell** [comment]
My vote is "yes, but not unless you can also access 'manage' for that piece type via the page menu."

There is still the problem of truly noncontextual pieces and users possibly being "blind" to the "apostrophe logo" aka admin bar button.

**Comment by stuartromanek** [comment]
once and for all, we're saying `contextual: true` is the recommended way to kick things off, right @boutell ?

**Comment by boutell** [comment]
Setting that yourself, along with making a commitment to actually have pieces-pages, yes.
