### ISSUE TITLE
Give the user an opportunity to 'organize' a page in the tree during page creation

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1084]

**Comment by boutell** [comment]
Maybe something like:

"This page will go here: home -> about -> staff -> contact [change location]"

When you click "change location" reorganize comes up and it's scrolled to make sure the new page is visible, the new page is obviously highlighted, and it's the only draggable one. And when you "OK" that nothing's happened yet, it's just remembering the related page and the relationship.
