### ISSUE TITLE
Consider condensing Page Menu and Global Menu into one interface

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1090]
A/B tests? More research probably needed to say definitively that this is the right move.

**Comment by HollyPony** [comment]
Have you consider the possibility of drag n drop the apostrophe menu. Come in relation with a dynamically resizable menu, which could become heavy since everything gone here

**Comment by stuartromanek** [comment]
@HollyPony Not sure drag-and-drop admin interface fits with the design language of the rest of the interface, but we have talked having the ability to un-float the admin menu and put it in document flow so that it is not on top of the website. Is that the problem you're trying to solve? 

Would welcome a proposal / PR

**Comment by HollyPony** [comment]
I can't see what it look like, but it could be a solution. However, this is not the point of this issue. I'll look to a workaround on my own fork and create a complete issue / pr. In any case, merging menus sound good for me too :)

**Comment by abea** [comment]
@stuartromanek Should this still be open?

**Comment by stuartromanek** [comment]
yes, can close, conclusion on this is that Page Menu and Admin bar will be combined in 3.0 but 2.0 will remain as is
