### ISSUE TITLE
Widgets should be able to opt in to seeing all of the page data at all times

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1093]
Currently, widgets can only see `data.widget` and `data.options`. The latter contains the options passed to the widget via `apos.singleton` or `apos.area`.

They can't see `data.page`. 

This was originally done for several reasons, some theoretical and one practical: when you're editing a widget, or clicking "save" and re-rendering a widget, Apostrophe doesn't have to go get the page exactly the way it normally would just to re-render that one widget faithfully. Loading pages with "all the trimmings" can take time and that slows down editing a bit.

However after long experience we're finding that developers are constantly working around this by passing the page in as an option, which is a much worse performance hit (giant structures in JSON), or by passing in a subset of the fields of the page, which is OK but a lot of extra work for the developer.

Meanwhile, apostrophe-override-options has been introduced. This module allows every module in the system, as well as the current page and its ancestors, to influence what `module.getOption('analyticsId')`  might return when called from `widget.html`. It's a powerful feature and an enterprise customer requires it. And it doesn't work when re-rendering a widget after saving. We worked around it, but it's not great that you still don't see the impact during editing.

My feeling is that we should take the plunge here and make a change:

* The `data` object passed to a widget should be a shallow copy of the data object passed to the page template, with the `.options` and `.widget` properties added.
* When re-rendering a widget, the browser should send the server the current URL in the address bar as a parameter. The server should load everything *exactly as it normally would for that URL*, including invoking `pageBeforeSend`, then skip the final rendering process and just render the one widget.

My feeling is that this is a backwards-compatible change because anything intentionally added to the data object for the widget will still "win."

The performance hit from loading the page fully will either (a) be small, or (b) be a big hint that the developer needs to fix the performance of that page — which is punishing site visitors a lot more than it will punish page editors.

**Comment by boutell** [comment]
cc @stuartromanek @HollyPony @agilbert @bobclewell @austinstarin @bgantick @arti5m @abea @mtthwmnc

**Comment by stuartromanek** [comment]
what would the resulting difference of the `page` object be with the widget fetching it vs passing it through options?

**Comment by boutell** [comment]
Are you asking if there would be any lack of fidelity compared to passing it as an option? There would be no difference. However when it is passed as an option to the widget there is a really massive performance hit in many cases due to the way widget options must be carried around in JSON and passed back to the server for re-rendering unless we make this change.

**Comment by boutell** [comment]
The team is in support of this feature.

**Comment by boutell** [comment]
We may be overthinking this. It might be as simple as an option indicating a widget type should refresh the main content area on save.
