### ISSUE TITLE
Convert Apostrophe in-context admin UI from anchors to buttons

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1111]
Nested anchors are not allowed, some real-world cases of folks doing that 

https://github.com/punkave/apostrophe/issues/797

**Comment by fredrikekelund** [comment]
Thanks for alerting me to this existing issue, @stuartromanek! I'll see if I can write up a PR within a week or so

**Comment by abea** [comment]
This might be resolved?

**Comment by stuartromanek** [comment]
The main macros have been replaced and tested but there could be others in the wild. Closing
