### ISSUE TITLE
New batch operations modal needs styling

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1113]
See modal.html, progress.html and user.less in the new apostrophe-jobs module.

Use the dgad-266 branch until that gets merged.

Temporary styles screenshot:

https://www.dropbox.com/s/19sseuogx8y8vg8/vvhec35t.png?raw=1

**Comment by stuartromanek** [comment]
I need to be able to test this UI over and over, what are the steps for running an innocuous job in a boilerplate project?

**Comment by boutell** [comment]
Do a batch operation on pieces. You could add a setTimeout to the method
that carries it out on each doc so it doesn't flash by
