### ISSUE TITLE
Modal tabbed sections get shifted out of view on medium widths

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1146]
In a modal with tabbed sections, if I go to a medium-small width the side tabs can get pushed out of the region and then don't go back to normal when the page is made large again. Editing at small screens might not be supported, but it should go back to normal when expanded again.

Screen capture: https://youtu.be/au4NS3Oqu9o

**Comment by abea** [comment]
Seems this has to do with editing views that require scrolling. When you scroll down on the right side of the modal (the form), then switch tabs, the tab list jumps up. It seems proportional to the distance scrolled.

Longer scroll, bigger jump: https://youtu.be/7t7UU9uVZr0
Shorter scroll, short jump: https://youtu.be/B6r26cWgKQg

**Comment by bgantick** [comment]
This seems to have been resolved.

**Comment by bgantick** [comment]
Ah, this is happening in Firefox
