### ISSUE TITLE
Add colspan and rowspan to allowed attributes in apostrophe-rich-text-widgets

### ISSUE THREAD

**Issue by msdsk** [apostrophecms/apostrophe#1149]
Adding by default

` sanitizeHtml:{
  allowedAttributes: {
    td: ['colspan', 'rowspan'],
    th: ['colspan', 'rowspan']
  }
}`

would allow for tables to retain information about joined cells, without any ill results.

**Comment by boutell** [comment]
Well, ill results are in the eye of the beholder... this could encourage the use of tables as a layout mechanism. I don't know if it's a good default or not, and you can do this through configuration. @stuartromanek what do you think?

**Comment by stuartromanek** [comment]
I don't know that it will encourage people to use tables for layout .. it wouldn't be super easy to build like that.

After a quick look at CKEditor's Table plugin (which comes bundled with Apostrophe), the plugin DOES let you `merge` cells, which adds `colspan` and `rowspan` attributes.

 I think it would be fine to add them by default.

**Comment by boutell** [comment]
Sure, a PR is welcome, this would need to be done with care, note that if you just configure allowedAttributes with new stuff but don't include the usual stuff, you lose all of it.

**Comment by stuartromanek** [comment]
closing this as its really not an issue.

Look forward to a PR @msdsk
