### ISSUE TITLE
Support for svg attachments

### ISSUE THREAD

**Issue by bigomega** [apostrophecms/apostrophe#1150]
Adding `'svg'` to this list enables it, but I'm not sure if that's all is required  
https://github.com/punkave/apostrophe/blob/91b5c15393f89185d58459059ae32f2c22c1d622/lib/modules/apostrophe-attachments/index.js#L126

**Comment by boutell** [comment]
svg really should become part of the `images` group, and should be supported by apostrophe-images-widgets. However this requires that we address cropping for SVGs. Which is probably possible by generating versions that have a prologue that masks them. We would also have to adjust the `url` method of `apostrophe-attachments` to report the original file's URL for any named size.

**Comment by boutell** [comment]
(We would address cropping through masked versions, rather than dynamically, in order to allow all of Apostrophe's cropping UI and frontend logic to work without big changes.)
