### ISSUE TITLE
Multi Languages Using WorkFlow 

### ISSUE THREAD

**Issue by fahmawy** [apostrophecms/apostrophe#1170]
Hello Dears
Really I am soo happy for using apostrophe and i reach now to finalize my project with it so please i have one issue hope you helping me on it cause i am new user on node application

i used work-flow for locales to switch between Arabic and English
when i switched to Arabic or English content translated but look to the lang in html
https://prnt.sc/hpf1ce 
still en

so please do you recommend method i can use to change it to be able load bootstrap-rtl file base on lang slug 
and how i can detect the current language on layout.html ??

thanks in advance

**Comment by boutell** [comment]
Hi @fahmawy,

There is a `locale` block in the outer layout template as of a recent release, and you can access `data.workflow.locale` in templates, so there you go.

We'll add this to the docs.
