### ISSUE TITLE
Allow CKEditor style options for text justifying

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1172]
It seems that in 2.0 the `'JustifyLeft', 'JustifyCenter', 'JustifyRight'` options are not available in the CKEditor toolbar. We can add them as styles, but not in the toolbar. This was available in Apostrophe 0.5.

**Comment by boutell** [comment]
Apostrophe doesn't mess with the toolbar options, it just passes them to CKEditor. So most likely these options are provided by a ckeditor plugin that is not part of our current ckeditor build. You could fix that for a project by adding those ckeditor plugins at project level and there is a documented procedure for that. However perhaps these should be part of our standard build. 

A new build requires some help from @stuartromanek who sees to it that the custom Apostrophe theme is up to date.

**Comment by stuartromanek** [comment]
I thought this should be available by default so i added it to our build. PR is open https://github.com/apostrophecms/apostrophe/pull/1177

**Comment by stuartromanek** [comment]
This was merged to master, see PR for use ^
