### ISSUE TITLE
More (overridable) options for CKEditor

### ISSUE THREAD

**Issue by bigomega** [apostrophecms/apostrophe#1197]
Only three options are allowed for CKEditor now (**[source code](https://github.com/apostrophecms/apostrophe/blob/master/lib/modules/apostrophe-rich-text-widgets/public/js/editor.js#L63-L65)**). It would be nice to allow users to send any option since CKEditor takes a ton of parameters.  (It can be as simple as doing an object merge).

**Comment by stuartromanek** [comment]
Hi @bigomega 
You can indeed override CKEditor's default configuration by hooking into `apostrophe-areas` and `apostrophe-rich-text-widgets` at project level.

This would be more valuable to others as a question about _how_ to override or add specific functionality to CKEditor in Apostrophe on SO tagged with `apostrophe-cms`. https://stackoverflow.com/questions/tagged/apostrophe-cms

Do you mind posting what you're trying to accomplish over there?
