### ISSUE TITLE
data.baseUrl returns the wrong protocol for secure sites.

### ISSUE THREAD

**Issue by arti5m** [apostrophecms/apostrophe#1205]
https://github.com/apostrophecms/apostrophe/blob/1812b9b5b1fe69077a3b9c75e9d0d3e289dc1c05/lib/modules/apostrophe-express/index.js#L604

**Comment by boutell** [comment]
You can address this by setting `baseUrl` correctly in `data/local.js`, and you always would for a production site (right?), but we should look at whether we can configure Express to trust the proxy and thus know it is secure.

**Comment by arti5m** [comment]
This sort of thing? 
https://github.com/techgaun/til/blob/master/nodejs/nodejs-req-protocol-with-nginx-proxy.md

**Comment by timashev** [comment]
Kind of duplicate of this: https://github.com/apostrophecms/apostrophe-workflow/issues/126

**Comment by boutell** [comment]
Going to close this because there is a working solution based on configuring baseUrl and there has been no movement.
