### ISSUE TITLE
moog-require: improve bundles shouldn't have to be inside /node_modules

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1207]
In quick prototyping of an improve bundle it is not immediately clear that the module NEEDS to be inside `/node_modules`. This shouldn't be required.

This bug has to do with moog-require

**Comment by boutell** [comment]
Note to self: putting the ticket here was your idea because moog-require doesn't get looked at very often and this should probably find its way to a project roadmap.

**Comment by boutell** [comment]
Closing this because the new support for nested folders in `lib/modules` pretty much meets the reasonable project-level needs for this feature for now.
