### ISSUE TITLE
Chooser: Make controls always visible and underneath the chosen thing

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1213]

**Comment by stuartromanek** [comment]
a few proposals for chooser'y related UI

Overall: Don't hide chooser choice UI. If dealing with a text-like thing, build the UI more inline than the in-context style

1: In the typeahead/browse view of a schema, combine these elements into one that makes a bit more sense.
http://g.recordit.co/emLaR2crjd.gif

2. Reflected in the chooser manager
http://g.recordit.co/CH3InfQDuQ.gif

3. In an image chooser, leave the controls exposed and hanging on their elements
![image](https://user-images.githubusercontent.com/1889830/40054525-237289cc-5813-11e8-86f6-255a3f31d900.png)

@runyx ^

**Comment by boutell** [comment]
Also a good idea for the up and down and delete buttons to update the display without re-rendering via the server. "Always render server side" has been quite good to us, but these are easy cases for an optimization that would eliminate frustration when you have scrolled all the way to the bottom of a long selection to move something and now you have to scroll again.

**Comment by runyx** [comment]
Those look fantastic. Love the new combined approach in 1&2.

**Comment by stuartromanek** [comment]
@boutell it would be nice to animate those movements as well, the flashing is kinda harsh as to what just happened. Do we have some easy jquery-ui library available to throw that at?

**Comment by boutell** [comment]
Good question, I'm not sure which effects are in our build but we can probably do something nicer.

**Comment by stuartromanek** [comment]
This is all merged
