### ISSUE TITLE
Page Tree: Visually differentiate the Trash node

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1214]

**Comment by boutell** [comment]
@stuartromanek did you still want to add an icon or something for this?

**Comment by stuartromanek** [comment]
A proposal like this is coming in a batch of modal ui enhancements

http://g.recordit.co/gq8R17UHDL.gif

@runyx ^

**Comment by runyx** [comment]
I like it. I'm going back and forth on if the red is distracting when you're not thinking about the trash, but I think the benefit outweighs that.

**Comment by runyx** [comment]
Hm I'd rather lean red than make it seem inactive, don't want people thinking they can't drag anything into or out of it. The red has a nice continuity with the "Move to Trash" text. Maybe lighten it instead?
