### ISSUE TITLE
widgetControlGroups need to be extended to support select elements

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1222]
This is a requirement for the apostrophe-personas design.

**Comment by tortilaman** [comment]
I definitely second this. It would really help with making custom modules which have multiple similar types, such as different types of notices.

**Comment by stuartromanek** [comment]
@boutell this shipped in the most recent version, yeah?

**Comment by boutell** [comment]
It did, but in a minimal way - the select element will appear, and the current value is preselected, but actual saving of a changed value requires a bit of plumbing on your part. See the apostrophe-personas module (currently only in github) for an example.
