### ISSUE TITLE
Cannot upload images to media library on Windows, but can on linux platform

### ISSUE THREAD

**Issue by valorad** [apostrophecms/apostrophe#1225]
Platform: win32-x64
node: v9.4.0
apostrophe: v2.45.0

I have set up an apostrophe project on Windows. When I open up Images management window and try to upload any image, it gives out an error: 

> Some files were damaged, of an unsuitable type or too large to be uploaded.

So I cannot upload any image.

I checked it out in server console, it outputs:

> { Error: Command failed: convert C:\Users\valorad\AppData\Local\Temp\Ci9ztwvCQ6EaMdgwn0q_Z7H6.png -auto-orient ( -clone 0--1 -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/original.png +delete ) -strip -resize 1600x1600> ( -clone 0--1 -resize 1600x1600> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/max.png +delete ) ( -clone 0--1 -resize 1140x1140> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/full.png +delete ) ( -clone 0--1 -resize 760x760> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/two-thirds.png +delete ) ( -clone 0--1 -resize 570x700> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/one-half.png +delete ) ( -clone 0--1 -resize 380x700> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/one-third.png +delete ) ( -clone 0--1 -resize 190x350> -write M:\workbench\@norryowl\proj/data/temp/uploadfs/3a6aea8d62be4c29fbcacd0e4abb33e2/one-sixth.png +delete ) null:
> ��Ч���� - -auto-orient
> ...

But the exact project works well if served on linux platform.

I notice that the file path it trying to process is incorrect, with back-slashes at first, but after workspace path it all turned to forward-slashes. Could it have something to do with this?

**Comment by boutell** [comment]
Did you install the imagemagick convert utility? Is its location present in
the PATH environment variable?

**Comment by boutell** [comment]
Closed due to lack of response, but please reopen if you find that the problem persists when the imagemagick convert utility is present in the PATH as seen by your node application.

**Comment by dmykhailo** [comment]
Hi there,
most likely there are restrictions on your NGINX server.
Update your nginx.conf with e.g.:
```
post_max_size 128M;
upload_max_filesize 100M;
```

**Comment by valorad** [comment]
@dmykhailo No, I don't think so. I wasn't using nginx back then.

I think the problem probably lay at the path, as you can see `M:\workbench@norryowl\proj/data/temp/uploadfs/3a6ae...` where the slash and back-slashes are mixed, which might have caused the problem. (Or if not for the slashes, it might be the "@" character)
