### ISSUE TITLE
Error: The module services extends apostrophe-pieces-widgets, but the piecesModuleName option is not set, and we can't guess it from the name of your module.

### ISSUE THREAD

**Issue by divyanshprateek** [apostrophecms/apostrophe#1226]
I am not able to use apostrophe-pieces.

**Comment by boutell** [comment]
Please show your code. Did you try what the error message is telling you?

**Comment by divyanshprateek** [comment]
thanks it worked

**Comment by Developer314** [comment]
@divyanshprateek  how did you fix the issue ?

**Comment by boutell** [comment]
@Developer314 if you are extending `apostrophe-pieces-widgets` then there must be a separate module extending `apostrophe-pieces`, named (for instance) `my-things`, and your module would be named `my-things-widgets` and have its `piecesModuleName` option set to `my-things`. If any of this is not the case then the error message is to be expected.
