### ISSUE TITLE
Add weight property to pieces for ordering

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1229]
A feature that comes up occasionally from clients is manual ordering that would be respected across the site. So if I have staff I can, through some UI, drag them into an order that's respected across the site in widgets, indexes, etc.

The `weight` property in Drupal and `order` (I think) in Wordpress works like this. It might take a bit of config to get it set up in those CMS, but it's a pretty valuable option. Importantly this would have the UI for drag sorting rather than needing to set a number in each piece's UI.

**Comment by bobclewell** [comment]
I think a very similar feature was discussed recently during a meeting with an enterprise client. In that case they have a large number (+100) of pieces, and they were not interested in ordering the complete amount. The way I understand it, their idea was to be able to flag certain pieces as "featured" and have those featured pieces rise to the top. And then, within those featured pieces you can drag and drop an order.

I'm not sure where this feature fits into their list of priorities, but it would be useful to sync up with @stuartromanek on this at some point so we can also meet the need you identified.

**Comment by abea** [comment]
Excellent. The "featured" flag is a great addition, but I'd suggest the weighting not be dependent on that. I'd guess you wouldn't be planning to tie those, but thought I'd mention since most Apos use cases probably wouldn't need both.

**Comment by boutell** [comment]
You can do the weight thing by addinga field and setting the sort option.

**Comment by tortilaman** [comment]
I've implemented a weight field in some projects recently, and there are a couple issues with that:
1) Make sure you don't `sortify` an integer field, that's a really annoying thing to figure out.
2) When you change the weight of one item, it doesn't affect the weights of other items. I guess this is why it's a weight and not an order.

I've been looking to figure out some way of actually ordering things as well, but hadn't gotten around to fully implementing anything yet. I think this would be really valuable.

**Comment by abea** [comment]
I thought of that, but with enough pieces, counting on a client to manually go into each piece and set a number often isn't sustainable. Certainly an option if desperately needed.

**Comment by boutell** [comment]
This will likely be addressed via a DGAD scope of work.

**Comment by boutell** [comment]
Closing as we now have the `apostrophe-pieces-orderings-bundle`.
