### ISSUE TITLE
Broken Install 

### ISSUE THREAD

**Issue by romans127** [apostrophecms/apostrophe#123]
Something is wrong with the new updates. The package.json file fails every time I just try to install the sandbox site.

**Comment by JemiloII** [comment]
Fails for me on Centos 7 with node v5.9.1 and npm v3.7.3
I also used aposthrophe-cli to generate project folder.

[root@foodmemes foodmemes]# npm install
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated extend@1.1.3: Please update to the latest version.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
loadDep:async             ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Killed

**Comment by boutell** [comment]
This is an out of memory error from npm and is not related to Apostrophe
per se. Obviously it concerns us though.

We generally advise our clients to get a 2GB VPS, which has always been
sufficient. In 1GB, npm tends to fall over, especially with mongodb on the
same machine.

It may be due to the inclusion of babel in the apostrophe-browserify
module's dependencies. It's a fairly large dependency. Still npm should
cope and I wish they would revisit it from top to bottom.

Ryan's message is pretty ambiguous, it's not clear if he's having the same
issue as you are, so I will keep this issue open in the hope he comes back
with specifics.



On Sun, Mar 27, 2016 at 1:10 AM, Brian M. Jemilo II <
notifications@github.com> wrote:

> Fails for me on Centos 7 with node v5.9.1 and npm v3.7.3
> I also used aposthrophe-cli to generate project folder.
>
> [root@foodmemes foodmemes]# npm install
> npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For
> more information, visit https://fb.me/react-tools-deprecated
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before
> will fail on newer node releases. Please update to graceful-fs@^4.0.0 as
> soon as possible.
> npm WARN deprecated extend@1.1.3: Please update to the latest version.
> npm WARN deprecated CSSselect@0.4.1: the module is now available as
> 'css-select'
> npm WARN deprecated CSSwhat@0.4.7: the module is now available as
> 'css-what'
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before
> will fail on newer node releases. Please update to graceful-fs@^4.0.0 as
> soon as possible.
> loadDep:async ▄ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> Killed
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/123#issuecomment-201992479>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Certainly a different error from hat I received in the past if my memory serves me correctly. This looks like a memory issue.  Mainly because of where the killed log is happening.  I'd suggest looking at your memory as its loading dependancies and make a note of the most significant spike

**Comment by boutell** [comment]
We find that a 2GB VPS has no trouble, but anything smaller tends to run
into this. ): npm needs a crash diet.

On Mon, Mar 28, 2016 at 10:57 AM, Ryan Watts <notifications@github.com>
wrote:

> Certainly a different error from hat I received in the past if my memory
> serves me correctly. This looks like a memory issue. Mainly because of
> where the killed log is happening. I'd suggest looking at your memory as
> its loading dependancies and make a note of the most significant spike
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/123#issuecomment-202427437>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
