### ISSUE TITLE
Deploying apostrophe to the cloud documentation missing key information

### ISSUE THREAD

**Issue by tortilaman** [apostrophecms/apostrophe#1230]
I'm not sure where to submit a pull request for this, otherwise I'd do it myself.

Currently, nowhere in the documentation (other than the source code from what I can tell) does it inform you that the `minified` option for `apostrophe-assets` overrides the `APOS_MINIFIED` environment variable. I can only assume this is something that has tripped people up many times. It would probably be ideal to mention that you should remove the minified option from your apostrophe-assets options.

**Comment by boutell** [comment]
You're right, I think we made a bad call there. I've documented it with a very clear warning. You can contribute PRs to the apostrophe-documentation repo. The README covers how to do test builds.

**Comment by boutell** [comment]
Sorry for the frustration I can tell you experienced on this one!

**Comment by tortilaman** [comment]
Thanks, I probably could've figured out the repo with a bit o searching, hahaha.
