### ISSUE TITLE
Version mismatch Github / NPM

### ISSUE THREAD

**Issue by kamildragon** [apostrophecms/apostrophe#1234]
Hello, 
this is a question that arised when i went looking for a specific version, 
why is there a version missmatch between github and npm:
NPM: version 2.46.1 
Github: 2.39.1

I went looking for issues/bugfixes and noticed, the version mismatch is irritating especially if working in a team where we come to different conclusions about the latest version.

Thanks!

**Comment by austinstarin** [comment]
Thanks for writing in! I'm seeing the same version number in GitHub's `master` branch as published on NPM https://github.com/apostrophecms/apostrophe/blob/master/package.json#L3

Are you referencing that branch?

**Comment by boutell** [comment]
Hi, npm is definitive. We have been lazy about git tagging. We need to automate the release process more so that doesn't happen. Always refer to package.json and npm.
