### ISSUE TITLE
Enhancement to showFields on arrangeFields tab grouping

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe#1236]
If show fields on a group of arranged fields in your schema, the fields show/hide but the tab that you group them in remains.

**Comment by boutell** [comment]
Interesting point, but can you have a ux convo first with @stuartromanek
about whether we should be showing and hiding tabs with showFields? The
user night miss that even if it worked.

**Comment by bobclewell** [comment]
I just came across this need in my current project. 

To me it would be more confusing to have an empty tab, then to hide and show tabs. I going to work with the empty tabs for now.

**Comment by bobclewell** [comment]
Simply stated, if the tab has no fields within it showing, it should also be hidden, IMO.

**Comment by boutell** [comment]
Works for me.

**Comment by boutell** [comment]
(That is, the idea works for me.)

**Comment by stuartromanek** [comment]
There is a semi-duplicate where I suggested visually disabling those tabs, which feels more in line with something like a system menu. That seems like the better option to me but would hear from @boutell and @bobclewell before closing this one

**Comment by stuartromanek** [comment]
that issue is here https://github.com/apostrophecms/apostrophe/issues/1398
