### ISSUE TITLE
Updating an area in a piece should fire beforeSave, etc.

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1247]
Right now, the areas module doesn't attempt to use the update handler of the piece, it goes straight to docs.update. If a manager can be found and it has an update method it should be used. cc @tortilaman

**Comment by boutell** [comment]
Also a good first issue for those curious about the node-y bits of the code. Hint: the file you'll be working in is `lib/modules/apostrophe-areas/lib/api.js`. The `saveArea` method calls `self.apos.docs.update`, but that is low level and it bypasses the special handling the developer might want for a particular type of piece. 

Instead find the manager for the type:

`var manager = self.apos.docs.getManager(doc.type)`

If the manager exists and has an `update` method, call that instead. If both conditions are not met, go ahead and call `docs.update`.

**Comment by kalidis** [comment]
I was trying to do this pull request but I have no idea that which manager could have a update method, could you give my an example?

**Comment by boutell** [comment]
You can use an if statement to see whether manager.update exists or not.
