### ISSUE TITLE
Add schema field type `email`

### ISSUE THREAD

**Issue by arti5m** [apostrophecms/apostrophe#1254]
An `email` field type would be very handy.

**Comment by anddimario** [comment]
I've created this: https://github.com/anddimario/acms-email-field

**Comment by boutell** [comment]
@anddimario would you be interested in turning this into a PR on the apostrophe core module?

**Comment by anddimario** [comment]
i've not much experience on apostrophe, but i'll try @boutell

**Comment by boutell** [comment]
This was done.
