### ISSUE TITLE
strange layout behaviour

### ISSUE THREAD

**Issue by daslicht** [apostrophecms/apostrophe#1277]
Hi, 
i have added the following block befor the ```beforeMain``` block to the /views/layout.html

```
{% block navigation %}
NAV COMES HERE
{% endblock %}
```

even without a wrapping block the text is not shown. (yes I restarted node)

Even tho my default.html tempalte extends layout , the block navigation is not show.
Is there something else to be configured ? please?

**Comment by boutell** [comment]
Your layout in turn extends `outerLayout.html`, which has no `navigation` block. In Nunjucks, only the "root" template (the one all others extend, directly or indirectly...) can create a brand new block that isn't nested in another one.

But, you can make a `navigation` block inside a block that *does* exist, like `beforeMain`. Nesting blocks is fine and will let you do what you want, overriding the `navigation` block separately in `default.html`.

In layout:

```
{% block beforeMain %}
  {% block navigation %}NAV HERE{% endblock %}
  ... other stuff ...
{% endblock %}
```

Now in default.html:

```
{% block navigation %}
Nav customized to default...
{% endblock %}
```

**Comment by boutell** [comment]
(In future, please send how-to questions like this to stackoverflow first, tagged apostrophe-cms. It makes the answers easier for others to find. github is best used for bug reports, feature requests, PRs, etc.)

**Comment by daslicht** [comment]
allright
