### ISSUE TITLE
"Add Content" menu fights with the widget controls (e.g. it fights with the up/down/trash/etc. buttons)

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1288]
These wind up overlapping because the widget controls still pop up when a menu is active, and you are unable to click the menu, which is becoming a showstopper in the enterprise sandbox.

**Comment by boutell** [comment]
The fix in #1289 is inelegant, assigning to @stuartromanek to think about a cleaner/more CSS oriented fix. This needs to ship for now due to urgent enterprise requirement.

**Comment by stuartromanek** [comment]
Completed some UX follow through on the fix begun in #1289 and closed this out
