### ISSUE TITLE
PayloadTooLargeError: request entity too large when trying to POST to apostrophe-headless API

### ISSUE THREAD

**Issue by marjan-georgiev** [apostrophecms/apostrophe#1291]
I am using apostrophe-headless, and my payloads are slightly big since I am storing images as base64 strings, so some of the requests fail with this:

```
PayloadTooLargeError: request entity too large
    at readStream (/Users/marjan/Projects/marketplace-backend/node_modules/raw-body/index.js:155:17)
    at getRawBody (/Users/marjan/Projects/marketplace-backend/node_modules/raw-body/index.js:108:12)
    at read (/Users/marjan/Projects/marketplace-backend/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/Users/marjan/Projects/marketplace-backend/node_modules/body-parser/lib/types/json.js:134:5)
    at Layer.handle [as handle_request] (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:317:13)
    at /Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/marjan/Projects/marketplace-backend/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:317:13)
    at /Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/marjan/Projects/marketplace-backend/node_modules/express/lib/router/index.js:275:10)
    at self.csrf (/Users/marjan/Projects/marketplace-backend/node_modules/apostrophe/lib/modules/apostrophe-express/index.js:447:16)
```

I tried setting `apostrophe-express.bodyParser` to `{limit: '50mb', extended: true}`, but that doesn't seem to work.

Any ideas on how to increase the request size limit?

**Comment by marjan-georgiev** [comment]
This seems to have worked:

```
bodyParser = {
  json: {limit: '50mb', extended: true},
  urlencoded: {limit: '50mb', extended: true}
};
```

**Comment by boutell** [comment]
Interesting. Most of the time JSON encoding is used with apostrophe-headless, and we did bump up the limit for JSON to 16MB recently in the latest npm version of apostrophe. Glad you were able to find the correct configuration for your needs.

**Comment by moshepeled** [comment]
better use:

app.use(bodyParser.json({limit: '10mb', extended: true}))
app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))

**Comment by sanakdam** [comment]
i tried change limit on node_module body-parser from 100kb to 10000kb and it works

**Comment by pepo205** [comment]
You can avoid parse payload, in case you don't need it (file transfering for example), using param parseReqBody: false

**Comment by pronebird** [comment]
@pepo205 `parseReqBody` is not documented anywhere.

**Comment by boutell** [comment]
Yeah, I don't think `parseReqBody` is a thing.

Setting the limit on body-parser is the way to go.

**Comment by Gricardov** [comment]
> i tried change limit on node_module body-parser from 100kb to 10000kb and it works

This was the answer I was looking for! Thanks. I had a base64 encoded json string and couldn't change the limit in any other way

**Comment by courageDeveloper** [comment]
@marjan-georgiev  thanks a lot. I used app.use(bodyParser.urlencoded({limit: '50mb', extended: true }));
app.use(bodyParser.json({limit: '50mb', extended: true}));  Which is basically the same thing.

**Comment by ravi-kumar-beniwal** [comment]
Better use you can specify the limit of your file size as it shown in given line

app.use(bodyParser.json({limit: '10mb', extended: true}))
app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))

You can also change the default setting in node-modules body-parser then in the lib folder, there are JSON and text file. Then change limit here. Actually, this condition pass if you don't pass the limit parameter in the given line
app.use(bodyParser.json({limit: '10mb', extended: true})).

**Comment by maksof-Rehan** [comment]
> better use (you can change the limit of data as you wish - for example 10mb):
> 
> app.use(bodyParser.json({limit: '10mb', extended: true}))
> app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))

workng for me thanks

**Comment by sudhir600** [comment]
Worked for me.. Thanks

**Comment by Abhinash16** [comment]
When you are trying to send data from postman, remove the header and than try to upload,
and remember to use the same key while uploading the image that you have used during defining multer single method,
eg: single.('Image', 10);
from postman send "Image": <your file>
and uncheck the header content : see pic for ref
![Screenshot (4)](https://user-images.githubusercontent.com/52877872/70368702-1e609180-18d4-11ea-8d40-65bbbf2f07a9.png)

**Comment by Redsandro** [comment]
But what are the default limits?

**Comment by Rieger-Sebastian** [comment]
Thank you for the solution works for me!
    _app.use(bodyParser.json({limit: '10mb', extended: true}))
    app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))_

If it still not working check the location where you set it. For me it works after I set it to one of the first "app.use" elements.

**Comment by SailorDev** [comment]
> Thank you for the solution works for me!
> _app.use(bodyParser.json({limit: '10mb', extended: true})) app.use(bodyParser.urlencoded({limit: '10mb', extended: true}))_
> 
> If it still not working check the location where you set it. For me it works after I set it to one of the first "app.use" elements.

it still not working for me

**Comment by usama-asfar** [comment]
This work for me 
```
app.use(bodyParser.json({
  limit: '50mb'
}));

app.use(bodyParser.urlencoded({
  limit: '50mb',
  parameterLimit: 100000,
  extended: true 
}));
```

**Comment by ganeshBUnbound** [comment]
> This work for me
> 
> ```
> app.use(bodyParser.json({
>   limit: '50mb'
> }));
> 
> app.use(bodyParser.urlencoded({
>   limit: '50mb',
>   parameterLimit: 100000,
>   extended: true 
> }));
> ```

Thanks man. It worked for me

**Comment by boutell** [comment]
Hi folks, since @marjan-georgiev gave the right answer for Apostrophe long ago (see above), I am locking this thread. For general questions about the body-parser module unrelated to apostrophe please see the [body-parser module documentation](https://www.npmjs.com/package/body-parser) which does cover all this.
