### ISSUE TITLE
CSS Shapes Editor for Images in Apostrophe

### ISSUE THREAD

**Issue by tortilaman** [apostrophecms/apostrophe#1354]
CSS shapes (awesome [video explanation](https://www.youtube.com/watch?v=pOB75oTNhw0) from a super insightful channel if you're unfamiliar) seem like a really awesome (yet underutilized) part of css that would work really well with a cms. As such, I was going to spend some time implementing it for my team's use, and figured it would make sense to contribute back to Apostrophe as a whole. With that in mind, I wanted to get the team's thoughts on implementation. Going from what I think is easiest to hardest:

### Option 1) Image mask field per-image
_**Add a field on this page**_
<img width="1408" alt="screen shot 2018-05-04 at 1 25 33 pm" src="https://user-images.githubusercontent.com/5018268/39650887-b199b4b4-4f9e-11e8-83e2-c488a15ea92f.png">
The easiest thing to do would be to add a field to the `apostrophe-images` module to add a mask image, but that would be on a per-image basis and not on a per-placement basis. I can't really think of a common scenario where you would need different masks for different placements of the same image, so that would probably be fine. That being said, similar things like cropping and focal point selection are done on a per-placement basis. Maybe a compromise would be to allow per-placement masks similar to cropping and focal points?

### Option 2) Image mask field per-placement
_**Add a option here**_
<img width="215" alt="screen shot 2018-05-04 at 12 54 12 pm" src="https://user-images.githubusercontent.com/5018268/39650936-dc191cc0-4f9e-11e8-81f2-9baeef6d9563.png">
So in this option It would still be fields, but having just a couple schema fields show up in a modal after clicking a button might feel somewhat empty? That being said it does give users more flexibility.

### Option 3) Shape Editor Modal
_**Add a option here**_
<img width="215" alt="screen shot 2018-05-04 at 12 54 12 pm" src="https://user-images.githubusercontent.com/5018268/39650936-dc191cc0-4f9e-11e8-81f2-9baeef6d9563.png">
An alternative to mask images would be implementing a polygon / ellipse editor modal in the same spot as option 2. Maybe in the end the modal that comes up would have the ability to do either masks or a shape editor?

Adobe released a [javascript library](https://github.com/adobe-webplatform/css-shapes-editor) for this a few years back that looks like it could do the trick, but it would probably need a bit of updating. This seems like it could be adding a lot of overhead to what are already some long load times for the apostrophe editing interface though.

_**Pretty easy to use**_
<img width="211" alt="screen shot 2018-05-04 at 12 56 20 pm" src="https://user-images.githubusercontent.com/5018268/39649481-c9fbbfec-4f9a-11e8-8647-9532c56f998d.png">

### Usage
The one thing that is a bit different about this as opposed to cropping or focal points is that the built-in image widget wouldn't really have a use for it by itself unless some major additions were made to allow for captions to appear on top or something. This would make it a feature that is only useful if users use it in a similar fashion to how you can currently manually retrieve focal point info. In addition since it's a css property _**it would only be usable in inline styling or with javascript**_ since (at least to my knowledge) apostrophe data isn't usable in stylesheets. If that's not the case though, do let me know as I'd love to be able to use apostrophe data when compiling less.

### My initial choice
The developer in me wants to go for option 3 since it's a more compelling interaction, but I feel like trusting that users are able to create mask images allows use of a more powerful (but less interesting) implementation. Potentially in the future a combination of 2 and 3 would be best, but I think at least initially I would go with option 1.

Let me know what you think makes the most sense

**Comment by boutell** [comment]
Sorry we didn't get back to you on this cool idea in a reasonable amount of time! It's out of scope for apostrophe core but would make an interesting enhancement possibly using the `improve` feature. If you decide to return to it let us know, closing for now.
