### ISSUE TITLE
Batch upload UI should include progress meter

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1367]
Large batch uploads just Spin the Wheel for a long time, giving little indication for the user that good things are happening. We should include a progress meter with a `Uploading file x of xx` message

**Comment by boutell** [comment]
Sure. I have seen images pop up on the grid in this situation but maybe not
always and a real counter would be classy.

**Comment by stuartromanek** [comment]
We have a design for more complete progress meters in 3.0
![image](https://user-images.githubusercontent.com/1889830/72631734-c4b3a400-3922-11ea-8905-92ed0f59421b.png)
