### ISSUE TITLE
Vulnerabilities found with npm@6

### ISSUE THREAD

**Issue by crstnio** [apostrophecms/apostrophe#1372]
Just updated to npm@6 and created a boilerplate project. I think this is new to npm, since `npm audit` was [added to version 6](https://docs.npmjs.com/getting-started/running-a-security-audit).

```
[!] 22 vulnerabilities found [9836 packages audited]
    Severity: 8 Low | 14 Moderate
    Run `npm audit` for more detail
```

I made a screenshot of the audit. It's very long, this is only an excerpt.

<img width="576" alt="npm audit" src="https://user-images.githubusercontent.com/34842497/40015219-e2ea5cfa-57b2-11e8-8446-e3db5fd82e6a.png">

**Comment by boutell** [comment]
![Passing Audit](https://user-images.githubusercontent.com/32125/40484977-3b5deddc-5f2b-11e8-882e-6113b3c6f724.png)

**Comment by boutell** [comment]
We are now passing the audit. Microsoft took care of their dependency in response to our ticket. 👍
