### ISSUE TITLE
MomentJS to depecate support for non-ISO or RFC format

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1376]
In an older 2.x project we're passing a date from the Twitter API through the date filter, bypassing the normal processing in apostrophe-twitter-widgets' getRelativeTime method. This caused Moment.js to kick out this warning:

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

We attempted #1362 , but simply parsing as ISO results in losing the time zone information.

**Comment by boutell** [comment]
This isn't Apostrophe's task to perform, or if it is, it belongs in apostrophe-twitter-widgets.
