### ISSUE TITLE
When deleting media, widgets that use that media do not know they are now empty

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1381]
This creates broken UI when there both no placeholder and no image. Perhaps some kind of 'this was recently deleted' message when revisiting the affected field?

**Comment by geoffdimasi** [comment]
![image](https://user-images.githubusercontent.com/164509/40143940-df3b6788-592a-11e8-8b09-3b5f7fe1dbd4.png)

**Comment by stuartromanek** [comment]
similar to #847

**Comment by stuartromanek** [comment]
Hm .. like if you had a slideshow of many images and then you delete one out of the media library, the rest would soldier on and that would be good, right?

A simple enhancement would be to give our house `apostrophe-images-widgets` template a better placeholder / not found state

**Comment by boutell** [comment]
This is a good first issue. Hint: don't try to implement "this was recently deleted," that is quite difficult. Instead, just edit `lib/modules/apostrophe-images-widgets/views/widgetBase.html` to ensure that if there are zero images, a helpful hint that you may need to select images appears, but only when the widget can be edited by the user (that is, `if data.widget._edit`). You're working on a Nunjucks template, so be sure to learn about those first.

**Comment by zindarato** [comment]
I have a fix for this pending in PR #3040. I am not able to link this issue to that PR, I'm guessing an editor/admin for Apos would need to do that. Hopefully this issue will be ready to close once that PR is reviewed.

**Comment by FullVibranium** [comment]
has anyone been assigned to this issue, I would like to contribute as , I am new to open source I would really appreciate your guidance

**Comment by boutell** [comment]
This fix landed long ago; marking closed. Sorry for the lack of bookkeeping.

**Comment by Harshitahusts** [comment]
can i start working on this, would love to give it try
