### ISSUE TITLE
Image Cropper: pad cropping interface into the modal

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1392]
![image](https://user-images.githubusercontent.com/1889830/40253124-980faddc-5aac-11e8-90e1-2f98ca16b763.png)

When the crop handles are at the edge of the image they are being cut off by the viewport of the modal. Pad the entire interface into the modal more so that crop handles are easy to grab.

Consider disabling the zoom feature.

**Comment by boutell** [comment]
@stuartromanek any concerns with this one?

**Comment by stuartromanek** [comment]
I think this is a fine solution .. the main concern was when the cropper handles would be on the edge of the browser window and difficult to find, so this addresses that.
