### ISSUE TITLE
Array Tabs: Ability to display thumbnails in the tab itself.

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1394]
![image](https://user-images.githubusercontent.com/1889830/40253333-58ddc864-5aad-11e8-9c36-5e1dede244e7.png)

If an array is being used to display visual things like marquee slides etc, we should be able to point the `titleField` option at an `apostrophe-images` singleton and get the first image out of it and display it in the tab

**Comment by stuartromanek** [comment]
I think a convenience should be baked in for images

**Comment by boutell** [comment]
OK!

How about: 

`imageField: 'thumbnail'`

Where `thumbnail` may be an attachment *or* an area (a singleton most likely), in the latter case `apos.images.first` is applied.

Like?

**Comment by boutell** [comment]
Note this means `titleField` may still be specified to have both. Dunno if you like this idea.

**Comment by stuartromanek** [comment]
I do like that idea, marking this for 3.0
