### ISSUE TITLE
Coming from Keystone

### ISSUE THREAD

**Issue by jacargentina** [apostrophecms/apostrophe#1399]
Hi all! I'm evaluating some alternative to KeystoneJS https://github.com/keystonejs/keystone as my entire website is built in it, and i'm very dissapointed with the project progress. For me its like is in a slow path to complete death.

It seems **apostrophe** may be my solution! Seems like a very active project, with manu capabilities. I just wanted to know if i could achieve some specific points:

- Migrate the mongo db from **keystone**; any tutorial on how to import ?
- On keystone i've made some patches (not upstreamed) to serve not only one domain, but **any subdomains**, with the same keystone instance/mongo database (i mean https://pms.nexion.com.ar, https://smarterp.nexion.com.ar and https://www.nexion.com.ar are all the same instance) Is it possible with **apostrophe**

Thanks in advance!

**Comment by boutell** [comment]
Hi @jacargentina! We don't have tools specifically for importing from keystone, but the mongo collections should be pretty straightforward to, for instance, export to CSV (with mongo's command line tools) and then import with the `apostrophe-pieces-import` module. Or you could write an import task yourself that uses Apostrophe's APIs to insert these objects as the appropriate piece type in your Apostrophe site's architecture. The latter would probably be good in the long run.

As for multiple sites on a single instance, yes to the instance, no to the database (they use separate mongo databases, but this is not a huge deal with modern versions of mongodb unless you have many thousands of them). See:

https://github.com/apostrophecms/apostrophe-multisite

Which is nearing production use for our own projects.

This is not really a github issue conversation, so I'm closing it, but feel free to come hang out on the gitter (https://gitter.im/apostrophecms/apostrophe), ask questions on stackoverflow (tagged apostrophe-cms), or reach out via support@punkave.com about an enterprise support relationship.

Thanks!
