### ISSUE TITLE
Ability to render .apos-ui .apos-button as <buttons>

### ISSUE THREAD

**Issue by fredrikekelund** [apostrophecms/apostrophe#1417]
I've run into an issue where I can't nest an area/singleton in an `<a>` element, since Apostrophe injects the `.apos-ui` elements, which in turn contain `<a>` elements for buttons. Web browsers get very picky about that and mess up the layout by moving the nested `<a>`s out of its container, and the whole page breaks.

My widget looks something like this:

`lib/modules/news-item-widgets/index.js`

```js
module.exports = {
  extend: 'apostrophe-widgets',
  label: 'News item',
  addFields: [
    {
      name: '_image',
      type: 'joinByOne',
      withType: 'apostrophe-image',
      label: 'Image',
      required: true,
      idField: 'imageId'
    },
    {
      name: '_page',
      type: 'joinByOne',
      withType: 'apostrophe-page',
      label: 'Page',
      required: true,
      idField: 'pageId',
      filters: {
        projection: {
          title: true,
          slug: true
        }
      }
    },
    {
      name: 'body',
      type: 'singleton',
      label: 'Body text',
      widgetType: 'apostrophe-rich-text',
    }
  ]
};
```

`lib/modules/news-item-widgets/views/widget.html`

```html
<a class="News-item" href="{{ data.widget._page.url }}">
  <img src="{{ apos.attachments.url(data.widget._image.attachment, { size: data.options.size }) }}" alt="{{ data.widget._image.alt }}">

  {{ apos.singleton(data.widget, "body") }}
</a>
```

My current solution is to only render the `apostrophe-rich-text` content, not the whole widget, like this:

```html
<a class="News-item" href="{{ data.widget._page.url }}">
  <img src="{{ apos.attachments.url(data.widget._image.attachment, { size: data.options.size }) }}" alt="{{ data.widget._image.alt }}">

  {{ apos.areas.richText(data.widget.body) }}
</a>
```

That works, but it would be nice to be able to do contextual editing in these scenarios as well. One solution then is to use `<button>`s rather than `<a>`s for the `.apos-button`s. Not sure how high the risk for breakage is with such a change, but it could be hidden behind an opt-in option.

**Comment by stuartromanek** [comment]
We have an issue open about this over at #1111 so I'm going to close this for now.

Happy to review a branch / PR where you replace the elements with buttons in some of our larger projects @fredrikekelund
