### ISSUE TITLE
Change admin bar default state to closed?

### ISSUE THREAD

**Issue by tylerpope** [apostrophecms/apostrophe#1419]
Is it possible to prevent the admin bar from always being open and then closing when visiting a page?

**Comment by stuartromanek** [comment]
Not currently @tylerpope but I think we'd welcome a PR for a setting in the `apostrophe-admin-bar` module for having it closed by default.

If that is something you're interested in we can help point you in the right direction.

**Comment by tylerpope** [comment]
Ah okay got it. I'll go ahead and submit a PR for this - thank you.

**Comment by houmark** [comment]
@tylerpope Please see PR #1449 that adds this functionality — currently awaiting approval and hopefully a merge.

**Comment by tylerpope** [comment]
@houmark yeah that's perfect thanks!
