### ISSUE TITLE
Document edit modal should show 'rescue' under 'more' options when document is in trash

### ISSUE THREAD

**Issue by starsinmypockets** [apostrophecms/apostrophe#1420]
<img width="1366" alt="screen shot 2018-06-09 at 1 32 42 pm" src="https://user-images.githubusercontent.com/949175/41194489-cc761a2c-6be9-11e8-8d13-f0fed5f47cc3.png">
Check out the screen shot. 

* the "trash" option should not be available if item being edited is in the trash
* "rescue" option should be available

**Comment by boutell** [comment]
Implemented in #1801, closing this in favor of tracking that PR.
