### ISSUE TITLE
Newly added fields with a "def" should get that def for existing documents in the database, for field types where this is safe and sensible

### ISSUE THREAD

**Issue by houmark** [apostrophecms/apostrophe#1442]
Running 2.59.0.

I've been trying to get some default options loaded for my widgets. Seems like it's either completely broken, the documentation is incorrect, or I am doing it wrong.

I have tried for pretty much all field types, but no matter what I do, it loads the first option in a select, it does not load a text in a string field etc.

I'm using `def` to set the default value against the value of the select or as a string if a string field.

I would like to dig into the source and try to find out why, but I'm pretty new around here, so I thought I would report it here first... maybe it's not just me?

**Comment by crstnio** [comment]
Hey @houmark,

welcome to Apostrophe!

Would you mind posting some code examples you have tried?

[This question](https://stackoverflow.com/questions/41945540/apostrophe-default-value) has an example. But I can confirm that it doesn't work **before saving** the fields. Did you try that? After saving the modal and reopening it, the default value is set.

I tried:

```javascript
addFields: [
  {
    name: 'learnMore',
    type: 'string',
    label: 'Learn more',
    required: false,
    def: 'Learn something more'
  }
],
```

I agree that the documentation is lacking some information for new users.

**Comment by crstnio** [comment]
Yeah, that shouldn't happen at all.

`select` has the same behavior. Just leave it unselected and save, after that the default option is selected. But again, the default value should be selected on first open.

I set `def` to `value` of the desired choice.

```javascript
addFields: [
  {
    name: 'learnMore',
    type: 'select',
    label: 'Learn more',
    choices: [
      {
        label: 'Test 1',
        value: 'test1'
      },
      {
        label: 'Test 2',
        value: 'test2'
      }
    ],
    def: 'test2'
  }
],
```

Your feedback is much appreciated and I think this will be fixed soon.

**Comment by houmark** [comment]
@crstnio Your example doesn't work (at least not for me).

* Does not matter if has `required: true / false`
* When opening you will see `Test 1` selected by default
* Save
* Re-open and you will have `Test 1` selected (and `test1` saved in the DB)

I have tested this before and re-tested now to make sure, but simply by pseudo reading it seems to me that it cannot work like that, as it will be impossible to actually selection Test 1 and have it saved otherwise (in the first round of saving at least).

**Comment by houmark** [comment]
And unless you have an "empty/fake" option, you cannot leave it "empty" by the way... The dropdown is populated with the options defined, no empty options.

**Comment by crstnio** [comment]
Hmm, I tested that just now and the `select` field is empty on first open. After saving, the default option is selected.

Strange. Currently I dig into the code and hope that my (limited) experience makes me understand what's going on. 😆

**Comment by houmark** [comment]
This is my behavior: [Video demo](https://cl.ly/sVC9)

**Comment by crstnio** [comment]
Very strange. I tested the select field with a virgin widget but after saving options for tests, I can confirm your behavior.

I managed to set `def` as `value` on the input `string` field. But unfortunately, Apostrophe does not use the `value` attribute. It places the values inside a `shadow-root`.

That is the end of my wisdom.

**Comment by boutell** [comment]
def should work, we will take a look.

**Comment by boutell** [comment]
See PR in #1444 under internal review

**Comment by houmark** [comment]
@boutell For what it's worth, I can confirm that it's working in my end using `def` for widgets. Makes sense now :) I did not encounter any regressions, but I also tested very fast and I wouldn't know specifically what to look for in relation to regressions from this fix.

**Comment by crstnio** [comment]
Hm, how about global schema fields?

Setting `def` on a `string` schema field in a module that uses `improve: 'apostrophe-global'` does not work too.

**Comment by stuartromanek** [comment]
I think there is trickiness with adding `def` and then looking at pieces that existed before def was assigned. Those pieces won't populate the def option, which is why `def` and `apostrophe-global` can be at odds (apostrophe-global is just a single piece created in the beginning)

@boutell we've talked about the difficulty in implementing that, should it be a separate 3.0 thing?

**Comment by boutell** [comment]
Aha yes that is it. Not a bug but quite annoying. You could write a
migration.

**Comment by boutell** [comment]
We could write a task to automatically add defaults where the field type is marked as safe for that purpose. That task could be automatically invoked by apostrophe-migrations:migrate. I've retitled the ticket to be about that. It's not a bug but it would be a lot nicer to have it.

**Comment by boutell** [comment]
Hmm, this task would not be part of the every-deployment migration process because it is potentially time consuming, especially if it has to track down your objects in arrays and widgets. It could be a run-on-demand thing though.
