### ISSUE TITLE
Confusing pieces manager instructions

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1450]
https://github.com/apostrophecms/apostrophe/blob/2fe3ba010bba0217d98614ccfdb03e98eb79cd0b/lib/modules/apostrophe-pieces/views/managerModalBase.html#L15

This help text for the manager modal is confusing to me. It seems like this is the instructions for `apos-pieces-widget`, not the pieces manager.

It looks like this used to be "Here you can add new {{ data.options.pluralLabel }} or click on existing {{ data.options.pluralLabel }} to edit them." That seems much better.

**Comment by boutell** [comment]
Yes it's just wrong, not sure how that crept in, PR away.
