### ISSUE TITLE
path property should be made up of _id strings to avoid complexities around duplication and the trash

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1462]
User-readable strings in path were cute right up until the moment they weren't. The logic to rewrite path in such a way that it doesn't cause duplication when a page is in the trash on a workflow-related site and someone makes a new page at that path simply shouldn't have to exist. And there are likely other performance wins from being able to just get straight to the _id of an ancestor rather than the ancestor's `path`.

**Comment by nofwayy** [comment]
Interesting. Would be great to develop that approach and see what kind of other perdantes wins we could have here
