### ISSUE TITLE
Add help text to permissions options

### ISSUE THREAD

**Issue by agilbert** [apostrophecms/apostrophe#1468]
The group permissions system is extremely powerful and configurable at a very detailed level.

But when configuring permissions, there is no information present on how to use them in UI, thus making it unlikely a site admin will be able to understand and take advantage of these features.

![image](https://user-images.githubusercontent.com/70999/42225401-846306b8-7eaa-11e8-892d-596c1df1e474.png)

**Comment by boutell** [comment]
Closing because the new extended permissions feature will bury this one pretty solidly and the legacy permissions, while available, will not get new love.
