### ISSUE TITLE
3.x: MongoDB 3.x driver must be used

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1473]
According to this chart there is no downside in terms of compatible versions of mongodb server:

https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility

And the only way to work with MongoDB 3.6 or 4.0 server is to use the new driver.

There are bc breaks which are significant for legacy projects but reasonable for a new major version of apostrophe:

https://github.com/mongodb/node-mongodb-native/blob/HEAD/CHANGES_3.0.0.md

The connection approach, connection URLs and removal of the projection argument to find() are all a pretty big deal.

**Comment by nofwayy** [comment]
Think we will need that on 2.x also
