### ISSUE TITLE
Alternative to apostrophe:migrate

### ISSUE THREAD

**Issue by 13MS** [apostrophecms/apostrophe#1489]
The tutorial to deploy on Heroku includes this step:
`APOS_MONGODB_URI=mongodb://YOUR-uri-goes-here node app apostrophe:migrate`
I am getting a 'There is no such task.' error, suggesting a list of possible tasks. Has this function been deprecated? And if so what should I use instead?
Thanks!

**Comment by boutell** [comment]
Typo fixed. Should be `apostrophe-migrations:migrate`. Thanks for catching it.
