### ISSUE TITLE
Notification colors aren't set with modals open.

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1491]
When modals are open, the notifications take their styles from `.apos-ui .apos-notification` rather than `.apos-notification--error` (for example).

![notification-color](https://user-images.githubusercontent.com/1155984/42699219-1baf3f24-868e-11e8-932e-8e0a5c7a401f.gif)

**Comment by houmark** [comment]
@abea If you can test that my pending PR will fix your situation, then I'm pretty sure it will fix colors all the way around. I tested various situations, but I would like your confirmation that your situation is also fixed with my PR.
