### ISSUE TITLE
Reached maximum area loader recursion level after edit blog page

### ISSUE THREAD

**Issue by andreysolovyov** [apostrophecms/apostrophe#1502]
Hello!

I'm facing troubles with accessing apostrophe site.
After some tries of edit blog article content I'm getting warning "reached maximum area loader recursion level" and site did'not loading any page anymore.

Does any safe load way exists to prevent error?

**Comment by abea** [comment]
That error is often related to using joins that don't have projection filters applied. Are you using `joinByOne` or `joinByArray` fields in these places? Or in widgets that are there?

There's more information about this in the guide to schemas for those types: https://apostrophecms.org/docs/tutorials/getting-started/schema-guide.html#code-join-by-one-code

**Comment by boutell** [comment]
This is not a bug (see comment from @abea) but feel free to reach out with more questions if you have trouble following his advice after reading the notes in the schema guide about projections.

**Comment by andreysolovyov** [comment]
Ok. Im my case the root cause of problem was incorrect widget data referrence. But, to fix this issue and turn back my site up I have to open database and manually fix incorrect widget bindings. I mean that it is not ok to crash all site caused local widget error.
