### ISSUE TITLE
Add search disabling for page types and individual pages

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1533]
This came out of a recent client request. It would be useful to add search disabling via a page settings field in the UI (like navigation exclusion).

It might be good to also allow devs to disable search on page types like they can on piece types now with `searchable: false`. We were hoping to use this to create a parked page with a disabled type, but there could be other use cases. At least this creates more parity with pieces.

The individual page exclusion is probably more important though, for pages that aren't sensitive but the site admin wants to be "private."

**Comment by boutell** [comment]
This could be done in a module that "improve"s apostrophe-global and adds the relevant fields to its schema, and also "improve"s apostrophe-search to use the information. Some PRs to apostrophe-global in core might be needed if the code is too monolithic and overridable methods need to be added.
