### ISSUE TITLE
Implement webpack pipeline

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#1580]

**Comment by bobclewell** [comment]
Attached myself to this one out of interest to learn more about webpack. I'm thinking I can learn more as part of this task.

**Comment by boutell** [comment]
This has mostly happened, but we haven't addressed styles yet beyond inline styles in a component, and a decision hasn't been made to commit to those. cc @bgantick

**Comment by bgantick** [comment]
Still to add: hot reloading, environment based minifying/logging (right now webpack is running in development mode all the time).
