### ISSUE TITLE
minSize in apostrophe-images options does not filter the correct sizes.

### ISSUE THREAD

**Issue by grdunn** [apostrophecms/apostrophe#1626]
Bug: When using the `minSize: [ x, x ]` option in apostrophe-images, a user is able to select images that are smaller then the specified size. 

Steps to reproduce: 

1. Add this field to any piece, or widget schema:
```
{
      name: 'image',
      label: 'Thumbnail',
      type: 'singleton',
      widgetType: 'apostrophe-images',
      required: true,
      options: {
        aspectRatio: [1, 1],
        minSize: [500, 500],
        limit: [1]
      }
    }
```

2. In the corresponding editor modal for the piece/widget with the above schema field added, you should be able to view a filtered media library (it does appear to be filtering on some level...), however there are still available options that are smaller then the 500 x 500 specified `minSize`.

**Comment by boutell** [comment]
Ping - can we get a reproducible example?
