### ISSUE TITLE
Add pattern property to text field schema options

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1633]
A `pattern` property on a string schema would then add the value to the `pattern` attribute on the input field for basic enforcement of an input pattern. The native browser alert would appear, assuming Apostrophe is letting the native form submission do its work.

```
    {
      name: 'favLetter',
      label: 'Favorite Letter',
      type: 'string',
      help: 'Enter a single capital letter',
      pattern: '[A-Z]'
    },
```

One use for this would be to update apostrophe-redirects to make sure that the "Old URL" starts with a forward slash.

**Comment by boutell** [comment]
The example should read:

`pattern: '^[A-Z]$'`

Otherwise it matches anything that *at least* contains a capital letter.

Also I would recommend that empty strings not be validated by the pattern. Instead they would be validated by the `required` property.

**Comment by houmark** [comment]
Should also define which field types a pattern could apply to.

String, integer, float, slug, date, time, password?

**Comment by abea** [comment]
Not sure if we're passing one another in the night here, Tom. I'm talking about using the native HTML input attribute, which does not validate against empty fields from what I can tell. So `required` would still do the work there.

Any server-side validation using the pattern would then only need to be for legacy browsers so old they don't know about the pattern attribute.

For now I'm only thinking of using it on strings. Fields like url, number, date, etc have built in validation if we're using native HTML types. Password is a whole bucket if fish I'm not sure we should get into and would probably need to be a whole conversation. Regardless, doing it for string fields would prep for being able to do it anywhere else.

**Comment by houmark** [comment]
All validations runs both client and server side, so to make sure this works in all clients, I guess it should part of validations, just like a range validation.

pattern in html5 will also change input keyboards in some mobile browsers, so I am not sure it's the best approach to use pattern at the input field at all.

**Comment by abea** [comment]
Why do you say that, @houmark? If mobile devices change their keyboards based on the input attributes to make entering easier for people, why not let them do that here too?

**Comment by boutell** [comment]
Ah. I wasn't aware of it.

**Comment by boutell** [comment]
Except, pattern is indeed looking for a regular expression, so my comment
on the error in the example is valid.

**Comment by boutell** [comment]
Pattern *is* a regular expression, so enforcing the same one on the server
makes sense. As for the interaction with required, we should see what
browsers typically do in the presence of pattern, and match that behavior
in the server side enforcement.

We could have a separate option for oddball cases where you want a "wrong"
pattern attribute in the browser just to force a keyboard, that way for
normal cases we have consistency. We can still enforce the actual pattern
on both ends too to save the user a round trip and a server error.
