### ISSUE TITLE
3.0: JSON APIs need review for efficient representation, code duplication, ease of authoring

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1662]
I am working on the overhaul of the code to use async/await rather than callbacks, which is not controversial; callbacks gotta go in 3.x. We have come very far with promise support in 2.x but callback based code is too hard to maintain.

In the process I'm hitting a few things that I can make easier for everybody while I'm in the midst of this overhaul in which I do see just about all of the code, at least in passing. 

This one is worth bringing into a ticket to capture thoughts and comments:

* Our JSON APIs respond with a JSON object with a status property, which might be `ok` or `invalid` or one of pretty much a handful of other values.
* HTTP status codes do this more efficiently and are familiar to REST developers, even if these APIs aren't strictly REST at all times... because there are too many edge cases that don't fit REST for the use of our own admin UI, but we have `apostrophe-headless` which provides quite a strong REST interface for the common cases.
* `async` functions are the way to go for 3.x, but Express doesn't natively do anything useful if a promise is returned by a route, such as catching errors if it rejects. So we wind up with a `try/catch` block in every route, doing the same thing in every route.
* This has led me to this approach:

```
  self.apiRoute('post', 'save-area', async function(req) {
    await self.lockSanitizeAndSaveArea(req, req.body);
  });
```

This is pretty neat: thanks to async/await, if this code throws an async exception, `apiRoute` will catch it and convert it to a suitable HTTP status code based on our traditional strings which are easier to remember and use consistently. 

On success, apiRoute will respond with a `200` status code, and send the return value... which could be a data object *or* a markup fragment *or* nothing much... as the response body.

Very tidy.

Another example:

```
  self.apiRoute('post', 'editor', async function(req) {
    return await self.render(req, 'editor');
  });
```

Here there is a return value, which becomes the response body.

In addition you can write:

`throw self.apos.http.error('required', { field: 'name' })`

If you feel the need to send the browser a response object in addition to an HTTP status code for your error.

You can't do a redirect with this, but redirects are not typical for API routes.

This feels like a good approach but I wanted to put it out here to gather any thoughts and concerns.

**Comment by nofwayy** [comment]
This is good stuffs ! Thanks for that proposal @boutell

I will add that there is some advanced use cases like setting a caching policy or changing the response type that would require access to the response object.

**Comment by boutell** [comment]
Indeed, but since we want to make sure developers clearly understand they don't have to send the response themselves (and save them from "you responded twice" errors), I think our best course is to intentionally leave out `res`, while documenting that you may access `req.res` if you want to change headers etc. as long as you're not actually sending the response.

**Comment by boutell** [comment]
We've gone ahead with this approach generally. Also we've chosen to keep APIs unique to our editing experience as a complement to conventional REST/headless APIs rather than attempting to force-fit everything to REST where we have good patterns that still make sense in our new Vue world.
