### ISSUE TITLE
Change automatic slug generation for files to include a file namespace

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1665]
This is to avoid a file called `great program.pdf` from taking the slug `great-program` when they'll later create a program piece called "Great Program." I've seen confusion several times when a client is trying to set a nice clean slug for the URL and an image or PDF already has that one.

I'm thinking files could have their slug include the filetype, e.g., `great-program-pdf`. Maybe this could be included in 2.x as well if only done on creation.

**Comment by boutell** [comment]
This was fixed at some point, file slugs are prefixed with `file-`.
