### ISSUE TITLE
Apostrophe lacks a way to create reusable components within templates that can access the model layer while following well-known MVC patterns

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1668]
We can argue till we're blue in the face that the current setup is good model-view separation, but people just find it really baffling that you can't load extra stuff or do anything asynchronous in a template.

It may or may not be practical, but nunjucks does support certain kinds of async features, and we should at least seriously consider enabling them. So a simple thing like "let me find related events by doing a search query on the show page" can be implemented by a typical developer.
 
Also, putting the plumbing in place for this opens the door to alternative rendering engines that are asynchronous, such as Vue server side rendering.

Another issue is that Nunjucks allows asynchronous filters (`|` stuffs) and asynchronous extensions (which introduce entirely new `{% tags %}`, but has no concept of asynchronous helper functions. Which means even after we do this, `{% set related = apos.events.find({ search: event.title } %}` is STILL Not A Thing That Can Be Written.

But this would be possible, as a custom async extension:

`{% find related = apos.events({ search.title }) %}`

And maybe that's even the perfect feature to offer out of the box in 3.x, as a starting point to Some Async Cool Shit Being Possible In Templates.

But this requires discussion, and I'm prepared to take "um, no" for an answer if that's the consensus.

P.S. I've talked about a weird thing in Nunjucks where you have to use `asyncEach` loops instead of `for` loops. As it turns out this only applies if you're going to `{% include %}` *and* you're going to do the including with an async template loader. And, that's not what we're doing - we're not interested in fetching template markup itself asynchronously. Just doing some async content fetching from databases, and that's something Nunjucks can automatically spot and infer that it has to turn "for" into "asyncEach" under the covers without baffling the developer. So that bit is :100: after all.

**Comment by abea** [comment]
How would this be different from running async functions in the `beforeShow` method, for example?

**Comment by grdunn** [comment]
I've never been frustrated not having the ability to fetch stuff directly from the template, but I can obviously see the value when it's presented like this :). Will something like `apos.events({})` potentially support projections,  criteria and the like? I'm all in favor of reducing the amount of code required in `index.js`/ config files to support these kinds of often used utilities.

**Comment by boutell** [comment]
@abea if you understand that mechanism and why you need it, it's not different. If you're coming from (fill in basically any framework that isn't apostrophe here), where you can pull stuff right from templates, it's a big learning curve and frustration point. Which is what I'm seeing in gitter all the time.

Also, and perhaps more important, if you're doing something like Vue server-side rendering you might not know what you need *until* processing happens inside the Vue code.

I would revise the syntax proposal to:

`{% find related in events { search: piece.title } %}`

Hmm, is that better or not? I just want to get away from inferring that `apos.events` is a function you could also call elsewhere, when it definitely isn't.

Another try:

`{% find related in events filtered by { search: piece.title } %}`

Well... that is readable...

We can take "apos." as read because this is an apostrophe-specific tag to begin with.

**Comment by boutell** [comment]
@grdunn I'm opening and closing my mouth re: how to answer your question about what you can actually do in find()...

Just a criteria object won't cut it, my search example wouldn't be possible.

Making it hard to pass a criteria object, however, would also be a nonstarter.

We have these lovely chainable filter methods, you should be able to use them huh.

So, I propose that all of the following should work:

```
{# Get the blue products using a criteria object and a projection filter #}
{% find blueProducts via products({ color: 'blue' }, { title: 1, _url: 1 }) %}
{% find blueProducts via products({ color: 'blue' }).project({ title: 1, _url: 1 }) %}

{# Find related events via the search filter. Passing criteria is optional since it's empty #}
{% find related via events.search({ title: piece.title }) %}
{% find related via events({}).search({ title: piece.title }) %}
```

We can of course chain the filter methods, i.e. search, project, etc. Note that just passing a projection as a second argument is still allowed in Apostrophe, even though in Mongo that went away in the 3.x driver (you must chain a method).

**Comment by bobclewell** [comment]
Writing queries in templates feels very off to me. A total code smell. At least coming from a Rails/Laravel world. 

Could the confusion be that right now this is all happening in `index.js`? It sounds like we are talking about a controller layer here. Is that right? Maybe the answer is a `controller.js` file to keep these type of queries organized? . . . .  https://sailsjs.com/documentation/anatomy/api/controllers

Or maybe we have as a best practice of using a `beforeShow.js` file that does this? Generally, I've been thinking a little about how it might make sense to make `index.js` in projects smaller. E.g. a best practice of using `schema.js` for example.

**Comment by grdunn** [comment]
@bob +1 on the controller bit.

**Comment by boutell** [comment]
Bob, I'm going to press you on the rails / Laravel thing - really no lazy
loading / fetching of related stuff based on things coming from the
template? I know that is super common in a Symfony / doctrine b world.
Maybe the problem is that I'm not able to deliver this as methods of the
piece you already have. (I really can't. That's not a place where nunjucks
permits asynchronous code to be put.)

**Comment by stuartromanek** [comment]
This feels fine and is tidy and nice but it doesn't really make finding extra stuff easier, does it? Getting stuff to the template feels like the easy part.

**Comment by boutell** [comment]
Stuart what do you see as the hard part?

**Comment by stuartromanek** [comment]
I'm in favor because it gives us a formal way to describe the process of getting extra stuff to the template.

My other comment was more like
Proposal 1 does a lot for you: it runs a query and returns the results to your Nunjucks variable. Very easy but feels weird.
Proposal 2 gives you a formal pattern for getting extra stuff to the template but you still have to know how to do the plumbing, it doesn't abstract away the query part. Which feels good, but is that solving the intent of the ticket?

Either way, again, I like the formal way this will let us describe the process.

**Comment by boutell** [comment]
Yes... I think the `{% component %}` proposal gives us a formal way to describe how to get extra stuff, *and* make reusable components that can get stuff regardless of which template you just included them in, *and* opens the door to SSR.

It follows MVC patterns, to address @bobclewell's reasonable objection that the `{% find %}` proposal pretty much chucks model-view separation entirely.

But no, it's not a trivial answer to the question that started this ticket. I think it is an answer we can feel good about asking people to master, though. And the experience of other frameworks like Symfony and Rails shows that people can master it, as long as you give them structure ("dammit where does my code go?" must have a simple answer).

**Comment by pietro-rutzen** [comment]
I came initially from the Rails community and data seems much more accessible for people who are just starting with the framework, and methods to be used in the front-end seem flow with more ease, as in Apostrophe right now we have to create a custom filter in nunjucks to solve certain scenarios, adding a second layer of backend aside from your usual Node programming schedule. And the learning curve for this might be a bit harsh.

Html is universal, and a lot is done by Apostrophe to automate the interactions with the back-end database to get things structured, but now the next natural step would be to think about front-end developers who just want to produce the most aesthetically pleasing experience for their users using, if possible the least amount of code. If I could just throw a couple of for loops and have my page ready I'd be very happy and could put my efforts into high-level project decisions.

Also the reason I comment in here is that in gitter, we were talking about the current use of widgets as partials. Usually this works, but when you want the same data used in different layouts you need to write `data.page` conditionals INSIDE the widget, which does not seem intuitive at all.

I think the `{% component %}` proposal would fit very nicely in various aspects and would make the learning curve easier for people who are not used to NodeJS.

**Comment by boutell** [comment]
@pietro-rutzen it is worth noting that you do have access to `{% include %}` and to `{% macro %}`, which can be used much like partials. You still need access to the data, of course. You can accomplish that access with an `apostrophe-pages:beforeSend` event handler now, adding it to `req.data`, but I agree that components will give users a more clearly understood place to put the code. And a clear error message if the code is missing, which can tell them exactly where to put the code (:
