### ISSUE TITLE
Problem with users permission.

### ISSUE THREAD

**Issue by GiuseppeCM** [apostrophecms/apostrophe#1685]
I have a "first" piece with a joinByOne to a second "lookup piece". In this scenario I have an authorization problem: If I don't give the user permissions to modify the "second" piece, but just "edit permissoin" on the "first" piece, when the user open the modal to choice the "second" piece gives an error, like if he were not authorized to choose an item.

This is my example [repo](https://github.com/GiuseppeCM/test-elasticsearch)

To replicate the error:

- add two groups, admin and edit;
- add two users, admin and edit;
-  log into site with admin user;
- set permission like this for edit group:
       Admin:amministrazione (edit) workflow;
- log with edit user;
- try to add an "amministrazione";
When the modal about "amministrazione" is open, choose one "apertura" or "chiusura".
This is my error in browser console:
`Uncaught Error: Syntax error, unrecognized expression: {"status":"forbidden"}
    at Function.Sizzle.error (jquery-3.js:1541)
    at Sizzle.tokenize (jquery-3.js:2193)
    at Sizzle.select (jquery-3.js:2620)
    at Function.Sizzle [as find] (jquery-3.js:845)
    at jQuery.fn.init.find (jquery-3.js:2873)
    at new jQuery.fn.init (jquery-3.js:2983)
    at jQuery (jquery-3.js:139)
    at Object.success (modal.js:109)
    at fire (jquery-3.js:3268)
    at Object.fireWith [as resolveWith]`

**Comment by boutell** [comment]
I just did a test of this kind in the apostrophe-samples project:

https://github.com/apostrophecms/apostrophe-samples

I created a test group whose only privilege is "admin products," and as a user in that group I was able to edit a product and select a specialist to join it to, even though I don't have any editing privileges for specialists.

So this all seems to be working OK. I suspect there is still a bug here somewhere, though, so feel free to reopen with a test project and very specific steps to duplicate the issue.
