### ISSUE TITLE
New Feature: schema field to support autocomplete from external endpoint

### ISSUE THREAD

**Issue by shauravg** [apostrophecms/apostrophe#1687]
This is a new feature request. We are currently using Apostrophe for a client project of ours. If this request is more appropriate for the enterprise side of things, the client is open to that. I just wanted to start here and see what fulfilling this feature request might take.

The request is to allow a schema field where the user can type in a string and be given autocomplete choices they can select from. The choices are served from a API which is being given the user input as they type. Once the user chooses a selection, then that selection's JSON output is stored as part of that piece and then further consumed by a website which uses apostrophe-headless. 

Let me know also if I could provide more details.

**Comment by shauravg** [comment]
Hi Tom. We are using joinByArray but let me be more specific about the UX that I think is not currently there. I also sent an email referencing this issue for enterprise support specifics.

Our website is for a real estate company which will have a main site and few subdomain sites (one per agent). The agent profile, blog, and various other things come from Apostrophe CMS (via apostrophe-headless). On the home page of each agent subdomain, there is a list of highlighted regions that the end user can click on and be routed to a page which shows them all listings for sale in that region. Each agent is given a login to CMS and they can edit their profile as well as the list of highlighted regions for their specific subdomain site.

Our model is as follows:
1. Agent piece type which has things like agent name, phone #, and a field that joins to highlightedRegion piece type via joinByArray
2. highlightedRegion has a single user entered attribute 'regionName'. The key piece missing is that when a user begins to enter something into regionName, we want to pass that to an external API which contains a list of all cities, counties, zipcodes, states and their geographical coordinates and gives us results from the which the user can choose one (i.e. autocomplete). Once the user chooses one of the results from this external API, we want to then store the name within regionName and pick up a few additional attributes like geographical type (string) and coordinate array (object).

Then, we can use apostrophe-headless to query the agent piece type and render the website accordingly.

**Comment by stuartromanek** [comment]
In another Apostrophe project I had solved a similar problem by creating a custom field type that mimics a normal string field but has extra front-end logic to talk to a back-end route, which makes and returns API requests. [More on custom field types here](https://apostrophecms.org/docs/tutorials/intermediate/custom-schema-field-types.html)

Would this be a road you would suggest @boutell ?
