### ISSUE TITLE
lib/modules and app.js can become very long, nesting of some sort would help structure them

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1692]
After some discussion of various approaches we're moving ahead with optional support for nesting your modules in subdirectories, as requested by an enterprise client and discussed amongst the team.

Both the team and the client seem to prefer this approach, which I’ve refined a little here to try to cover the edge cases:

• lib/modules MAY contain nested subdirectories, purely for aesthetic grouping purposes. You can nest as deep as you like. But, these “parent” directory names don’t matter.
• Only the names of the actual module subdirectories at the bottom matter. If two of them have the same name, in different parent directories, Apostrophe will detect the situation and throw a helpful error.
• The parent subdirectories MAY contain a `modules.js` file, which exports an object containing the relevant part of the `modules` config from `app.js`. So if you go all out with this, you don’t even need a `modules` property in `app.js`.
• The only modules a folder can configure in its `modules.js` are those it actually contains, as its immediate children. We check this too.
• **Unrelated files and directories, aka libraries:** you may create `/lib/modules/widgets/lib` to keep some useful tidbits for widget modules in, and put the actual widget modules in `/lib/modules/widgets/cat-widgets`, `/lib/modules/widgets/dog-widgets`, etc. However, you **must not place a file called `modules.js` in any folder beneath `lib/modules` that is not intended to be read and merged with `app.js`.**

**Comment by boutell** [comment]
The algorithm to be added to `moog-require` is:

1. Start with `M`, the `modules` config from `app.js`.
2. Iterate subdirs of `lib/modules`. If they match a module mentioned in `M`, load them as modules and do not recurse further in those dirs. If we have seen a module already, throw an error and stop.
3. Otherwise, if they contain `modules.js`, read it and merge it with `M`. First note that each module mentioned in it must be nested within this subdir folder. Then recursively apply steps 2-3.
4. If a module mentioned in `M` was not in the top-level `app.js` and was not found, throw an error.

**Comment by boutell** [comment]
I think that 100% guaranteed bc here is impractical, and it would be smartest to simplify:

* You must pass the `nestedModuleFolders: true` option to Apostrophe, or the behavior is unchanged. Now, let's assume that flag is set:
* Any `modules.js` under `lib/modules` is read and merged with app.js before individual modules are loaded.
* The keys of `modules.js` are then iterated in the usual way.
* Any `/lib/modules/**/foldername/index.js` combo where `foldername` matches the module name is accepted; if there is more than one we throw an error.

That's all.

**Comment by nofwayy** [comment]
If I understand this change correctly, we can now have some bundle like configuration at project level. which is really good. I wonder, however, if this change would also be expected to work at node_modules level

**Comment by nofwayy** [comment]
Thanks @boutell. I guess I’ll give it a try then, I needed that pattern to abstract uploadfs overrides in a user friendly way.
