### ISSUE TITLE
Unable to run minification

### ISSUE THREAD

**Issue by dnieuwstadt** [apostrophecms/apostrophe#1701]
Apostrophe Version: 2.72.1

We are attempting to minify our app but after using the _APOS_MINIFY_ flag we aren't seeing a minified JS file at the foot of the body as expected, we are still seeing the individual JS files.

We are successfully running a legacy version of Apostrophe of 2.46.1 and the minification is working as expected.

We start our app with the following command:

`APOS_MINIFY=1 APOS_MONGODB_URI=*** node app.js`

**Comment by boutell** [comment]
I am unable to reproduce this in our sandbox project. I think you might not be looking at the same copy you're running. Closing for housekeeping but feel free to reopen with details on how to reproduce this successfully with a publicly available project such as:

https://github.com/apostrophecms/apostrophe-sandbox
