### ISSUE TITLE
Cooperating ApostropheCMS with BarbaJS

### ISSUE THREAD

**Issue by ammein** [apostrophecms/apostrophe#1711]
Imagine a site uses BarbaJS for a great user experience between page transitions , it would be awesome to have this feature as well. But for now , it is nearly impossible to be done due to the natural behavior of ApostropheCMS that constantly need `apos.change()` to re-render the content on page.

**Comment by boutell** [comment]
Such a change would not make sense in the core of apostrophe which already pushes too much frontend javascript, but you could implement a new module that adds the capability.
