### ISSUE TITLE
Duplicate key error when using Azure Cosmos DB

### ISSUE THREAD

**Issue by Syacqu** [apostrophecms/apostrophe#1713]
Hi!

I've been working on a simple website using Apostrophe for the past week and quite like it so far. However, I'm currently having trouble getting things up and running on Azure. When I switch from the local database to Cosmos DB, I get the following error:

> WARNING: unable to ensure text index, apostrophe:migrate can fix that
> 
> /Users/john/test/node_modules/apostrophe/index.js:73
>         throw err;
>         ^
> MongoError: E11000 duplicate key error collection: admin.aposDocs Failed _id or unique key constraint
>     at Function.MongoError.create (/Users/john/test/node_modules/mongodb-core/lib/error.js:31:11)
>     at toError (/Users/john/test/node_modules/mongodb/lib/utils.js:139:22)
>     at /Users/john/test/node_modules/mongodb/lib/collection.js:668:23
>     at handleCallback (/Users/john/test/node_modules/mongodb/lib/utils.js:120:56)
>     at resultHandler (/Users/john/test/node_modules/mongodb/lib/bulk/ordered.js:421:14)
>     at /Users/john/test/node_modules/mongodb-core/lib/connection/pool.js:469:18
>     at process.internalTickCallback (internal/process/next_tick.js:70:11)

This error occurs even when the database uri is the only change I've made to the boilerplate Apostrophe project. Locally everything runs just fine.

I'm rather inexperienced when it comes to web development and haven't been able to find a solution so far, so any help with this issue would be appreciated.

**Comment by boutell** [comment]
CosmosDB is partially, not completely, mongodb-compatible. I would suggest that you open an issue with the CosmosDB team about this. They may be interested in making it more fully compatible and ensuring that it works with Apostrophe. But Apostrophe is documented to support MongoDB, not CosmosDB, so I am closing this issue for now.

**Comment by boutell** [comment]
(If you need MongoDB in the Azure cloud, try MongoDB Atlas. Their hosted offering can be deployed within Azure.)

**Comment by Syacqu** [comment]
Thanks! Switching to MongoDB Atlas worked out.
