### ISSUE TITLE
Problem with apostrophe-headless and apostrophe-workflow

### ISSUE THREAD

**Issue by GiuseppeCM** [apostrophecms/apostrophe#1731]
Hi all, I have a probelm with apostrophe-headless. As long as apostrophe-workflow was not active the insert page work, but since I activated this, the post return `notfound`.After the 'pos', in mongodb I have the document, so the insert the insertion was successful, but the respons is `notfound`.
Investigating I saw that: in `apostrophe-headless/lib/modules/apostrophe-pages-headless/index.js` at line 155 have function "post one" and in `async.series` the ultimate functions (find), when try to execute it `self.find(req, {}).and({ _id: safePage._id }).published(null)`, the return is undefined.
For my opinion the problem is: with the workflow you add new criteria in the find query and search `workflowLocale`in the field page, but the first write on mongo is the `workflowLocale-draft`

**Comment by boutell** [comment]
There is likely more to be considered here before workflow and headless can work together harmoniously. It is not clear what the best approach is.

**Comment by jkumara** [comment]
Hi! Are there plans to get these working together some time in the future? We're considering to use Apostrophe as a headless CMS for a big client, and this would be a really great feature to have.

**Comment by boutell** [comment]
Hi @jkumara, it is not currently a pressing need for our clients. if you would like to see this pushed forward more quickly please reach out for Apostrophe Enterprise Support:

https://apostrophecms.org/support/enterprise-support

**Comment by boutell** [comment]
Closing this as it should be an issue on apostrophe-headless.
