### ISSUE TITLE
schemas has object and nested arrayitems, not working, return 400 bad request!

### ISSUE THREAD

**Issue by QuietWind** [apostrophecms/apostrophe#1740]
curl 'http://localhost:3456/modules/apostrophe-schemas/arrayItems' -H 'Cookie: pma_lang=zh_CN; Hm_lvt_dde6ba2851f3db0ddc415ce0f895822e=1544277959,1544889672,1545033368; costa-jp-cms.csrf=cjq2dhy35000348sxm7kwzyrz; costa-jp-cms.sid=s%3AiF0MCQcmPzpOcFOYkSm2RG9cdNADp8VF.VMahR3m8NnyUi6I1ThOW37qsejAacE%2FsOag1HWN9WVU; costa-jp.csrf=cjq34odki0003a3yrqwd6jrid; Hm_lpvt_dde6ba2851f3db0ddc415ce0f895822e=1545809376' -H 'Origin: http://localhost:3456' -H 'X-XSRF-TOKEN: cjq2dhy35000348sxm7kwzyrz' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en,zh-CN;q=0.9,zh;q=0.8,ja;q=0.7' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: text/html, */*; q=0.01' -H 'Referer: http://localhost:3456/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Apostrophe-Html-Page-Id: cjq4uzg5v0003puyr5xhprkv2' --data-binary '{"active":0,"arrayItems":[{"id":"w196063671882755679","_ordinal":1}],"field":{"type":"array","name":"contactContent","label":"ContactContent","schema":[{"type":"string","name":"value","label":"Value","required":true}],"titleField":"value"}}' --compressed
----------------------------------------------------------------------------------------------------

above curl request and response
![image](https://user-images.githubusercontent.com/8223607/50437472-d0ea4f00-0924-11e9-8a52-257d540b05b7.png)

I find open source code eg: 

![image](https://user-images.githubusercontent.com/8223607/50437564-3c342100-0925-11e9-9a8b-e892d3a3f96a.png)

new array struct cannot bless

**Comment by boutell** [comment]
Closing this due to lack of response but feel free to provide a test case at some point.
