### ISSUE TITLE
Drag and drop for recently created widgets doesn't work

### ISSUE THREAD

**Issue by priethor** [apostrophecms/apostrophe#1766]
When the add a widget to an area, if you try to move it as soon as you create it, it can't be dropped. However, if the page is refreshed, the recently created widget can be moved correctly.

This behaviour can be reproduced directly in the [Open Museum demo](apostrophecmsdemo.org), by adding a Rich Text or link widget in any area and trying to move it after it's saved, in either Chrome, Firefox or Edge.

**Comment by boutell** [comment]
The PR #1792 resolves this. You can track its progress to publication there. Thanks for reporting it.
