### ISSUE TITLE
The embedded Rich Text editor

### ISSUE THREAD

**Issue by SnigBhaumik** [apostrophecms/apostrophe#1770]
While the whole framework Apostrophe is awesome, the embedded rich text editor (CKEditor) falls miles behind than its other features and capabilities.

Modern HTML editors has gone far ahead in terms of functionalities and user friendliness.
For example, https://wordpress.org/gutenberg/ or aloha editor.

Is there any plans to replace this CKEditor with a new more powerful one? 
Or least the default Apostrophe boilerplate project must include all available and possible plugins and configurations built-in and shipped with it.

They need an excellent WYSIWYG editor, just as excellent Apostrophe product is!

**Comment by boutell** [comment]
Yes, Apostrophe 3.x will have a new rich text editor. You can follow our experiments on that in the `3.0-tiptap` (tiptap, which is based on ProseMirror) and `3.0-rich-text` (CKEditor 5) branches. There are many issues, including licensing (Apostrophe is MIT licensed and we intend to keep it under a permissive license, some of the editors are not).

**Comment by SnigBhaumik** [comment]
Surely I understand the licensing issue Tom. 
Even with the CKEditor in Apostrophe 2.x, can we have a separate module that comes configuration bundles with all the default CKEditor toolbars and features. And also probably most common CKEditor plugins.

We were trying to add the **_sourcecode_** plugin/feature of CKEditor without much of a success. Have followed instructions from https://apostrophecms.org/docs/tutorials/howtos/ckeditor.html and some of the SO threads as well.

**Comment by boutell** [comment]
I suggest that you share a simple test project in which you have made a
best effort to get this to work. That how-to has been used successfully to
enable many different ckeditor plugins.
