### ISSUE TITLE
Click-drag not working in Firefox or Safari in area widgets

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1771]
Related to `3.0-tiptap` branch at time of reporting.

In the TipTap rich text editor with Firefox or Safari you can click and drag text to select specific text. In Safari, you also can't double click a line to select it (visibly) or use the keyboard to select text, though the editor does seem to recognize that the line is in focus. In FF, you can doubleclick a line to select the full line, or use the keyboard to select words.

These operations works as expected in Chrome and Opera.

**Comment by abea** [comment]
jk. Not related to TipTap. This is happening with non-TipTap widgets and with vddl (our dragger) disabled as well. It seems to be a bug in the core area editor.

**Comment by boutell** [comment]
Closing because the area editor has been pretty much rewritten, but we can reopen if it comes back to liiiife
