### ISSUE TITLE
User and group permissions are confusing and too coarse-grained

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1781]
The permission picker used when creating groups (and sometimes users) was implemented in the quickest possible way. There's a lot of power there, but the interface is baffling and rarely understood even in-house.

Per discussion with @carlykaras, @bgantick and @stuartromanek, we'd like to redesign the permissions tab for groups as follows.

### Overall Permissions

[ ] Admin: All

*Allows group members to do anything, including creating more users and groups.*

### Page Permissions

Pages: [ ] Select All / Remove All

[ X ] Edit Any   [ ] Create New [ ] And Move to Trash 

Members of this group can also be [ granted permissions for individual pages ].

### Product Permissions *(a piece type)*

Products: [ ] Select All / Remove All

[ ] Edit Any  [ X ] Create New [ X ] And Move to Trash

*Members of this group can create and edit their own products, but cannot edit others. If they can edit a product, they can also move it to the trash.

Members of this group can also be [ granted permissions for individual products ].

**Similar sections would follow for Images, Files, and other pieces.**

## NOTES

The top-level "Admin: All" permission will still be presented. 

The top-level "edit" permission will not be presented, unless already present in the project. Its current meaning is too confusing.

The top-level "guest" permission will be moved under PAGES and clearly labeled "View 'Login Required' Pages".

The top-level "upload/crop files" permission will be granted automatically if the user has *any* permissions for editing of pieces or pages. We can improve our garbage collection of unused attachments to ensure this is efficient. Users who only have guest permission will not be able to upload attachments by default but the developer can set a flag for this.

Help text will specify that if you create a page, you are granted edit/trash/move permissions for that specific page, so you can do common-sense things with what you created yourself.

In general help text should adapt to what you have picked so far. Try hard to explain what they get.

"Create New" and "Trash Any" imply "Move" privileges too, and the help will clarify this, possibly through displaying a checked "Move" box.

When a user clicks the "granted permissions for individual [x]" button, the page chooser opens, with multiple select and "select / deselect all children" capabilities.

Ideally the button language also updates to reflect whether the group already has some permissions for individual pages.

> NOTE: this complements, but does not replace, the interface for doing the same thing in "Page Settings." Sometimes you are thinking about it one way, sometimes the other. Granting permissions is often easiest in context, on a page. Revoking them en masse may be easiest at the group level.

Pieces have the same options as for pages. However there is no need to discuss "move" operations in the help, etc.

The "permissions may also be granted..." button will take you to a standard chooser for that type of piece, however only if this feature is enabled for the piece type (at first we had this for all piece types and devs and users found it to be too much, that's why it's a developer option to enable it).

Once again, a similar interface continues to exist in a permissions tab for the piece, when permissions for the piece are enabled at all.

**Comment by carlykaras** [comment]
@boutell I think we aligned on the "Select All" being a text link that toggles between "Select All" and "Remove All", rather than a checkbox.

**Comment by boutell** [comment]
Tagged 3.0 but also intended to be implementable in 2.0. In any case it would be inappropriate to ship 3.0 without these or equivalent considerations.

**Comment by carlykaras** [comment]
> @carlykaras if two out of three are checked, which state is appropriate for that text link?
> 
> I think the answer is "it's always 'select all' until everything is selected, and then and only then is it 'remove all.'"

Agreed!

**Comment by bgantick** [comment]
Thanks for capturing this @boutell - this all seems inline with the model we discussed.

**Comment by ECoursimaultM** [comment]
Hi @boutell, hi all,

Thanks for this initiative, we (at the Michelin team) have been long hoping for a more user-friendly way of managing user permissions. Just a quick question: how would apostrophe-workflow logics fit with this new permission admin system? I would like to make sure we easily split & secure permission levels not only across types of objects as this above description suggests, but also (and for us, probably more importantly) across locales. Beside, I think being able to easily disable the ability to export content across locales after commit would be helpful (based on our user survey, the "force export" thing that copy a piece of content from one locale to another is quite helpful, but the "export" dialog box that systematically pops up after each commit of each item turns out to be misunderstood, almost always skipped when not just mis-used).

Thanks in advance for sharing your thoughts on that! This being said, we will be happy to support and sponsor our part of this work as part of our Enterprise SLA (cc. @agilbert FYI)

**Comment by boutell** [comment]
Hi Etienne, thanks for chiming in on this and supporting the project under your Enterprise SLA!

Regarding locales and permissions, indeed this could be simplified as well.

I think there are two basic approaches:

(1) We essentially keep the current system, in which each named permission has a locale picker. But we associate just one such locale picker with each major type of content. That is, you would be able to check a few boxes to say "members of this group can edit product listings," and then also pick a few locales in which they can do so, also indicating whether they can commit or not or just edit the draft for each locale (just like now).

(2) We simplify the system. The simplification that occurs to me is that we could have a single locale permissions picker, in which you decide which locales this user or group can edit or commit in. Then, they must of course also have the permissions for the individual types of content.

The issue with this simpler interface is that it can implement the following user stories:

1. "Jane can only edit blog posts, and can only edit in French in any case."

2. "Sarah can edit in any language, and she can edit all types of content."

3. "Joseph can only edit blog posts and product listings, and he can only edit in French, English and German; and, in English, he can also commit (make content live)."

However, it can *not* implement this user story:

4. "Jane can only edit blog posts in French, and can only edit product listings in English."

It would be valuable to know whether this case feels important to your team. If not, we can significantly simplify the interface for locales and permissions, separating out the question of which locales you can edit from the question of which content types you can edit.

cc @carlykaras @stuartromanek

**Comment by boutell** [comment]
Re: the option to export that appears after every commit, we actually built a flag to optionally disable this for another client last year. 

"Do you export rarely? If so, you may want to set the `exportAfterCommit` option of the apostrophe-workflow module to `false`."

I will share more details on this elsewhere, but just in case others are looking for this feature.

**Comment by boutell** [comment]
@ECoursimaultM shared on a call that the simplified approach to locale permissions is fine, and user story number 4 should not come up in their case or similar operations. In the unlikely event of an edge case a separate account could be used.

**Comment by boutell** [comment]
We were also asked to provide a separate checkbox for moving pages around in the tree, as this can have far-reaching effects.

**Comment by boutell** [comment]
We're quite close on this. Here are a few problems that have come up:

1. The ability to "create, but not edit" pieces is problematic because so many pieces require contextual editing to be useful at all, and contextual editing is only possible *after* creation.
2. This statement is even more true for pages.
3. Control of *where* the user can create pages was not originally addressed in the new design.

Here is the plan to resolve this:

* "Create" permission will implicitly turn on "can edit documents that they created, or those for which they have been individually granted permission."
* In "Page Settings," the "Permissions" tab will have a new section after "Edit" for "Create Subpages."
* It will be possible to grant the ability to create subpages of a particular page without granting the ability to edit the page, and vice versa.
