### ISSUE TITLE
Pieces dissapear from modal when adding a "format" field to it.

### ISSUE THREAD

**Issue by JavierMtez-abarca** [apostrophecms/apostrophe#1787]
Good afternoon,

I was adding some fields to a piece and one of then is named "format". After that the modal to manage the piece stopped showing them. I'm able to add new ones but those won't be shown either. 

By deleting the "format" field or by changing it's name the problem seems to be solved. 

Is this a bug or is "format" a reserved word?

Thanks

**Comment by boutell** [comment]
I can confirm this. Not sure why yet, but it does disappear from the list view, and reappear if you remove the field.

**Comment by boutell** [comment]
The `format` query parameter is used by the list view, but the list view also passes `req.query` to `queryToFilters`. Adding a new string field automatically makes a query filter available for it, and... womp, womp. 

Simplest fix is probably for the list view to use something like `__format`.

**Comment by boutell** [comment]
A fix for this is in #1789, so closing that issue in favor of that PR; you can follow that if you're interested in when this will be released.
