### ISSUE TITLE
minSize not working in apostrophe-images

### ISSUE THREAD

**Issue by mtthwmnc** [apostrophecms/apostrophe#1810]
```
"apostrophe": "^2.79.0",
```

Image manager is bringing up images that do not meet the required `minSize`. Allows you to save the field and it renders an empty singleton.

**Comment by boutell** [comment]
To be precise, it blocks me from uploading a too-small image, but it still lets me pick one that's already present. So it's not a complete failure to pass on the hints to the chooser. Hmm.

**Comment by boutell** [comment]
See #1814
