### ISSUE TITLE
Is there any way to add a new route to point homepage?

### ISSUE THREAD

**Issue by popeyeaj** [apostrophecms/apostrophe#1820]
I just want to add a new route  like (/web) to point to homepage.

And then both 

_http://localhost:3000_
and
_http://localhost:3000/web_

point to the homepage.

**Comment by stuartromanek** [comment]
Here is some documentation on how routing works in Apostrophe
https://apostrophecms.org/docs/technical-overviews/how-apostrophe-handles-requests.html#express-routes

From some project-level module's `construct` method you can add a route directly by writing
```
self.apos.app.get('/web', function(req, res) {
    // maybe something special;
    return res.redirect('/');
})
```

You can also add a UI component for handling redirects by installing `apostrophe-redirects` and pointing your paths back to `/` 

https://github.com/apostrophecms/apostrophe-redirects

Also, StackOverflow and Discord are a better place for these sorts of future questions
https://stackoverflow.com/questions/tagged/apostrophe-cms
http://chat.apostrophecms.org
