### ISSUE TITLE
minsize not showing up in image chooser

### ISSUE THREAD

**Issue by mtthwmnc** [apostrophecms/apostrophe#1832]
Works as expected in `2.76.0`

![2 76 0](https://user-images.githubusercontent.com/7018825/54544096-43435c00-4975-11e9-967e-6cef32c9590b.png)

not working for `2.83.1`
![2 83 1](https://user-images.githubusercontent.com/7018825/54544097-43435c00-4975-11e9-9575-5c34f02455e7.png)

**Comment by boutell** [comment]
Closing in favor of https://github.com/apostrophecms/apostrophe/pull/1836
