### ISSUE TITLE
Admins need a way to be notified when documents are submitted, committed, etc.

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1839]
`apos.notify` is a great feature but currently it is generally giving you information about your own actions. There is a need also to communicate about what others have done.

In particular, we've been asked to quickly find a simple way to notify appropriate people when a document is submitted or committed.

Here is a possible approach that I think has long term value.

See the attached napkin sketches, they should help before you look at this wall of text 

(:

![IMG_20190320_145055498](https://user-images.githubusercontent.com/32125/54711342-15e6e180-4b20-11e9-97a3-a1a4a1ef523b.jpg)
![IMG_20190320_145107838](https://user-images.githubusercontent.com/32125/54711343-15e6e180-4b20-11e9-8e8b-bf80d3c774d7.jpg)

* `apos.notify` calls would get a new option, `category`. Notification categories are registered by modules that need them when Apostrophe starts up and would be simple strings, like `commit` and `export`. You would be able to register a nice label at the same time.
* When editing an Apostrophe group, there would be a new "Notifications" tab.
* In the Notifications tab, there would be a boolean for each category of notification, to indicate whether members of that group should get notified when a notification goes out in that category.
* If the notification is workflow-related, there's a multiple-choice locale picker for it, too. This way you are not bothered about locales that don't relate to you.
* Since notifications with a category would reach multiple people, only server-side code would be able to send one. That ensures we don't ever face a situation where a guest user can send inappropriate floods of notifications to other people (mostly a concern for sites with guest users, but we want to plan ahead).

This seems like a nice interface and requires no new UI code for the admin side.

As for the frontend interface for receiving notifications, for the very first MVP it could be almost just the way it is now. However we would need to add the username of the sender, so the receiver understands it is from someone else, plus a link to go to the document in question.

In the next iteration we would probably want to think more about whether we have the right interface for situations where a ton of notifications have piled up. We might at least want a "clear all" button and perhaps a way to collapse all notifications not based on your own actions to a "notification counter" in a corner until you're ready to deal with them.

What do you think @stuartromanek and @carlykaras?

**Comment by boutell** [comment]
Stuart points out that we'll want to be able to choose which piece types to get notifications about as well as which locales. And it's important that the implementation not send 500 notifications if someone does a batch commit, via the pieces manager or the "modified documents" view. 

Then again, I'm not sure it meets the need if not every committed document is called to someone's attention.

**Comment by carlykaras** [comment]
Reiterating offline conversations - for an MVP I think what you and Stuart have talked through makes sense, and we have ideas for future iterations.

**Comment by boutell** [comment]
A fancy example of a notify call might now be:

```javascript
apos.notify(req, '%s has been committed.', req.data.page.title, {
  doc: req.data.page,
  action: 'commit',
  type: 'success'
});
```

Notable points and technical implementation notes follow:

* Passing the doc concerned is a good future-proof way to capture locale, document type and whatever might be considered relevant later.
* We could however have options for those individual things in situations where loading the entire doc isn't already necessary and would be overhead.
* This makes it straightforward to map these to groups based on which doc types, locales, pieces and actions the group is interested in receiving notifications about.
* To keep the configuration from becoming too complicated, this will be a simple "AND" check. The notification must be for a type, a locale AND an action that interests at least one of the groups you're a member of.
* Being a member of two interested groups should NOT send you two notifications.
* Notifications with the same sending user, action, type and locale should "fold together." You don't get 500 notifications for a batch commit. Instead the first one pending for you gets annotated with a flag indicating how many similar notifications would have been sent.
* If a batch commit is in progress, there is still a race condition that can occur. User A clicks batch commit, and user B is watching. They see a notification, which soon has an annotation indicting 50 similar actions were taken so far. They click, clearing it. A new one appears, ticks up to 50... et cetera.
* This should be resolved by adding `apos.notifications.pause()` and `apos.notifications.resume()` methods, and the batch operation logic should wrap these around each batch operation.
* It is probably enough for the folding mechanism to kick in only on `apos.notifications.resume()`, which simplifies that logic because we don't have to check the database, only the in-memory queue of paused notifications. We do the folding there and then pop them into the database as normal.
* A minor related enhancement that should be made: currently you have to explicitly `await` apos.notify if you call it in a command line task and you are concerned that the task will exit before the notification reaches the database. Instead, pending apos.notify calls should be tracked by the notifications module and on an apos.destroy call, they should all flush before the database connection is closed.

**Comment by boutell** [comment]
We implemented apostrophe-external-notifications.
