### ISSUE TITLE
Auto-dismiss save notification

### ISSUE THREAD

**Issue by scottbuscemi** [apostrophecms/apostrophe#1845]
**Is your feature request related to a problem you are experiencing that is not a bug? Please describe.**
After saving a page or piece, a notification appears to let the admin know: "The page has been created and saved." However, this notification never goes away. Editing multiple pages/pieces results in these notifications stacking up and filling the screen.

**Describe the solution you'd like**
Auto-dismiss after a few seconds.

**Comment by boutell** [comment]
The notifications go away when you click on them, they don't stack up forever.

We should use the auto-dismiss option for more of them, though. These sound like good examples of that so I'll keep the ticket open with these particular cases in mind. (Some notifications already auto-dismiss after a few seconds.)

**Comment by boutell** [comment]
Fixed in commit c431756, will be published with the next release of apostrophe-workflow. Also there is a PR to add an obvious UI for closing notifications.
