### ISSUE TITLE
arrangeFields warning shows up for all pieces

### ISSUE THREAD

**Issue by fredrikekelund** [apostrophecms/apostrophe#1859]
**To Reproduce**
1. Install `apostrophe@2.85.0`
2. Configure a module that extends `apostrophe-pieces`
3. Start the app
4. See warning `doc type X contains ungrouped field(s):` for every field on that piece

**Describe the bug**
This seems like quite a noisy warning if it's generated for every piece by default. It seems to be happening because pieces always come with a baseline `arrangeFields` config simply by extending `apostrophe-pieces`. 

I do understand the reasoning that the "Info" label is a bit cryptic for end users, but given that it's not required to use the `arrangeFields` feature, I'm wondering if it's really necessary to produce so many warnings about this?

Just as a reference, this change seems to have been introduced here: aedee2dda36b915e1dfbb31fb54bf9fa50d8d541

**Comment by boutell** [comment]
It is not required but it is a best practice and we are trying to encourage
good ux. I take your point about it happening for piece types you have not
tried to arrange at all. That could be too much
