### ISSUE TITLE
Error message should have close button to dismiss the message

### ISSUE THREAD

**Issue by ofattouh** [apostrophecms/apostrophe#1870]
- Apostrophe modal error messages currently doesn't have a close button to let the back end users dismiss these errors and it will never go away unless you reload the page

- Currently the only way to dismiss/acknowledge this error message is to click on the message itself but how will the back end user know that ? 

- Please add a close button to allow the back end user to dismiss this error message

- This is a sample override code to change the error messages in custom coded module/piece:

```
// Inside lib/modules/apostrophe-users/public/js/editor-modal.js
apos.define('apostrophe-users-editor-modal', {

  extend: 'apostrophe-pieces-editor-modal',

  construct: (self, options) => {
    self.getErrorMessage = function (err) {
      if (err === 'unique') {
        return 'Please make sure the username and email address fields are unique.';
      } else if (err === 'Invalid Password') {
        return 'Invalid Password!';
      } else if (err === 'Invalid Administrator Password') {
        return 'Invalid Administrator Password!';
      }
      else {
        return 'An error occurred. Please try again.';
      }
    };
  }
});
```

**Comment by bobclewell** [comment]
updated the comment for code formatting

**Comment by ofattouh** [comment]
- Is this fix is now pushed to Apostrophe repository ? 

- If not then please let me when will it be available so I can update the Apostrophe version in package.json ? Thanks

**Comment by boutell** [comment]
Hi Omar, I understand you'd like to see a UX change here and we see your point! Please be patient and we'll get to it when we are able.

If you have a particular need you'd like to see prioritized quicker consider signing up for enterprise support:

https://apostrophecms.org/support/enterprise-support

Thanks!

**Comment by ofattouh** [comment]
Hi Boutell,

- I understand and it can wait 

- Thank you so much for all the hard work

**Comment by boutell** [comment]
Closing in favor of the PR in #2004 which you can follow for progress toward release.
