### ISSUE TITLE
svgImages: true not working with apostrophe-images

### ISSUE THREAD

**Issue by MorochoRochaDarwin** [apostrophecms/apostrophe#1881]
I have implemented the apostrophe-images widget in my page like this

```
{{ apos.singleton(data.page,'logo', 'apostrophe-images', {
      limit: 1,
      svgImages: true,
      extensions: ['png','gif','jpg','jpeg','svg']
      }) 
}}
```
I want to upload svg files but it doesn't work.

I followed https://docs.apostrophecms.org/apostrophe/modules/apostrophe-attachments#svgimages

Is posible upload svg files with apostrophe-images?

**Comment by boutell** [comment]
You pass this option to the apostrophe-attachments module, for instance in
app.js. Not to an individual area or singleton. Then svg becomes available
as an attachment extension and thus available for images and images-widgets.
