### ISSUE TITLE
Contextual edditing pieces

### ISSUE THREAD

**Issue by kalidis** [apostrophecms/apostrophe#1883]
Having two pieces pieceA and pieceB. PieceA has a joinByArray to pieceB. In the pieces-page of pieceA if you show all the information of both pieces, but pieceB can't be eddited from this page, and if you add **edit: false** to the apos.singleton, the tool bar of the rich text doens't appear, but it stills appear the box that indicates you that you can edit and even you can change the text, but when you refresh the page, the text is still the original one.

**Comment by abea** [comment]
Thanks, @kalidis.

More context in this SO thread: https://stackoverflow.com/q/55627043/888550
