### ISSUE TITLE
Maybe should check if there is `extends` instead of `extend` property on modules

### ISSUE THREAD

**Issue by umutozdemir97** [apostrophecms/apostrophe#1906]
This is not related to a bug. This idea might help to find out if developer used the property `extends` instead of `extend`. And it might lead the developer to search for the errors at different lines and files. 

I would like apostrophe to check if `extends` property of module is truthy or Moog might use `extends` as a fallback for `extend`.

Or maybe, there might be an ESLint rule about this, optionally installed on ApostropheCMS projects.

**Comment by boutell** [comment]
This is implemented in 2.90.0. It's a warning, since it's not a bug to use extends for something else (but it's certainly confusing).
