### ISSUE TITLE
apos.utils.post should support FormData

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1943]
Right now you can't use FormData and get our CSRF protection without duplicating our code. It should be straightforward for apos.utils.posts to recognize a FormData object and make the following changes:

* Don't try to set the content type of the request.
* Don't try to JSON.stringify the `data` parameter.

Then XMLHttpRequest will just do the right thing, most notably in IE11.

There are other ways to submit file uploads via AJAX but they tend to have unnecessary overhead (base64 encoding, for instance) and require more code to work back to IE11 than this simple "don't fight it, go with it" FormData approach.

**Comment by abea** [comment]
Closed by #1944 ?
