### ISSUE TITLE
The name option to pieces modules, etc. generates confusion, is not needed for uniqueness

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#1948]
`apostrophe-pieces` requires a `name` option.

This is unnecessary. It is used to populate the `type` property, and in various CSS contexts, but at bottom this was done purely for grammatical reasons and it's not worth the candle because developers are frequently confused by:

(1) the need to set it at all;
(2) our convention of making it singular (because it's the "type" of an "individual piece," but who cares);
(3) the fact that it's not identical to the module name;
(4) the fact that you have to pass `name` to `docs.getManager`.

For easy forward compatibility fo 2.x code, I think `name` should continue to be supported. But in 3.x, it should just default to the module name and not be a mandatory extra thing to worry about when creating a piece type.

At one point we thought this would generate conflicts between, let's say, articles and article index pages, but in fact it doesn't:

```
{ type: 'articles' } // same as module name
```

```
{ type: 'articles-pages' } // same as module name
```

Looks distinct to me!

**Comment by abea** [comment]
✅
