### ISSUE TITLE
Request does not contemplate HTTPS protocol

### ISSUE THREAD

**Issue by Jose96GIT** [apostrophecms/apostrophe#1959]
I've prove the connection to my Apostrophe page using HTTPS protocol instead of HTTP protocol and in the **req** object, the protocol property value is HTTP so that it doesn't detect correctly the protocol.

Futhermore, the absoluteUrl, baseUrl and baseUrlWithPrefix also have "http://..." instead of "https://...".

**Comment by abea** [comment]
Your `baseUrl` property doesn't use `http://`, does it?

**Comment by Jose96GIT** [comment]
I didn't have any baseUrl configured in the project and that was my problem. Thanks for your help!
