### ISSUE TITLE
Update content before sending to client/ rendering it.

### ISSUE THREAD

**Issue by vincentrohde** [apostrophecms/apostrophe#1964]
Is there a way to hook into the moment before the content is rendered for/ send to the client, and then update it?

Let me give you an example:
I want to delete all Widgets from type A, if the user disabled them in the past, but only if there are enough Widgets from type B, etc. The logic will get to complex for simple templates eventually.

I am fairly new to the Apostrophe CMS and would like to know if it is possible to update the content response(in such a way as described above) before it is rendered.

**Comment by abea** [comment]
Check out the promise events documentation. The apos-pages `beforeSend` event might be what you need. This would happen in the custom-pages or pieces-pages index.js file. https://docs.apostrophecms.org/apostrophe/other/events#apostrophe-pages-beforesend-req
