### ISSUE TITLE
Empy "Info" tab after all fields are arranged

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#1991]
**To Reproduce**
1. Run the apostrophe-open-museum site as of the branch https://github.com/apostrophecms/apostrophe-open-museum/tree/hotfix/arrange-all.
2. Click through the admin menu to create or edit an "Artist" piece.
3. Check the "Info" tab.

**Expected behavior**
The tab should not exist since no fields are there.

**Describe the bug**
The tab exists, but has no fields inside.

**Version of Node.js**
8.x

**Comment by boutell** [comment]
Closing in favor of PR in... womp... wooomp... WOMMMP.... #2001 (ta-daaaaa)
