### ISSUE TITLE
Apostrophe does not saves content of layout widgets

### ISSUE THREAD

**Issue by KaMeHb-UA** [apostrophecms/apostrophe#1999]
Apostrophe version: 2.95.0, Nunjucks version: 2.5.3

**To Reproduce**
1. Create new layout widget like described [here](https://docs.apostrophecms.org/apostrophe/tutorials/getting-started/layout-widgets). ([Full widget code](https://gist.github.com/KaMeHb-UA/2eac2702b464a2061268bb66c09430fa))
1. Add this widget to the page on your site
1. Add a widget (text or image) in column and fill it
1. Wait for a while
1. Refresh the page
1. Expect to see content saved

**Expected behavior**
Column content saves successfully

**Describe the bug**
Column content does not saves

**Version of Node.js**
12.6.0

**Server Operating System**
Ubuntu 19.04 with dockerized Alpine

**Screenshots**
![](https://gist.githubusercontent.com/KaMeHb-UA/2eac2702b464a2061268bb66c09430fa/raw/82e3c4ac6868867893a14181dc709408943ec90c/screen.png)

**Additional context**
I used Array.prototype because found no info about how to use my own functions in templates correctly. Sorry about that

**Comment by boutell** [comment]
This doesn't necessarily resolve your bug, but we now have a proper tutorial on adding nunjucks helper functions from your code:

https://docs.apostrophecms.org/apostrophe/tutorials/getting-started/nunjucks-helper-functions

That will help you get rid of all those Array.prototype hacks.

**Comment by boutell** [comment]
Please address the Array.prototype hacks using the nunjucks helper functions method linked above, and retest with version 2.95.1. (You might even find the bug is gone with 2.95.1 without having to do any refactoring first, so feel free to check that first.) I have reason to believe the fix in 2.95.1 is relevant. Thanks!

**Comment by boutell** [comment]
2.96.1 contains additional relevant fixes. Please retest! Thank you.

**Comment by boutell** [comment]
Closing due to lack of response but feel free to reopen if not fixed by latest apostrophe.
