### ISSUE TITLE
Error when publishing pieces page

### ISSUE THREAD

**Issue by kmanaseryan** [apostrophecms/apostrophe#2000]
When publishing a piece through publish menu it gives error. Even though the article is being published.
![image](https://user-images.githubusercontent.com/3371013/64062948-c17f7c00-cbfe-11e9-99fe-c2985d9645a0.png)

Error log is:
```
POST /modules/articles/publish: 

Error: Error is not a string or an instance of Error, maybe this is not an error and you forgot to
pass null as the first argument to next()?
```

I found that it comes from this line:
https://github.com/apostrophecms/apostrophe/blob/fcf7ada3e962b0b19543e7f0aa03fa362a0ce148/lib/modules/apostrophe-jobs/lib/api.js#L103

In `apiResponder(req, err, result, extraError)` function the second argument is `err`, however in the code above it is being passed the result. As a solution the second argument should be `null` indicating there is no error so that the argument: 
```
{
          // legacy
          data: single || {},
          // preferred
          results: results
        }
``` 
will be the third one.

**Comment by boutell** [comment]
Closing this in favor of #2002, refer to the PR for progress toward release. Thanks for the report.
