### ISSUE TITLE
Replacing an image in a widget with a newly uploaded image does not save

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#2009]
**To Reproduce**
1. Create a widget that has an apostrophe-images singleton in it's schema
2. Populate the image
3. Reopen the Edit Widget modal and edit the apostrophe-images singleton
4. When in the media library with chooser, upload a NEW image and add it to the chooser
5. The apostrophe-images singleton preview should appear to correctly reflect the new choice
6. Save and see the image has reverted to the old image.

**Expected behavior**
Uploading a new image mid-widget edit and replacing an existing selection should save when all is closed up.

**Describe the bug**
Newly uploaded image does not save as the selection in your apostrophe-images singleton

**Screenshots**
Demo video here https://www.dropbox.com/s/vefj5hsh9r69fzg/apostrophe-new-image-bug.mov?dl=0

**Comment by boutell** [comment]
Closed by #2011
