### ISSUE TITLE
nunjuks is not a html file

### ISSUE THREAD

**Issue by souricevincent** [apostrophecms/apostrophe#2019]
**Is your feature request related to a problem you are experiencing that is not a bug? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]. If this is a bug report, open a bug report instead.
--> The template engine is Nunjuks, however, the files have the `.html` extension,

**Describe the solution you'd like**
--> I think we should be able to configure the extension for the project, example: `.njk` for the views. Then explain that you need to add a file type in the IDE parameters and point to the `.njk` extensions as twig files.

**Describe alternatives you've considered**
--> no

**Additional context**
--> no

**Comment by boutell** [comment]
Apostrophe supports either file extension automatically for nunjucks files.

**Comment by souricevincent** [comment]
thank's
