### ISSUE TITLE
Join autocomplete not working

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#2022]
PLEASE NOTE: make sure the bug exists in the latest patchlevel of your major version of Apostrophe. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that series to verify the bug.

**To Reproduce**
1. Create a join field to a piece type that has a few pieces already. Type in one of the existing piece titles into the autocomplete field.

**Expected behavior**
The matching piece (and maybe others) appears in a list below the field.

**Describe the bug**
Nothing happens at the moment. Clicking "Browse" still works as expected.

**Comment by boutell** [comment]
This is a z-index problem with jquery ui autocomplete. You can just barely see it peeking out from underneath the modal here:

<img width="643" alt="Screen Shot 2019-09-15 at 12 28 01 PM" src="https://user-images.githubusercontent.com/32125/64924583-531ceb00-d7b4-11e9-9333-78572ec7af1f.png">
