### ISSUE TITLE
InContext Editing Errors out after modal is closed.

### ISSUE THREAD

**Issue by bharath6365** [apostrophecms/apostrophe#2026]
**To Reproduce**
1. Go to Apostrophe Demo Site
2. Open the Feature Widget inside a modal and click save.
3. Try to edit the rich text editor in-context
4. It fails with a warning that is shown to the user.

More Information about the issue is mentioned here.
https://www.notion.so/InContext-editing-errors-out-after-modal-editor-is-saved-a27cc8f0c2cc47a9b2c4eecca9eb640d

Link to an attempted fix - https://github.com/apostrophecms/apostrophe/pull/2025

**Comment by boutell** [comment]
In a recent fix that greatly improved stability for area editing overall, we missed that this particular case needs to call a newer method. See my PR, it's a one line fix because the right function is already available. Thanks for reporting the issue!
