### ISSUE TITLE
sendPage invokes legacy pageBeforeSend as expected, but emits beforeSend event from wrong module

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#2056]
Unless you happen to be extending `apostrophe-pages`, the sendPage method emits `beforeSend` from the wrong module.

For instance, if your module is called `bridge`, then `self.sendPage(...)` will emit `bridge:beforeSend`.

This happens even though the legacy `pageBeforeSend` callAll method is invoked correctly.

This is no good: `beforeSend` could also be some completely unrelated event in your `bridge` module,  and the developer expects and needs various standard "I want to mess with `req.data` before anything goes out" situations to be covered by this event whether the page was a standard one or not. That's the point of `sendPage`, after all.

The fix is to invoke `callAllAndEmit` on `apostrophe-pages` rather than on `self`.

cc @stuartromanek who was bit by this recently.

**Comment by kingsleytorlowei** [comment]
Can i work on this?

**Comment by boutell** [comment]
This got fixed, but thank you for asking!
