### ISSUE TITLE
Blessing mechanism should impose no significant performance penalty, or be removed

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#2074]
Blessings are notations that a particular set of area options , a particular schema, etc. are real — they came from the site developer — and it's OK to re-render a widget or area or manipulate some data with them. 

They were introduced to avoid the hassle of validating these option sets and schemas and such when they come back from the browser to be re-rendered after various types of edits.

They solve real problems, but they have generated a lot of code and a lot of annoyance. They need to get cheaper, or be chucked if their cost is higher than the alternative.

I see two basic options here:

1. Chuck 'em, and introduce validation of everything. The proposition here is that if we can ensure the options are safe, then we don't care if they came from a template or not, because they can't crash the page due to the validation, and they won't really render later for site visitors with any options other than those in the templates. Developers have to write validators for widget options in this scenario, otherwise a malicious editor can crash the site. Oh well.

The problem with option one is that we don't just need to validate widget options, we also need to validate other things that rely on blessings, like schemas when editing a page. I am not convinced there's a great way to do that.

2. Find a better, lower impact way to store blessings than the current "session plus reinforcing mongo collection" approach. The reinforcing mongo collection is there due to the race conditions of relying on session storage. It works, but it's a lot.

A lower impact solution would be to take the blessing hash we're already computing, turn it into an [HMAC](https://en.wikipedia.org/wiki/HMAC) so it can't be faked, and include it in the widget in such a way that it will come back to us in the API calls that want to re-render the widget. Then we can just check the HMAC, and if it's valid, we don't need to maintain a list of blessings at all.

I favor option two because we don't just use blessings for widgets, and it's not clear that we can write validators for every situation in which blessings are useful.

I'd do option two today in 2.x, but unfortunately it would be a significant bc break to plumb passing the HMACs back to the browser and then up to the server reliably. So for 2.x the workaround is the reinforcing mongo collection with `$addToSet`.

cc @abea @stuartromanek

**Comment by abea** [comment]
I don't know HMAC from Adam, but that seems like a great path for 3.0. Simplified and secures.
