### ISSUE TITLE
Lean mode should support "apos.on" for the "ready" event because everyone stubs their toe on it

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#2094]
"apos.on" does not exist in lean mode. That makes sense. However everybody gets confused about how to attach their "enhance" or "ready" event handlers for non-widget code.

The right way to do that is:

```javascript
if (!apos.on) {
  // safely after DOM is ready, like $(function() { ... })
  apos.utils.ready(invokeMyThing);
} else {
  // safely after DOM is ready AND when new widgets are ajaxed into the page while editing
  apos.on('enhance', invokeMyThing);
}
```

But this pattern is really tedious and everyone is having a tough time with it, which is breaking code on the front end.

So I propose it is worth a few bytes to support `apos.on` in the lean library, and to just have `ready` and `enhance` fire at `apos.utils.ready` time in lean mode, so code works either way. A few of the "if" statements above and you'll actually have more code bloat than this simple pokeyoke to prevent bugs.

**Comment by abea** [comment]
I'm not sure this is any more tedious than our method for invoking similar code now. It seems that specific documentation of this pattern would also resolve the issue.

**Comment by stuartromanek** [comment]
If lean mode had more definition around it would be easier to make these decisions.

If lean mode just means no external dependencies then I don't feel bad about filling in normal front-end `apos` functionality to keep code consistent and One Way.

The documentation for lean should be beefed up by adding a section around running non-widget code. Lean mode might also benefit from not just throwing everything into `apos.utils`, where we're currently mixing jquery-like helpers with apostrophe specific ready code.

**Comment by boutell** [comment]
Re: the API design, in 2.x we can't introduce bc breaks, but we could do some refactoring such that the apos.utils.* versions are still available as bc wrappers.

I do think it means "no external dependencies," but also staying fairly close to a credible claim that it's, well, lean... so additions like this should be discussed and justified but I think this is a very worthwhile one.

**Comment by abea** [comment]
Either way, clearer documentation should be part of this update. CC @localghost443

**Comment by boutell** [comment]
On reflection, I think A3 is a good time to review the factoring of lean frontend APIs, rather than putting bc wrappers in lean, because that... is... awfully bloaty ("welcome to the lean and mean frontend library! Here's some extra code you are stuck with because blah blah inside baseball").

In A3 I imagine we'll drop anything currently in apos.utils that is not needed for IE11 support.

**Comment by boutell** [comment]
Sorry, that comment was confusing. I'm saying that moving things like "apos.utils.closest" to another module in 2.x would be premature. I still think supporting "apos.on" makes sense for the original reasons stated above.

**Comment by boutell** [comment]
My concern isn't tedium, it's the bug-prone nature of saying "you have to write this if statement to deal with the two cases, and you have to write it in many places." That's a clear tell that we should provide a simple way to work in both situations.
