### ISSUE TITLE
Re-saving layout widget is causing an error

### ISSUE THREAD

**Issue by puntnomads** [apostrophecms/apostrophe#2098]
[apostrophe-samples](https://github.com/apostrophecms/apostrophe-samples) demonstrates column widgets like one-column-widgets, two-column-widgets and three-column-widgets. To have less widgets and be more dynamic, I thought a columns widget in which the user specifies the number of columns would be better. I have created that widget. After the columns are created, I can edit the number of columns to be different when there are no widgets on any column. However, if a widget is added to any column and then I try to save the column widget again leads to an error. How can I fix this error? 

The ideal scenario, for example, would be to create a 5 column widget, add an image widget to column 1 and then edit the column widget to be 3 columns with the image widget in column 1 still being persisted.

Replication Steps:  

1. Log into [CodeSandbox Example](https://rl4ox.sse.codesandbox.io), username is "user" and password is "user".  
2. Open edit modal for existing column widget.  
3. Save the column widget without any changes.  
4. See error in developer console.

**Comment by abea** [comment]
So far I don't see indication that this is a bug in core given the custom nature of this widget. On the face of it I'd think it's related to the tab with 12 areas that don't seem to have widget configurations. But it would be more helpful to see the code for this widget to know for sure. Can you share that?

**Comment by puntnomads** [comment]
The code is [here](https://codesandbox.io/s/apostrophe-columns-example-rl4ox)

**Comment by abea** [comment]
Yes, this is because the area options are not set in the schema. You can cut down on duplication putting the options in a variable in `index.js`, then can even reference that [like it's done here in the open-museum demo project](https://github.com/apostrophecms/apostrophe-open-museum/blob/master/lib/modules/two-panel-widgets/views/widget.html#L6). But I'm pretty sure that widget area options need to be defined in the schema.

**Comment by puntnomads** [comment]
That has solved my issue. Thank you very much for your help @abea. Much appreciated.
