### ISSUE TITLE
Step 3 of the Creating your first project throws an error

### ISSUE THREAD

**Issue by mayhemds** [apostrophecms/apostrophe#2120]
Following the Creating your first project steps. The last step causes an error once is run in the terminal

```
 cd test-project
 # Install our dependencies (most notably, Apostrophe)
 npm install
 # Add an admin user to the admin group; prompts for password
 node app.js apostrophe-users:add admin admin
 # Go go go!
 node app.js
```
Once the commands have run, the following issue happens

```
(node:10496) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:10496) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
_stream_readable.js:1157
      return this.pipes.length;
                        ^

TypeError: Cannot read property 'length' of undefined
    at Cursor.get (_stream_readable.js:1157:25)
```

**Comment by boutell** [comment]
Thanks. What version of node, on what operating system?

node --version

**Comment by mayhemds** [comment]
Hi, 
I'm using version v13.6.0

**Comment by boutell** [comment]
This is an issue using apostrophe in node 13, which is not recommended for production use:

"Node.js 13 is the next current release. Although it won’t be promoted to LTS and we don’t recommend its use in production, it’s still a good idea to test your applications and build your packages on this version periodically. Doing so ensures that you can experiment with the latest features — and when version 14 comes our, there will be less for you to catch up on in terms of what’s new."

However we will of course be fixing it, you should be able to use apostrophe with any currently supported release of node, apart perhaps from exceptionally bad node bugs, and we don't know that this is a node bug yet; probably more of a bc break in node 13, but we haven't yet figured that out.

In the meantime, it's recommended that you use node 12, the current production supported release of node.

**Comment by boutell** [comment]
After an "npm update," or in a new project, this problem should now go away; we released `emulate-mongo-2-driver` version 1.0.4 to work around an oddity in node 13 with mongodb collection objects.

**Comment by boutell** [comment]
(Thanks for the report!)

**Comment by mayhemds** [comment]
No problem. Thanks
