### ISSUE TITLE
`requireEditor` should return `401 Unauthorized` or `403 Forbidden` on error instated of `200 Ok`

### ISSUE THREAD

**Issue by tiphedor** [apostrophecms/apostrophe#2123]
**To Reproduce**

```javascript
// in a piece, for example
self.route('post', 'sample-route', self.requireEditor, (req, res) => {
  // ... do stuff
  return res.status(200).json({ok: true})
})
```

**Expected behavior**

 - For logged-in users: the request should return 200 OK, with body: `{ ok: true }`
 - For non logged-in users: the request should return 401 Unauthorized / 403 forbidden  with body: ` { status: 'forbidden'}` 

**Describe the bug**

 - ✅ For logged-in users: the request returns 200 OK, with body: `{ ok: true }`
 - ❌ For non logged-in users: the request returns 200 OK with body ` { status: 'forbidden'} `

**Version of Node.js**
N/A

**Server Operating System**
N/A

**Screenshots**
N/A

**Additional context**

Relevant pieces of code : 

 - https://github.com/apostrophecms/apostrophe/blob/c71d1790d110ba364301b053e7a4a248aecbe632/lib/modules/apostrophe-pieces/lib/api.js#L120
 - https://github.com/apostrophecms/apostrophe/blob/c71d1790d110ba364301b053e7a4a248aecbe632/lib/modules/apostrophe-pieces/lib/api.js#L539

**Comment by boutell** [comment]
This would be a bc break in 2.x, which uses the following UI convention: you get back 200 OK (absent a hard error on the server), with a `status` property which will be `ok` if all is well, and something else if not. We can't just change that as it would impact existing client code.

However in 3.x we are following REST conventions, including the use of appropriate status codes. So your concern will be resolved in that release.
