### ISSUE TITLE
Scrolling on the Manage Images modal does not work consistantly.

### ISSUE THREAD

**Issue by bobclewell** [apostrophecms/apostrophe#2130]
Apos v 2.101.0

**To Reproduce**
1. Go to the images modal with multiple pages of images (I have 200+)
2. Try to scroll
3. It only goes a small part of the way down. There are still images to see below that I can't get to.
4. Keep fiddling with the cursor and the window and eventually it works

**Expected behavior**
If there are images below to scroll to you should be able to scroll down without hesitation.

**Describe the bug**
Scrolling is stuck.

**Version of Node.js**
v12.13.1

**Browsers (only browsers tested - it might happen in others)**
Firefox 72.0.1
Chrome 79.0.3945.117 (Official Build) (64-bit)

**Screenshots**
See the video below. (I can also send you the .MOV file)
![ScreenRecording2020-01-21at92717](https://user-images.githubusercontent.com/116818/72813891-1feeda80-3c32-11ea-99d6-7fdbacb1dbe6.gif)

**Additional context**
This doesn't happen every time and it eventually gets unstuck. It's not clear to me the state of the cursor or the window to cause this, but it is happening pretty consistently to me.

**Comment by boutell** [comment]
@stuartromanek can you shed any light on this?

**Comment by bobclewell** [comment]
One additional detail: It doesn't just get stuck scrolling down. Sometimes if I'm at the bottom of the list I can't scroll back up.

**Comment by hexitex** [comment]
I added this to my site.css which seems to have fixed it.
.apos-manage-grid-view {
  
    overflow:hidden !important;
}

**Comment by abea** [comment]
This seems related to the addition of the CSS Grid styles via the feature query. I'll push a PR to override in that case. It seems the overflow rules is unnecessary in any case, but without confirmation I'll take the road of least impact.
