### ISSUE TITLE
Widget Edit Menu - Last field group flows out of modal

### ISSUE THREAD

**Issue by arthurnagyy** [apostrophecms/apostrophe#2147]
**To Reproduce**
1. Create a widget.
2. Add multiple field groups so that a scroll bar comes up. (around 15-16 // 1920x1080)
3. Scroll down. You will notice that you can't see the end of the scroll bar and you'll have a tiny space available to select the last group (text not visible at all).

**Expected behavior**
Be able to add as many groups as you want without the last group flowing out of the modal.

**Describe the bug**
After adding enough field groups for a scroll bar to show up and scrolling down to the bottom, you will notice that the last group is barely visible.

**Screenshots**
https://i.gyazo.com/6274bfeefd0703f24c1387854ac671e4.mp4

**Additional context**
While inspecting the elements I've noticed the following:
The `div` with the class of `apos-schema-tabs` has a inline style added to it `height: calc(-144px + 100vh);` (in my case). I could only assume that there's some JavaScript calculations to determine the size it should be. If I were to manually change it to `height: calc(-185px + 100vh);` then the issue would be resolved, but I assume that number isn't valid depending on screen sizes.

**Comment by boutell** [comment]
@stuartromanek can you peep this one?

**Comment by stuartromanek** [comment]
This was due to the fact we weren't taking into consideration the modal position offset when calculating the fillable height. @arthurnagyy @boutell I have a PR for this over here https://github.com/apostrophecms/apostrophe/pull/2149
