### ISSUE TITLE
apos.utils.get adds an extra "?" even when the query string is empty

### ISSUE THREAD

**Issue by jogarijo** [apostrophecms/apostrophe#2156]
**Is your feature request related to a problem you are experiencing that is not a bug? Please describe.**

In a project I'm working on, we expose GET routes that expect complex query string that make use of the nested object syntax. For example, I can end up with URLs that look like `/somewhere?some[data]=1`.

As I'm working in lean mode, I'd like to use the `apos.utils.get` method to make the request from a client script; however, looking into Apostrophe source code, it's clearly stated in a comment that nested properties are not supported in the query string. So in order to make it work, I'm currently building the query string myself and injecting it in the `uri` parameter, something like this:

```js
apos.utils.get('/somewhere?' + toQueryString(data), {}, callback)
```

However, the way `apos.utils.get` is implemented always adds an extra question mark `?` at the end of the URI, even if the query string is empty; in my case, it's thus modifying the value of the last property of the query string (e.g. `GET /somewhere?some[data]=1?` → `some.data === '1?'`).

**Describe the solution you'd like**
I don't think nested properties in query string should be supported by default, as it requires a middleware on server-side to parse them anyway. The minimal solution I'd advocate for would be to detect if the `data` object is empty, and then not add the extra `?` at the end of the `uri`. We could even pass `null` or `undefined` for this purpose, to make it explicit that we do not intend for a query string to be added at all.

This solution would keep the previous, simple behavior, while still allowing to create custom query strings for complex cases when needed.

**Describe alternatives you've considered**
Another solution would be to let the user provide a transformation function to convert the input data to a query string. It could be an additional optional parameter for example.

In my use case, I'm using the [`qs` package](https://www.npmjs.com/package/qs), which exposes a `stringify` method. Thus could the code look like:

```js
apos.utils.get('/somewhere', data, qs.stringify, callback)
```

I personally find this solution more elegant, and it aligns quite well with the API of other libraries like Lodash or JSON.stringify and such.

**Comment by boutell** [comment]
Thanks, we're solving this with a simple PR to not add the ? if data is null or not an object or if data has no properties. Allowing an encoding function strikes me as overkill because I would expect developers to just build their own URL if they need more.

**Comment by jogarijo** [comment]
I do agree, even more so that in my use case, there is additional logic around it so I already have a wrapper that can take care of such things.
