### ISSUE TITLE
Possible security related bug

### ISSUE THREAD

**Issue by bugbreaka** [apostrophecms/apostrophe#2183]
Hi,

I may have found something that affects the framework security.

Could you advice how to inform the project about the findings?

I'm not too familiar with GitHub, but here are a couple of articles which may help:

* [https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository)
* [https://help.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories](https://help.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories)

**Comment by abea** [comment]
Please email security@apostrophecms.com. Thanks, @bugbreaka. I need to get that added to a `SECURITY.md` file.

**Comment by bugbreaka** [comment]
Fixed in [https://github.com/apostrophecms/apostrophe/releases/tag/2.106.0](https://github.com/apostrophecms/apostrophe/releases/tag/2.106.0)
