### ISSUE TITLE
2.106.0 Breaks apostrophe-images

### ISSUE THREAD

**Issue by thesim333** [apostrophecms/apostrophe#2185]
After updating to 2.106.0 apostrophe-images view is no longer showing thumbnails.

## To Reproduce
Open the images chooser from the top bar or from a widget.
The widget is better as it shows the image actually exists in the edit sidebar

2.105.2 works
2.106.0 shows rows of ?

## Describe the bug
The apostrophe-images manageGridPage thumbnail images are showing the missing attachment image and console warning.

"Template warning: Impossible to retrieve the attachment url since it is missing, a default icon has been set. Please fix this ASAP!"

The images appear to work everywhere else as expected.

## Details

**Version of Node.js:**
10.20.0 and 12.16.2

**Server Operating System:**
Ubuntu 18.04

**Comment by boutell** [comment]
Thanks. PR is under review.

**Comment by boutell** [comment]
While you're waiting for the PR, there is an easy workaround:

```
// in app.js, in the modules list...
modules: {
  'apostrophe-images': {
    addToListProjection: {
      attachment: 1
    }
  }
}
```

**Comment by boutell** [comment]
Fix released, thanks again for the report.
