### ISSUE TITLE
"startBody" block in `outerLayoutBase.html`

### ISSUE THREAD

**Issue by arthurnagyy** [apostrophecms/apostrophe#2195]
## The problem to solve

Currently there is no _easy_ way to add something right after the `<body>` is opened.

## Proposed solution

Add an empty block in `outerLayoutBase.html` called `startBody` above the `apostropheMenu` block.

## Alternatives

The easiest way I found to deal with this is to overwrite `outerLayoutBase.html` just to add that block.

## Additional context

Currently in the `<head>` we have this exact thing, a block called `startHead` for situations where you need to add something right in the beginning of the `<head>`.

**Comment by abea** [comment]
@arthurnagyy There is a template `prepended` hook right after `body` opens. `apostrophe-templates` has the [`prepend` and `append` methods](https://docs.apostrophecms.org/reference/modules/apostrophe-templates.html#prepend-location-helperfn) to add things at the beginning and end of the head, body, context menu (bottom left) and the main `apos-refreshable` wrapper.

Here's an example of that in action, in an module called `my-alert`

```js
// lib/modules/my-alert/index.js
module.exports = {
  extend: 'apostrophe-module',
  construct: (self, options) => {
    self.prependAlert = () => {
      self.apos.templates.prepend('body', (req) => {
        return self.partial('alert', {});
      });
    };
  },
  afterConstruct: (self) => {
    self.prependAlert();
  }
};
```

This is rendering a file at `lib/modules/my-alert/views/alert.html`. I'll add this to the list of things that need to be better documented.
