### ISSUE TITLE
Feature request...  asciidoc support

### ISSUE THREAD

**Issue by boydkelly** [apostrophecms/apostrophe#2240]
Would be awesome to have asciidoc support!

**Comment by abea** [comment]
Are you suggesting it for rich text widgets?

**Comment by boydkelly** [comment]
What do you guys think of [hackadoc](https://github.com/hackergarten/hackadoc), fork of [hackmd.io](https://github.com/hackmdio/codimd) using 

> This is a fork of the great hackmd.io. We just thought it would be even greater with AsciiDoctor and so we included [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) the project and changed its name accordingly ;)

I think Atom and others use asciidoctor.js to render .adoc files too.   

It would just be awesome to make an asciidoc file in apostrophe and have it rendered correctly too.

In fact you can edit an adoc file already as some of the code is compatible with markdown.

**Comment by boutell** [comment]
Apostrophe 2.x is committed to ckeditor, and Apostrophe 3.x is committed to TipTap. But it is possible to drop in your own replacement for `apostrophe-rich-text-widgets` without touching the core code at all, and there's an example you can check out:

https://github.com/apostrophecms/apostrophe-tiptap-rich-text-widgets/

So I suggest that you create your own npm module offering the editor of your choice. Then it becomes an option for everyone who is interested to "npm install", with no need to alter the core module.

Going to close this as an issue on the core module but I am interested to see what you come up with!
