### ISSUE TITLE
Add loader on button click that involves ajax request 

### ISSUE THREAD

**Issue by henrywongkar** [apostrophecms/apostrophe#2274]
## The problem to solve

Is your feature request related to a problem you are experiencing that is *not* a bug? Please describe.

> Need a loader so we know that we need to wait instead of clicking too many times and causing too many window open http://prnt.sc/tp1isr

## Proposed solution

Describe the solution you'd like

> Loader and disable the button we just clicked until the request completed would be good

**Comment by boutell** [comment]
You make a very good point but can you clarify exactly how we reproduce
this one? We do have a busy spinner so I am confused.
