### ISSUE TITLE
Support configuring an alternate collection name or entire alternate URL for the REST API of a module

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#2276]
For sane and simple communication between its own browser UI code and the backend, a module will always have a REST API where Apostrophe expects it:

```
/api/v1/module-name
```

However, our module names are now singular (by popular demand). If the module name is `product` this will look like:

```
/api/v1/product
```

While the most common REST convention would be:

```
/api/v1/products
```

So, we should implement a `restAlias` option, which may be set like this:

```
restAlias: 'products'
```

Now the API will respond at BOTH of these URLs:

```
/api/v1/product
/api/v1/products
```

`restAlias` may also start with `/`, in which case it is understood to be a rooted URL, so it can be anywhere, not just `/api/v1`.

**This rule will also apply to `apiRoutes`, `htmlRoutes`, etc.** because the same issue exists when these are viewed as extensions of the REST paradigm to cover actions without a clear pattern in REST URLs. *All* routes for a given module will be impacted by `restAlias`.

**Comment by abea** [comment]
@boutell Do you think we should get this in the backlog still?

**Comment by boutell** [comment]
I would say no, I would say this will be reopened by popular demand if necessary. We're just not hearing it as a need right now.
