### ISSUE TITLE
Unable to change default value for boolean schema field to true

### ISSUE THREAD

**Issue by ngranahan** [apostrophecms/apostrophe#2331]
## To Reproduce

1. Add boolean field to a piece, page, or widget, setting `def: true`

```
{
      name: 'example',
      label: 'Example',
      type: 'boolean',
      def: true,
      choices: [
        { label: 'Yes', value: true },
        { label: 'No', value: false }
      ]
}
```
2. View field in Apostrophe UI to confirm that default value is still set to `false`

## Expected behavior
Setting `def: true` in a boolean schema field should set the default value of that field to `true`.

## Describe the bug
Setting `def: true` does not change the default value of the boolean field to true. Default is always set to `false`.

**Comment by boutell** [comment]
I see Bea has assigned this to himself, missed that earlier, but FYI folks, here is a demo where it works:

https://github.com/apostrophecms/apostrophe-boilerplate/tree/boolean-def-demo

Looking at Nora's example, the difference could be the use of the "choices" option perhaps?

**Comment by boutell** [comment]
I am also unable to reproduce it this way:

```
      addFields: [
        {
          type: 'boolean',
          name: 'cool',
          def: true,
          choices: [
            { label: 'Yes', value: true },
            { label: 'No', value: false }
          ]
        }
      ]
```

`true` is working as the default for me here too.

@ngranahan I think we'll need a branch of apostrophe-boilerplate demonstrating the issue from you to move forward.

**Comment by abea** [comment]
theoretically I will be returning to this.

**Comment by abea** [comment]
Yeah, I double checked as well with fields:
```
  addFields: [
    {
      name: 'booleanFalse',
      label: 'False boolean',
      type: 'boolean',
      def: false,
      choices: [
        { label: 'Yes', value: true },
        { label: 'No', value: false }
      ]
    },
    {
      name: 'booleanTrue',
      label: 'True boolean',
      type: 'boolean',
      def: true,
      choices: [
        { label: 'Yes', value: true },
        { label: 'No', value: false }
      ]
    }
  ],
```

Both default as expected. I'll close until we have some more reproduceable info.
