### ISSUE TITLE
Apostrophe website linked in "About Apostrophe" not available

### ISSUE THREAD

**Issue by torbenlast** [apostrophecms/apostrophe#2432]
Apostrophe version 2.2.0.2

## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Click on the Hamburger Menu Icon
> 2. Click on 'About Apostrophe'
> 3. In the "Info" Tab click on the link to 'Apostrophe Website'
> 4. That link leads to a website which is not available

## Expected behavior
> Link should lead to a working Apostrophe homepage

**Screenshots**
The link to "Apostrophe website" links to _http://apostrophe.github.io/apostrophe/_ 

![Bildschirmfoto vom 2020-09-29 11-27-38](https://user-images.githubusercontent.com/50545231/94540627-f5383580-0246-11eb-82df-f5c95d32115f.png)

and that site is not available:

![Bildschirmfoto vom 2020-09-29 11-30-20](https://user-images.githubusercontent.com/50545231/94540796-2dd80f00-0247-11eb-90c7-fd82c4b8eb5b.png)

**Comment by boutell** [comment]
Hi @torbenlast, this query seems to be about an unrelated product. Some kind of android app maybe?

ApostropheCMS is a content management system and has no native apps, so you're probably looking in the wrong place. Maybe you can track down the author's twitter.
