### ISSUE TITLE
3.0: prompt bug on Node 14

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#2589]
## To Reproduce

Step by step instructions to reproduce the behavior:

1. Set your terminal to use Node 14.
2. Do a fresh install of A3
3. In a linked project, create a new user with `node app @apostrophecms/user:add username admin`

## Expected behavior
Everything runs nicely.

## Describe the bug
A warning is logged: `(node:36344) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`

## Details

**Version of Node.js:**
Node 14

**Server Operating System:**
MacOS

**Additional context:**
This is likely related to the use of `prompt@0.25`. It has `winston` as a dependency, which I don't think supports Node 14. Switching to `prompts` instead of `prompt` should fix this.

**Comment by boutell** [comment]
This may be resolved by Joe's PR, which I tested and merged today, although not with Node 14.

**Comment by bramdeba** [comment]
With Joe's PR everything does run nicely on Node v14.15.0.

Terminal output:
```
MacBook-Pro:apos3 bram$ node app @apostrophecms/user:add test-user admin
✔ Enter a password for test-user: … ********
MacBook-Pro-van-Bram:apos3 bram$ 
```
