### ISSUE TITLE
3.0: Rich Text Editor Toolbar not visible in apostropheCMS 3 demo

### ISSUE THREAD

**Issue by hussainb** [apostrophecms/apostrophe#2654]
![image](https://user-images.githubusercontent.com/4962633/103444046-f4220480-4c8a-11eb-9e5e-306b47bffa7e.png)

![image](https://user-images.githubusercontent.com/4962633/103444052-fd12d600-4c8a-11eb-8012-33c736f86932.png)

**Comment by stuartromanek** [comment]
hey @hussainb .. quick sanity check .. does the rich text toolbar appear when you highlight a selection of text from the above widget?

Currently the toolbar only becomes visible when action can be taken on a specific portion of text, it is not constantly present

**Comment by hussainb** [comment]
@stuartromanek .. Oh god, my bad.. yes it does appear on highlight.. clumsy of me missing that out.
 sorry for the false report.
