### ISSUE TITLE
Rich Text Editor Toolbar not visible in apostropheCMS 3

### ISSUE THREAD

**Issue by Nekkiton** [apostrophecms/apostrophe#2787]
Part of the Rich Text Editor toolbar is not visible if text located close to the left or right side of the screen

![editPanel](https://user-images.githubusercontent.com/11338846/109871560-5e9bf480-7c7c-11eb-8739-88a3cde62a6b.gif)
![fullscreen](https://user-images.githubusercontent.com/11338846/109871564-5fcd2180-7c7c-11eb-9c82-711c01cb0f13.gif)

**Comment by abea** [comment]
A definite bug that we've talked a lot about. We're using the tiptap editor, which is great, but the built-in menu bar options don't quite do everything we need in contexts like this. This is certainly on our radar and a near-term project.

**Comment by Nekkiton** [comment]
Thanks, good to know that

**Comment by itsaalexk** [comment]
This should be marked as solved since I tried replicating it and the sidebar has been changed.

**Comment by BoDonkey** [comment]
Thanks @itsaalexk!
