### ISSUE TITLE
PRO-69 Fragments should support the call / caller syntax like macros do

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#2930]
Macros support this:

```
{% macro render(options) %}
<section
data-` 'accordion' | prefix `='` options | json `'
class="` 'accordion' | prefix `"
>
{% if caller %}
{{ caller() }}
{% endif %}
</section>
{% endmacro %}
```

You call that like:

```
{% call render({ ... }) %}
Body that gets inserted by `caller()` goes here
{% endcall %}
```

It is highly likely that areas could be used with a feature like that, so fragments should support it.

We can do it with rendercall and rendercaller keywords, for parallelism with the "render" keyword already used to render fragments without a body.

 So to get the equivalent of `{% call macroName ... %}` you would use `{% rendercall fragmentName... %}`.

Similarly `rendercaller` (since we probably can't just recycle caller without breaking macros).

**Comment by boutell** [comment]
In the meantime the workaround for generating custom bodies is passing fragments to other fragments as parameters, which does work.

**Comment by myovchev** [comment]
I can give it a try. I can use `3/pro-1185-fragments-calling-fragments` as source branch. Does it sound OK @boutell?

**Comment by boutell** [comment]
Yes that makes sense. Thanks for giving it a go!

**Comment by myovchev** [comment]
Actually it's quite easy, I have a working prototype on my test case repo already. However there are few ways to go, so I'll create a draft PR against the `3/pro-1185-fragments-calling-fragments` and we can discuss it.

**Comment by myovchev** [comment]
@boutell I forgot to add the `closes` magic in the PR, please close.
