### ISSUE TITLE
3.0 Widgets with duplicated ID

### ISSUE THREAD

**Issue by gmarchildon** [apostrophecms/apostrophe#2971]
## To Reproduce

Step by step instructions to reproduce the behavior:

1. Add a widget with an area field (wrapper widget)
2. Add a widget in that area and display it's ID `{{ data.widget._id }}` (inner widget)
3. Duplicated the wrapper widget

## Expected behavior
Both inner widgets should have different ID displayed.

## Describe the bug
Both inner widget will have the same ID. It seems that when duplicating the wrapper widget, the content is copied one to one, ID included. If we duplicated in inner widget, it correctly generate a new ID, so I can safely assume that this behavior is not normal.

## Details

**Version of Apostrophe**
3.0.0-alpha.7

**Version of Node.js:**
12.19.9

**Version of NPM:**
6.14.13

**Server Operating System:**
macOS Catalina Version 10.15.7

**Comment by abea** [comment]
Thanks @gmarchildon. I've logged this in the internal ticket queue.
