### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by AmadeusDeadDmytro** [apostrophecms/apostrophe#3116]
Configuration files are located in config.js and can be accessed by anyone. I tried to move it all out to .env and got the following error -> Error: Configuration property "KEY" is not defined

**Comment by abea** [comment]
I'm not sure what config.js file you're referring to. On the server you can use a `data/local.js` file for environment variables. That shouldn't be committed. A bit more about that here: https://docs.apostrophecms.org/devops/deployment/deployment.html#minifying-assets
