### ISSUE TITLE
MongoError Unable to create piece

### ISSUE THREAD

**Issue by Ramakrishnan-Sathyanarayanan** [apostrophecms/apostrophe#3142]
I am trying to create a piece in apostophe and I faced this weird issue today. 
![image](https://user-images.githubusercontent.com/65652388/120787723-4377a400-c54d-11eb-97f3-a21427a4e6d2.png)

When I tried digging into the db, I found that there is a index on path and workflowLocaleForPathIndex and this specific piece creation is trying to write with empty path values and index condition is not met and hence the error.

How can I make the path value valid or any other help around it would be appreciated.

**Comment by boutell** [comment]
Hello @Ramakrishnan-Sathyanarayanan,

`workflowLocaleForPathIndex` is set in `lib/implementation.js` of `apostrophe-workflow`, like this:

```
  self.ensureWorkflowLocaleForPathIndex = function(doc) {
    if (doc.slug.match(/^\//)) {
      doc.workflowLocaleForPathIndex = doc.workflowLocale;
    }
  };
```

As you can see if the slug starts with a `/` it is set, otherwise it is never set.

So this shouldn't be possible with pieces. Unless perhaps you are doing something custom that would cause a piece slug to start with `/`, which would break many tests in Apostrophe that distinguish pages from pieces.

**Comment by Ramakrishnan-Sathyanarayanan** [comment]
@boutell yeah we are doing customisation eith piece. We figured it out the other day itself. Missed to update here.

We have decided to add validation that restricts slug that starts with / for pieces. 

Thanks for the turnaround.. We can resolve the bug.

**Comment by boutell** [comment]
Hmm, are you saying apostrophe is allowing slugs starting with a / for pieces? That shouldn't happen, so it is interesting by itself, unless it's happening through some custom code of yours.

**Comment by Ramakrishnan-Sathyanarayanan** [comment]
No. I am saying we found that the error was because a user tried adding / in slug for pieces and we are planning to add a front end validation to restrict users from using / in the slug for pieces. Thanks for the help..

**Comment by boutell** [comment]
Ah, OK. I verified that our own UI will not allow a user to do this, so it must be an issue with custom UI and perhaps custom backend logic too.
