### ISSUE TITLE
Pages: Requires an easy way of getting all pages quickly, implement as a wrapper to find with more reasonable defaults for backend pagetree operations.

### ISSUE THREAD

**Issue by suhmantha1** [apostrophecms/apostrophe#315]
.trash(null)
.areas(false)
.published(null)

**Comment by boutell** [comment]
This wrapper would be specifically used in the pages module and should
probably be a method of that. There are a lot of places where we need a
more back-endy set of defaults.

On Wed, Jul 22, 2015 at 3:03 PM, Samantha Combs <notifications@github.com>
wrote:

> .trash(null)
> .areas(false)
> .published(null)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/315>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
