### ISSUE TITLE
3.0: apos UI is always rebuilding in development

### ISSUE THREAD

**Issue by myovchev** [apostrophecms/apostrophe#3184]
## To Reproduce
Make any app related change with a standard app setup (a3-demo or a3-boilerplate). Apostrophe UI will be always rebuilt.

## Expected behavior
The apos UI should be built after performed check 

## Describe the bug
The reason for this bug (I guess) is a typo:
https://github.com/apostrophecms/apostrophe/blob/3.0/modules/%40apostrophecms/asset/index.js#L94

`apos-only-timestamp.txt` is never created from what I read below this line, only `apos-build-timestamp.txt` is created after successful build.

## Details

**Version of Node.js:** any

**Comment by abea** [comment]
Thanks. This is fixed in the next release. Resolved by #3182
