### ISSUE TITLE
How to enable membership and allow users edit content from the frontend?

### ISSUE THREAD

**Issue by hiovi** [apostrophecms/apostrophe#3249]
What would be the best way to sign up users from the front end and allow them to, say for instance, rate an article, or create an order. I would like to use only Apostrophe to keep things simple rather than use a number of third party services. Also I would like to avoid creating a separated single page application.

**Comment by boutell** [comment]
Hi @hiovi, since this is a how-to question, would you please take it to discussions?

https://github.com/apostrophecms/apostrophe/discussions

Happy to respond, just want to keep the discussions and the issues/bug reports separate.

Thank you!
