### ISSUE TITLE
Getting started quickly

### ISSUE THREAD

**Issue by RobertSandiford** [apostrophecms/apostrophe#3518]
So I have installed apostrophe v3 (with a few snags along the way : ) ) What I found is that I only had a couple of options when page editing (rich text, image, video), which didn't allow very much.

I'm wondering what the best way to get a site running quickly is? Does v2 have more options? Do I need to install modules from somewhere?

What I'm looking for ideally is the ability to quickly get a site up, with a visual page editor, but to have the fredoom to extend with code later. Something like wordpress + themes + divi page editor, but just not wordpress if you know what I mean.

I haven't got a lot of time to dig through the docs now, so some kind of quick start to being able to make fuller page layouts would be very helpful.

**Comment by abea** [comment]
The immediate site creation experience you're describing is something we provide in the Assembly commercial product: https://apostrophecms.com/assembly. Little to no coding required to start building a site with more advanced widget options. There is a contact pop-up on the page there if you're interested in demoing that.

The open source offering does ask more of you as a developer with the intention that we aren't deciding for you what the layout should look like or what special widget you'll need. The documentation does have specific code examples for additional widgets, including a multi-column widget, which takes those initial widget options and elevates them.

You can also install the demo site repo, which we use for our main demo, but also has some additional widgets in there as well as basic CSS. https://github.com/apostrophecms/a3-demo/

**Comment by RobertSandiford** [comment]
OK Thanks

**Comment by zenflow** [comment]
@RobertSandiford I found the addition of these 2 widgets from the aforementioned a3-demo project went a long way:
- [columns-widget](https://github.com/apostrophecms/a3-demo/tree/main/modules/columns-widget)
- [container-widget](https://github.com/apostrophecms/a3-demo/tree/main/modules/container-widget)
