### ISSUE TITLE
How to include Vue component in admin UI bundle?

### ISSUE THREAD

**Issue by zenflow** [apostrophecms/apostrophe#3529]
## Question

I'm trying to add a relationship field to a piece's `columns` by copying the [a3-demo](https://github.com/apostrophecms/a3-demo) project exactly:
1. Used this code for the piece's `columns` : https://github.com/apostrophecms/a3-demo/blob/942b057aa0146cf051b21ed4a36beee9d4151273/modules/article/index.js#L89-L96
2. Copied the `DemoCellRelation.vue` file into the same file location (`modules/article/ui/apos/components/DemoCellRelation.vue`)

But when I open the manager for this piece, the column is blank and I see an error in the console:

`[Vue warn]: Unknown custom element: <DemoCellRelation> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Is there something else I need to do to get the `DemoCellRelation` vue component to load in the admin UI?

I searched the docs but couldn't find anything on this. The [documentation on `columns.add.*.component`](https://v3.docs.apostrophecms.org/reference/module-api/module-overview.html#columns) doesn't go into this.

I built and ran the a3-demo project to see if there's an issue there, and no that project doesn't have this issue, and I can't find any other reference to `DemoCellRelation` in that project, so I'm wondering why that vue component file gets loaded fine in that project but not in my own.

## Details

**Version of apostrophe**

3.7.0

**Version of Node.js:**

14.18.0

**Server Operating System:**

Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/3198597/140592731-50c5a88d-d44a-4b3e-807c-4655a5cc5af0.png)

**Comment by boutell** [comment]
Could it be that the admin UI just hasn't been rebuilt? Apostrophe doesn't watch it for the need for a rebuild the same way as `ui/src` unless asked to with the APOS_DEV=1 environment variable. Otherwise it only rebuilds on changes to package-lock.json, on the theory that there could be a new or updated apostrophe module in the project.

We should consider a more nuanced way to handle this. cc @abea

**Comment by zenflow** [comment]
@boutell Yup, that was it. I deleted `apos-build` & `public/apos-frontend` directories and started the dev server again and the problem was fixed. Thanks for the hint!

I'll close this issue since the question is answered and my problem is resolved.
(Of course feel free to reopen for any follow-up purposes.)
Thanks!
