### ISSUE TITLE
Impossible to have slug fields that stay empty

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe#3586]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

1. Create a schema (on a piece type, for example) with a `slug` type field separate from any doc type slug. It should not follow any other fields.
2. Include `def: ''` on the field.
3. Edit that document in the UI and don't enter anything in the slug field.

## Expected behavior
The field value should be empty. Either `null` or an empty string.

## Describe the bug
The string "none" is saved instead. This is because the slug schema field settings run the empty entry through sluggo without passing the field's default value as the sluggo string default.

Arguably the field should stay empty regardless of the field's `def` value (including no value) unless it is following another field.

**Comment by boutell** [comment]
@abea can this change result in an empty slug for an apostrophe document? That would be a bug.

**Comment by boutell** [comment]
Thanks for checking.
