### ISSUE TITLE
Checkboxes are not required when they supposed to be

### ISSUE THREAD

**Issue by barzie01** [apostrophecms/apostrophe#3590]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Create a piece-type. In index.js create a field with the type checkboxes.
> 2. Set required option to true.
> 3. Go to created piece on page.
> 4. Leave all checkboxes unchecked and publish the piece.
> 5. The piece is published.

## Expected behavior
> The piece should not be published when all checkboxes are left unchecked if required option is set to true.

**Comment by abea** [comment]
Thank you for the report! You're right. The validator is doing some checking that cause false negatives.
