### ISSUE TITLE
/api/v1/@apostrophecms/attachment/upload invalid

### ISSUE THREAD

**Issue by sunnyzhifei** [apostrophecms/apostrophe#3782]
post /api/v1/@apostrophecms/attachment/upload a form-data and return  invalid, didn't finished this area ?

![image](https://user-images.githubusercontent.com/34208561/171980457-e06bfb07-679f-4b57-97ea-c532168b1ff5.png)

![image](https://user-images.githubusercontent.com/34208561/171980524-38803496-cce8-4192-b814-8ac65585bbf6.png)

**Comment by boutell** [comment]
Our own admin ui uses this api for all images uploads, so it does work. Most likely you are not using multipart/form-data. The easiest way is to use our apos.http.post method. You can find examples in our open source code of uploading attachments.

**Comment by sunnyzhifei** [comment]
thanks you ,i finish it . its a fetch bug.  i get right response after i delete content-type .
