### ISSUE TITLE
The Select components in contact us page background and color are both white.

### ISSUE THREAD

**Issue by danielasakpa** [apostrophecms/apostrophe#3934]

**Comment by BoDonkey** [comment]
Hi @danielasakpa,
Sorry you are experiencing this. Can you give a little more info so that we can reproduce the issue?
Thanks!

**Comment by ravikumarsingh9907** [comment]
On your contact us page, Let's get started! (choose option) section's options text colour and background colour are same (white).

![Screenshot from 2022-12-22 16-00-32](https://user-images.githubusercontent.com/74643324/209115705-c22e3971-ee3e-4817-a180-b221ac4d9bce.png)

**Comment by BoDonkey** [comment]
What browser are you using? On Chrome it looks okay.

**Comment by ravikumarsingh9907** [comment]
I'm also using Google Chrome Version 107.0.5304.121 on Ubuntu 20.04.5 LTS

Check
![Screenshot from 2022-12-22 16-15-31](https://user-images.githubusercontent.com/74643324/209118146-15331a57-f915-4e08-93e2-29e6a4b1e624.png)

**Comment by BoDonkey** [comment]
Sorry, should have said Chrome 108.0.5359.98 on MacOS 13. Thanks for the report. Time to boot the linux box!

**Comment by BoDonkey** [comment]
This issue should now be resolved. Thanks for your help in pointing this out!!
