### ISSUE TITLE
Multiple Sites within one Apostrophe Installation

### ISSUE THREAD

**Issue by rwatts3** [apostrophecms/apostrophe#398]
Greetings, 

Is there a module or has anyone managed to build a multi site options for apostrophe. 
For example if I have a client that has 3 sites and they would like to manage and share data from within the same apostrophe install. Such as navigating to test.somesite.com and test2.somesite.com, both using resources from somesite.com. 

A possible idea could be add a configuration to app.js where we can pass an array of sites, with a list of options such as subdomain and other options.

**Comment by boutell** [comment]
Hi Ryan,

Not so far.

This sort of thing is likely to be easier in 0.6, which will land in npm
soon, certainly within a month since we plan to use it in a redesign of our
own site.

0.6 is a complete refactoring of Apostrophe in which it's much easier to
reason about where these things should be done.

But it won't be standard equipment.

On Wed, Jan 13, 2016 at 12:20 PM, Ryan Watts <notifications@github.com>
wrote:

> Greetings,
>
> Is there a module or has anyone managed to build a multi site options for
> apostrophe.
> For example if I have a client that has 3 sites and they would like to
> manage and share data from within the same apostrophe install. Such as
> navigating to test.somesite.com and test2.somesite.com, both using
> resources from somesite.com.
>
> A possible idea could be add a configuration to app.js where we can pass
> an array of sites, with a list of options such as subdomain and other
> options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/398>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Thank you. Really looking forward to 0.6 is there a branch I can clone. I'd
like to take a look under the hood possibly contribute if possible .

**Comment by boutell** [comment]
Certainly. Check out the "unstable" branches of the apostrophe module and
the apostrophe sandbox, which are meant to be used together.

On Thu, Jan 14, 2016 at 4:34 PM, Ryan Watts <notifications@github.com>
wrote:

> Thank you. Really looking forward to 0.6 is there a branch I can clone. I'd
> like to take a look under the hood possibly contribute if possible .
> On Thu, Jan 14, 2016 at 1:38 PM Tom Boutell <notifications@github.com>
> wrote:
>
> > Hi Ryan,
> >
> > Not so far.
> >
> > This sort of thing is likely to be easier in 0.6, which will land in npm
> > soon, certainly within a month since we plan to use it in a redesign of
> our
> > own site.
> >
> > 0.6 is a complete refactoring of Apostrophe in which it's much easier to
> > reason about where these things should be done.
> >
> > But it won't be standard equipment.
> >
> > On Wed, Jan 13, 2016 at 12:20 PM, Ryan Watts <notifications@github.com>
> > wrote:
> >
> > > Greetings,
> > >
> > > Is there a module or has anyone managed to build a multi site options
> for
> > > apostrophe.
> > > For example if I have a client that has 3 sites and they would like to
> > > manage and share data from within the same apostrophe install. Such as
> > > navigating to test.somesite.com and test2.somesite.com, both using
> > > resources from somesite.com.
> > >
> > > A possible idea could be add a configuration to app.js where we can
> pass
> > > an array of sites, with a list of options such as subdomain and other
> > > options.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/punkave/apostrophe/issues/398>.
> > >
> >
> >
> >
> > --
> >
> >
> > *THOMAS BOUTELL, *DEV & OPS
> > P'UNK AVENUE | (215) 755-1330 | punkave.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/punkave/apostrophe/issues/398#issuecomment-171772754
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/398#issuecomment-171786833>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Awesome thank you, I appreciate it. 
I'll take a review of the 0.6 milestone and see where I can fit in.

**Comment by rwatts3** [comment]
What's the best way to go about setting up the unstable branches. 

Clone the apostrophe-sandbox module, then add the branch for 0.6 as a dependency. Or Clone both modules  into the same directory ?

**Comment by boutell** [comment]
Clone both repos. Then manually add a symlink in node_modules of the sandbox to the apostrophe module.

**Comment by rwatts3** [comment]
Thank you for that information. 

I will also be looking closely at the new api and module structure, to create a snippets package for apostrophe in `Atom.io`. Possibly doing the same for `Intellij` and `Sublime Text`. If you have any thoughts to keep in mind as I plan this out please feel free to let me know.

**Comment by rwatts3** [comment]
Ok I was able to create the symlink and get the 0.6 site running. However this is all I see when I access the site, and when I try to login with admin demo it tells me the password is incorrect. Any suggestions ? 

http://screencast.com/t/u7v2x9lG

**Comment by jth-** [comment]
The admin user isn't baked into the configuration like it is in `0.5`. In order to add an administrator user, run the following task:

`node app.js apostrophe-users:add admin Admin`

Where 'admin' is the username, and 'Admin' is the group name.

**Comment by rwatts3** [comment]
Ok that makes sense. Thank you for the insight

**Comment by rwatts3** [comment]
Noticed that import/export functionality was not found in the milestone issues. Is it safe to assume it will also be brought over to 0.6 ?

**Comment by boutell** [comment]
Yes, eventually! And of course an import from 0.5 is planned.

On Fri, Jan 15, 2016 at 1:38 PM, Ryan Watts <notifications@github.com>
wrote:

> Noticed that import/export functionality was not found in the milestone
> issues. Is it safe to assume it will also be brought over to 0.6 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/398#issuecomment-172046526>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Ryan, check this out:

https://github.com/punkave/apostrophe/blob/unstable/README.md

This new README is actually a how-to based on my experience today building
a simple "L-shaped" website with 0.6 unstable.

Covers a lot of things you're likely to run into, and I plan to continue
with it as I do more with my straw-man site. (:

On Fri, Jan 15, 2016 at 4:45 PM, Tom Boutell <tom@punkave.com> wrote:

> Yes, eventually! And of course an import from 0.5 is planned.
>
> On Fri, Jan 15, 2016 at 1:38 PM, Ryan Watts <notifications@github.com>
> wrote:
>
>> Noticed that import/export functionality was not found in the milestone
>> issues. Is it safe to assume it will also be brought over to 0.6 ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe/issues/398#issuecomment-172046526>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Thank you for the readme . I'll head over there now to review.

**Comment by rwatts3** [comment]
Has there ever been any talk in regards to re-writing apostrophe using http://meteor.com/ I think meteor's infrastructure, and framework would be a great match for apostrophe and vice versa.

**Comment by boutell** [comment]
Unfortunately we're way, way, way, way too far down the road with 0.6 for
that. (:

On Fri, Jan 15, 2016 at 5:33 PM, Ryan Watts <notifications@github.com>
wrote:

> Has there ever been any talk in regards to re-writing apostrophe using
> http://meteor.com/ I think meteor's infrastructure, and framework would
> be a great match for apostrophe and vice versa.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/398#issuecomment-172114072>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by nexbit** [comment]
Hi
I don't know if this is the correct place to ask (probably not), but I'm eager to contribute on modules/features, but at the same time I need a fairly stable version to run my site on..

How safe it is to use 0.6/unstable for running a live site, while developing new features at the same time?
And, as a companion question, when do you plan to release a rather stable (say almost complete beta) 0.6 version?

Thank you all!
P.

**Comment by boutell** [comment]
I am not going to make any forward-looking statements. (: All programmers
are incurable optimists.

Instead I will simply point out that we are now building out two client
projects on 0.6. Once these pilot projects reach the finish line, it is
likely that we'll do just about everything in 0.6. And these are projects
with customer-driven deadlines, so it won't be more than 2-3 months.


On Mon, Feb 29, 2016 at 6:44 AM, Paolo Furini <notifications@github.com>
wrote:

> Hi
> I don't know if this is the correct place to ask (probably not), but I'm
> eager to contribute on modules/features, but at the same time I need a
> fairly stable version to run my site on..
>
> How safe it is to use 0.6/unstable for running a live site, while
> developing new features at the same time?
> And, as a companion question, when do you plan to release a rather stable
> (say almost complete beta) 0.6 version?
>
> Thank you all!
> P.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/398#issuecomment-190173910>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rwatts3** [comment]
Hi @boutell 

I certainly agree with your response. I suppose the most challenging issue for those within the community that would like to assist in building 0.6 is the fact that the milestone issues are a bit hard to decipher in regards to :

- What's remaining, truly remaining for the world to use.
- Where can "I" jump in and help,
- And lastly how are "you" `Punkave/Apostrophe` building things out so that we can follow the pattern.

I believe if those 3 points can be specified with a little detail, people from the community such as my self can potentially jump in and help so that the heavy lifting is not just on Punkave.

For me it's not a matter of sitting back and waiting, it's more of not wanting to go off the rails with building some functionality just to find that it was not following the build pattern, or that it's super custom for my own personal projects.

**Comment by jth-** [comment]
Very happy to hear the excitement from the community around the release of 0.6!

Making it more accessible for the community to contribute to Apostrophe is definitely a goal of ours going forward. However, in terms of 0.6 at its current juncture, we have a last couple fundamental building blocks to solidify before opening up the branch to wider contributions.

As @boutell mentioned, we’ve begun to develop client sites with 0.6, and those projects have their own deadlines, so getting the 0.6 branch to a stable place is a top priority for our development team right now.  Once we’re there, our focus will shift to developer documentation, where we’ll provide detail both on building websites and the patterns used to build and extend the new version of Apostrophe. We’ll also be working towards curating a more contributor-friendly backlog.

Thanks again for the interest in the project and the feedback!

**Comment by levint** [comment]
Hi all, with v2.0, how do we make multiple sites (multi-tenancy) with just one apostrophe installation?

**Comment by boutell** [comment]
Hi, multi-tenancy is not something that has been on our internal priority list for 2.x thus far. Our typical client wants a site exclusively for their purposes, and the model of a node process and mongo database per client tends to fit with that. However, there are ways to alter this picture, and so that will change if we have a client (or an enterprise Apostrophe support customer) for whom it is a priority to develop that feature.

**Comment by boutell** [comment]
More on Apostrophe enterprise support: http://apostrophecms.org/support/enterprise-support.html

**Comment by stuartromanek** [comment]
This is now a work in progress https://github.com/apostrophecms/apostrophe-multisite
