### ISSUE TITLE
3.37.0 Incorrect doc localization reference

### ISSUE THREAD

**Issue by stepanjakl** [apostrophecms/apostrophe#3990]
Hello,

I am quite unsure what caused this issue, but suddenly in an A3 app, the `current` localization key stopped appearing. The localization object started pointing to the `previous` doc version. I don't really know why the `previous` doc versions of the home page were created in the first place.

<img width="626" alt="Screenshot 2023-01-07 at 13 10 22" src="https://user-images.githubusercontent.com/47005900/211152334-10cff22d-0062-4033-b806-8283ebdf5fef.png">

I dug deeper into the codebase and found that the `localizations` array consists of few different docs:

https://github.com/apostrophecms/apostrophe/blob/f130c2474b45b6d43ba74ac88def2eae3102807b/modules/%40apostrophecms/i18n/index.js#L130

<img width="415" alt="Screenshot 2023-01-06 at 12 28 31" src="https://user-images.githubusercontent.com/47005900/211152461-1c5d4009-0428-47e1-99a5-d53b95e40432.png">

It just happens to pick the first object that satisfies this condition (which in our case is the `previous` doc version): 

https://github.com/apostrophecms/apostrophe/blob/f130c2474b45b6d43ba74ac88def2eae3102807b/modules/%40apostrophecms/i18n/index.js#L148

I managed to fix it with a modified condition:

```js
const doc = localizations.find(doc => doc.aposLocale.split(':')[0] === name && doc.aposLocale.split(':')[1] === context.aposLocale.split(':')[1]);
```

I can create a PR for this if you think it's a suitable solution.

However, my suggestion only treats the symptomps as the cause of the issue (i.e. the generated `previous` docs) might lay somewhere else.

**Comment by ValJed** [comment]
Hi @stepanjakl !
Thank you for this detailed issue.
You're right this is a bug from apostrophe, but these in the localization the previous docs should not be available.
The issue comes from the `aposMode` that is not properly updated when switching a published doc into a previous one.

I'm currently working on a fix, I keep you informed.

**Comment by ValJed** [comment]
A PR is open to fix this issue. It should be available in the next release.
You can use it or test it on [this branch](https://github.com/apostrophecms/apostrophe/tree/pro-3452-previous-docs-in-localizations) if needed.

**Comment by stepanjakl** [comment]
Hello @ValJed, thank you for sorting this out so quickly! It is working well now.
