### ISSUE TITLE
Suggestions on what to do to improve performance

### ISSUE THREAD

**Issue by jansensan** [apostrophecms/apostrophe#4030]
## Question or comment

My site's Node process seems to "idle" at 25% when there are no visitors, and 75%+ when there are. mongod seems steady at 20% all the time:

<img width="640" alt="capture of processes on server" src="https://user-images.githubusercontent.com/1410355/216129810-ad9f4829-782d-4741-a0bb-4674ea47ae60.png">

There is likely some work that could be done on my part to improve Apos' performance no? I am uncertain what to take into consideration, so that's why I am asking here.

## Details

**Version of Apostrophe:**
Apos v2.223.1

**Version of Node.js:**
v16

**Server Operating System:**
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-197-generic x86_64)

**Comment by boutell** [comment]
I haven't seen this behavior. For context, how much RAM and how many CPU cores does this server have?

**Comment by jansensan** [comment]
2 GB Memory, 50 GB Disk. From the image name I would believe a single CPU core.

**Comment by boutell** [comment]
OK, that should generally be adequate.

Apostrophe doesn't typically do this when there is no traffic, no. I usually see zero load on Node.js in the absence of traffic. I would look at whether you have any custom Node.js code that does extra work, for instance on an interval timer.
