### ISSUE TITLE
default value in select doesnt show conditional fields

### ISSUE THREAD

**Issue by ecb34** [apostrophecms/apostrophe#4049]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Go to home page
> 2. Click on add content
> 3. Add sample widget
> 4. The conditional field is not shown

## Expected behavior
> Show the conditional field when you open the widget

## Describe the bug
> The default value for select type is not working with conditional fields, in the repository im using dynamic choices but it doesnt work with static choices too.

P.S with dynamic choices if the select field is not mandatory, there is no empty option in the select, that is a different behavior than the one we have when using static options, is that the desired behavior? 

## Details

**Version of Node.js:**
v16.16

**Server Operating System:**
Ubuntu 20

**Additional context:**
You can access the code here https://github.com/ecb34/A3-conditional-field-bug
its the boilerplate repository with a sample widget

**Video**

https://user-images.githubusercontent.com/26570009/219345862-91009c26-0e18-4346-830e-c2b18c666d52.mp4

**Comment by BoDonkey** [comment]
Hi @ecb34,
Thanks for adding this issue and the helpful repo! I agree that this should not be the desired behavior, nor is it the behavior I would expect. I'm opening a ticket on this now.
Cheers,
Bob

**Comment by Bidhu1024** [comment]
I can solve this issue by adding a label over the select tag.  please assign this issue to me. @BoDonkey

**Comment by BoDonkey** [comment]
Hi @Bidhu1024  - We don't utilize that feature, but you are welcome to work on the issue. I do know that there was a ticket made for this, and an engineer on our team should be working on this during the current cycle. However, if you would like to submit a PR we would welcome it. Just let me know when you submit the PR so I can assign the code for review.
Cheers,
Bob

**Comment by Bidhu1024** [comment]
@BoDonkey Hey Bob, I can complete within a day or two.
