### ISSUE TITLE
Give a proper delay for popovers 

### ISSUE THREAD

**Issue by rohan9024** [apostrophecms/apostrophe#4075]
## The problem to solve

When hovered over the navlinks the popovers displayed a random and there is no delay.

https://user-images.githubusercontent.com/64919642/223352355-9c90d1fd-bcdf-49a2-bcde-2f90cfbe77fc.mp4

## Proposed solution

I can make the animations look much more smoother and appealing.
Please assign me this issue.

**Comment by BoDonkey** [comment]
Hi @rohan9024,
We appreciate you pointing these issues out. The repo for our product website is currently private, so it isn't open for non-Apostrophe employees to make code changes. We encourage you to take a look at our public repos for other ways that you could contribute.
Thanks!
Bob
