### ISSUE TITLE
We can add icons instead of text being displayed

### ISSUE THREAD

**Issue by rohan9024** [apostrophecms/apostrophe#4076]
## The problem to solve

There is text which is used for links instead icons will look much better.

![image](https://user-images.githubusercontent.com/64919642/223353209-903bd95d-5a0a-4cf8-9a4e-35fe37b9f2e2.png)

Please assign me this issue

**Comment by BoDonkey** [comment]
Hi @rohan9024,
Thanks again. I commented on your other issue and have passed these issues to our team to look at.
Cheers,
Bob
