### ISSUE TITLE
Dependency issues when running with pnpm

### ISSUE THREAD

**Issue by notpushkin** [apostrophecms/apostrophe#4126]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

1. Install pnpm: https://pnpm.io/installation
2. Clone the boilerplate: `git clone https://github.com/apostrophecms/a3-boilerplate apos-app; cd apos-app`
3. Install dependencies: `pnpm i`
4. Run `pnpm run dev`
5. See error:

    ```
    ERROR in ./apos-build/default/src-import.js 28:0-134
    Module not found: Error: Can't resolve 'postcss-loader' in '/Users/ale/tmp/apos-app'
    ```

    (or similar for `css-loader` and `sass-loader`)

6. Try adding those: `pnpm add -D postcss-loader css-loader sass-loader`
7. See more errors: https://gist.github.com/notpushkin/1c6569a5662d0a466aca9e99fd828b10

## Expected behavior

`pnpm run dev` starts the dev server without errors.

## Describe the bug

Apparently, `./apos-build` relies on the particular `node_modules` structure that npm produces – in particular, it seems to depend on packages that aren't declared in package.json, but are transitive dependencies of other packages. This should generally be avoided in Node.js, as these implicit dependencies may break any time: https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html

pnpm explicitly puts only declared dependencies into `node_modules`, so this assumption breaks. Here's the description of `node_modules` structure it produces: https://pnpm.io/symlinked-node-modules-structure

## Details

**Version of Node.js:**
v18.15.0

**Server Operating System:**
macOS 12.3.1

**Comment by boutell** [comment]
Hi @notpushkin, `css-loader` and `postcss-loader` are properly declared as dependencies of `apostrophe`.

While we don't use `pnpm` in-house, if you can clarify any specific dependencies that are (1) required by the apostrophe module source code and (2) not enumerated in package.json, we can certainly fix that, or accept a PR.

**Comment by notpushkin** [comment]
@boutell I think the issue is, the `apos-build` directory generated by `apostrophe` package is not in fact a part of it, and thus doesn't get access to its dependencies with pnpm. For it to work, all the dependencies it might need have to be specified in the project's package.json, and to `apostrophe` itself, those would be `peerDependencies` then.

Another possible solution is to tweak imports generation in `apos-build` to specify absolute paths for all imports (like `src-import.js` does right now.

**Comment by myovchev** [comment]
I'm aware of this problem. I first faced it a few years ago in a `rush` monorepo. It uses pnpm by default, so I was forced to switch to npm package management (which comes with a lot of tradeoffs in this case). 

I can't describe the problem better than it's done in this ticket. I have a basic understanding about what pnpm does and why transitive dependencies are a bad thing. I've never searched for a solution and I don't think there is an easy one. But I might be wrong.

In theory Webpack itself is responsible for resolving dependencies (except those directly imported in the webpack configuration). All build pipelines are declaring resolve configuration in the proper order (admin UI uses only apos deps, while `src` looks first at the project level and falls back to apos deps). I don't see any problem here. 

I can see dependencies introduced on a Webpack config level as the source of the problem. I can investigate and see if there is a sensible solution. I'm also ready to collaborate with those who have more details on that problem or concrete solution ideas.
