### ISSUE TITLE
Dropdown menu options difficult to read due to color scheme

### ISSUE THREAD

**Issue by Sukhendu2002** [apostrophecms/apostrophe#4164]
## The problem to solve

When using the contact us page or the demo page, the dropdown menu options are not fully visible due to the font and background color. 

## Proposed solution

This could be achieved by changing the font color or background color of the dropdown menu so that the options are more visible.

## Alternatives

One alternative solution could be to use a different type of input, such as a list of options, that doesn't have the same issue of the options getting cut off due to font and background color.

## Additional context

![image](https://github.com/apostrophecms/apostrophe/assets/76804228/317bb1e5-2c4a-4c87-a904-80c9667cde35)

**Comment by BoDonkey** [comment]
Hi Sukhendu2002,
Thanks for the report. I was wondering what browser/OS you are using? I have tried both Chrome and Firefox and can not replicate what you are seeing. Any additional info would be great.
Cheers,
Bob

**Comment by Sukhendu2002** [comment]
Hi Bob,
Thank you for getting back to me. I used Edge, Chrome, and Brave on my end as well, and I am currently running Windows 11 as my operating system.
Please let me know if there is any additional information I can provide that may be helpful in resolving this issue.
Thank you,
Sukhendu

**Comment by GitsOfVivek** [comment]
Hey, I would like to work on this issue. Can you elaborate more?

**Comment by BoDonkey** [comment]
Sorry @GitsOfVivek - This issue is for a private repo that isn't open for contributions. Additionally, I haven't been able to reproduce the issue.

**Comment by triskuit** [comment]
This issue should be resolved. Lemme know if that's not the case!

**Comment by Pankaj-Surya** [comment]
Hey @Sukhendu2002,
1.Identify the Styles: Locate the CSS styles responsible for the dropdown menu's font color and background color. These styles might be defined in a stylesheet or inline within the HTML code.

2.Adjust Colors: Modify either the font color or the background color (or both) to achieve a higher contrast between the two. This can be done using valid CSS color codes.

/* Example: Increasing font color contrast */
.dropdown-menu {
    color: #ffffff; /* White font color */
    background-color: #333333; /* Dark background color */
}
3.Test and Validate: Apply the changes on a local or development environment and test them thoroughly. Ensure that the dropdown menu options are now clearly visible and the contrast is satisfactory.

4.Responsive Design: Ensure that the changes made are responsive and do not negatively impact the user experience on different devices and screen sizes.

**Comment by BoDonkey** [comment]
Hi @vivekrajput-93,
If you take a look at the comments above, you can see that this issue was raised about a private repo. That repo isn't open for contributions from the open-source community. Sorry! Greate enthusiasm, but it is important when you are trying to find issues to work on that you read all of the comments that have been made on the issue. Feel free to look through our public organization repos for another issue. I would love to help you get started! Here is our Discord where we have some open source discussion channels. https://discord.com/invite/XkbRNq7
Bob

**Comment by BoDonkey** [comment]
Hi @Pankaj-Surya,
Great enthusiasm and help! Thanks for jumping in. We are trying to build our open source community of Discord. Feel free to jump in and invite others to talk about anything open source!
Cheers,
Bob
