### ISSUE TITLE
UI,UX enhancement using placeholders

### ISSUE THREAD

**Issue by surendrapm** [apostrophecms/apostrophe#4166]
UI,UX enhancement 

In ContactUs form placeholders are missing
![Screenshot from 2023-05-22 11-15-56](https://github.com/apostrophecms/apostrophe/assets/112800253/c93bb099-a8a3-404a-af09-f548a17bb269)

> Mention any other context or attach screenshots regarding the feature request.
> Check the existing issue labels and add any you think are relevant, e.g.,
> `UI`, `UX`, `accessibility`, `security`.

**Comment by imbhaskarn** [comment]
@surendrapm Hey please assign me this.

**Comment by BoDonkey** [comment]
@imbhaskarn These potential enhancements are for the ApostropheCMS website, which is a private repo. While we would love any contributions you would like to make in our public repos, this issue is something we would handle internally.

**Comment by surendrapm** [comment]
yeah i agree @BoDonkey with your point but if the placeholders like for example instead of empty input name box we can give enter your name ... like this

**Comment by Kevin-Usadadiya** [comment]
I would like to contribute to this issue as it is my first open source contribution

**Comment by Kevin-Usadadiya** [comment]
![Screenshot (14)](https://github.com/apostrophecms/apostrophe/assets/83108939/5c46f622-0f3d-470f-9155-6f1844da13da)
Like this?

**Comment by BoDonkey** [comment]
@Kevin-Usadadiya As it says in the comments above, our website is a private repo, so we don't take code contributions. I would be happy to work with you on any of our other repos. Just go to https://github.com/orgs/apostrophecms/repositories and see if there is a repo you would like to work on. Maybe "random-words".
Cheers,
Bob

**Comment by Kevin-Usadadiya** [comment]
Thanks

**Comment by Kevin-Usadadiya** [comment]
Does the company is hiring
I would to contribute to code internally
