### ISSUE TITLE
Return an empty string for an undefined date/time field of a piece-type is displayed in a column with component: 'AposCellDate'

### ISSUE THREAD

**Issue by chmdebeer** [apostrophecms/apostrophe#4291]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Add a "column" for a piece-type with a date/time field and set the component to AposCellDate, for example:
```
columns: {
    add: {
      firstName: { label: 'First Name' },
      lastName: { label: 'Last Name' },
      confirmedOn: { label: 'Confirmed On', component: 'AposCellDate' }
    }
  }

```
> 2. Add a piece of that piece-type but leave the date field empty
> 3. The admin interface will display today's date since the empty field is passed to "new Date()" which returns today's date.

## Expected behavior
> Return an empty string.

## Describe the bug
> in @apostrophecms/ui/ui/apos/components/AposCellDate.vue the method formatDateColumn needs protection from an empty field.
> I did the following but it is crude and I am sure the is a more elegant way of handling it:
```
...
  methods: {
    formatDateColumn (value) {
      if (!value) {
        return "";
      }
      const format = this.$t('apostrophe:dayjsCellDateFormat');
      // endsWith allows it to still match when the i18n show debug mode
...
`

**Comment by AllanKoder** [comment]
Hi, could I work on a fix for this?

**Comment by BoDonkey** [comment]
Hi @AllanKoder ,
 We don't formally assign issues, so if you want to work on this it is fine. Do you have any experience with Apostrophe?
Cheers,
Bob

**Comment by AllanKoder** [comment]
I've messed around with the CMS and I have the dev environment set up. I'll get started on it.
