### ISSUE TITLE
Update the new Twitter Logo 

### ISSUE THREAD

**Issue by niranjan-kurhade** [apostrophecms/apostrophe#4320]
## The problem to solve

Update the logo of Twitter to the latest logo (X).

In the footer we are still using the old logo of Twitter in the footer of the website. 
![image](https://github.com/apostrophecms/apostrophe/assets/97905637/1365f488-7a44-44c7-b52f-05583186c427)

## Proposed solution

New logo to be implemented.

**Comment by niranjan-kurhade** [comment]
Please assign this issue to me! I would like to work on it.

**Comment by BoDonkey** [comment]
Hi @niranjan-kurhade, are you talking about the Twitter logo in the core of Apostrophe, or on the marketing site (https://apostrophecms.com/)?

**Comment by niranjan-kurhade** [comment]
> Hi @niranjan-kurhade, are you talking about the Twitter logo in the core of Apostrophe, or on the marketing site (https://apostrophecms.com/)?

Yes, the mentioned screenshot is of the Marketing Site.

**Comment by BoDonkey** [comment]
That site is internally developed on a private repo. Thanks for the heads-up and the request to help, but it isn't a repo we assign people outside of the organization to work on.

**Comment by niranjan-kurhade** [comment]
> That site is internally developed on a private repo. Thanks for the heads-up and the request to help, but it isn't a repo we assign people outside of the organization to work on.

Okay, Np! Is there any Twitter logo in the core of Apostrophe?

**Comment by BoDonkey** [comment]
The core of Apostrophe uses an older version of the vue-material-design-icons package. So it actually contains the older version of the icon. Right now if users want a different set of icons they need to register them. Maybe @boutell could comment on whether it would be worth registering a new icon to be used for twitter in core.

**Comment by boutell** [comment]
This would only be an issue in the admin UI and we don't use it in the admin UI to my knowledge. So I think this issue can be closed. Thank you for pointing out the issue!
