### ISSUE TITLE
Enlarge the authoring section

### ISSUE THREAD

**Issue by thomas-rousselot** [apostrophecms/apostrophe#4343]
## The problem to solve

The panel opened when editing section content (text, links...) is too narrow. When editing a link, for example, we can only see the left half of the link to: portion (cf screenshot below). The save button to save link to edits is barely accessible.
<img width="1496" alt="Capture d’écran 2023-11-14 à 16 04 22" src="https://github.com/apostrophecms/apostrophe/assets/71826125/f1ffd07a-df4b-4dcd-83f0-49fe2b007711">

## Proposed solution

Could it be possible for the contributor to adjust the with of the panel? Or at least could it be possible to make it wider by default? Maybe up to the redline as suggested in the screenshot below?
<img width="1495" alt="Capture d’écran 2023-11-14 à 16 08 03" src="https://github.com/apostrophecms/apostrophe/assets/71826125/ede91fde-4427-4a0d-83d1-bd0fe160e470">

This is something that we've seen in Storyblok for example.

## Additional context

Currently, I don't think it accessible enough for contributors and it makes authoring a little difficult for the non tech savvy and even for some people with a little tech knowledge.

**Comment by boutell** [comment]
Hi Thomas, yes we have an internal ticket on this which has sat for a rather long time given the value and how straightforward it is, I'll nudge it.

BTW if you're working with one of our customers let me know.

**Comment by thomas-rousselot** [comment]
Hi. Yes we're working with Michelin. If you can help fixing this, that'd be great. It would definitely add value and make authoring more pleasant. Thanks.

**Comment by boutell** [comment]
Hi Thomas, it will help greatly in prioritization if this issue comes to the Apostrophe Enhancements gitlab board as a ticket so that it can be addressed in the Michelin support stream. Please reach out to Sundeep or Stephane or I can make an introduction, let me know.

**Comment by thomas-rousselot** [comment]
I thought I was opening a ticket here :) Can you give me access to the Michelin support stream then?

**Comment by thomas-rousselot** [comment]
@boutell Do you think you could give me access to Sundeep or introduce me to Stephan so I can post my tickets to the Michelin environment? Thanks !

**Comment by boutell** [comment]
Hi Thomas, yes of course, please send email to tom@apostrophecms.com so I can make the introductions. Difficult to do that just from github since there is no contact info.

**Comment by boutell** [comment]
(Internal note: update PRO-3286 if Michelin agrees)

**Comment by ETLaurent** [comment]
https://github.com/apostrophecms/apostrophe/pull/4445
