### ISSUE TITLE
Token API expires every 2 weeks. Can we automatically renew it?

### ISSUE THREAD

**Issue by thomas-rousselot** [apostrophecms/apostrophe#4346]
## Details
We're working on a project for Michelin. But the API token expries every 2 weeks and we have to manually renew it then. When token expires, content is no longer available, leaving a blank space.
[
![Capture d’écran 2023-11-16 à 15 20 31](https://github.com/apostrophecms/apostrophe/assets/71826125/c48c7444-d6e3-4287-9ad5-08867b330240)
](url)

## Expected behavior
Is it possible to change this? Otherwise, is there a way to automatically renew it so we don't have to manually renew it every week?

**Comment by boutell** [comment]
What token are you referring to? Is this an `apostrophe-headless` bearer token? An A3 bearer token? 

If you need this dealt with in a timely fashion for Michelin please bring it to the Michelin gitlab apostrophe-enhancements board with appropriate details.

**Comment by thomas-rousselot** [comment]
Hi. It's the A3 bearer token indeed. https://v3.docs.apostrophecms.org/reference/api/authentication.html#bearer-tokens
Could you give me access to the Michelin gitlab apostrophe-enhancements board so i can resubmit the request there?

Thanks

**Comment by boutell** [comment]
Please reach out to tom@apostrophecms.com so I can connect you with the appropriate people on the Michelin team. Thanks!

**Comment by boutell** [comment]
The docs are being updated to reflect the fact that the `bearerTokens.lifetime` option of `@apostrophecms/login` is specified in milliseconds, not seconds.
