### ISSUE TITLE
Schemas: "select" should take "multiple" and "style" options, rather than having lots of similar field types

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#440]
Single select:

```
{
  type: 'select',
  // default
  style: 'dropdown'
}
```

```
{
  type: 'select',
  style: 'radio'
}
```

Multiple select with checkboxes:

```
{
  type: 'select',
  multiple: true,
  style: 'checkboxes'
}
```

Multiple select with selectize:

```
{
  type: 'select',
  multiple: true,
  // default
  style: 'dropdown'
}
```

cc @agilbert @jth-

**Comment by jth-** [comment]
I like the sound of this.

Would a feature like 'Show Fields' work with a multiple select or checkboxes? I think it could, just worthy of some further consideration.

**Comment by boutell** [comment]
It could, just yeah, worth noting that it has to be implemented correctly
for all the cases.

On Mon, Feb 22, 2016 at 9:13 AM, Jimmy Harrison <notifications@github.com>
wrote:

> I like the sound of this.
>
> Would a feature like 'Show Fields' work with a multiple select or
> checkboxes? I think it could, just worthy of some further consideration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/440#issuecomment-187193776>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
