### ISSUE TITLE
Vimeo videos not in format vimeo.com/video/123456 cause 400 invalid error

### ISSUE THREAD

**Issue by LeviticusMaximus** [apostrophecms/apostrophe#4615]
I know that there is a fix for this in the pipeline, just putting this bug up here to help anyone currently scratching their heads as to why their previously fine Vimeo video in the format

vimeo.com/1234567

is no longer accepted as a valid url - there's an oembetter fix that is currently unreleased, so until it is, current fix options are either to:

**a)  overrride the oembetter package version in app.js**

```
  "overrides": {
    "apostrophe": {
      "oembetter": "git+https://github.com/apostrophecms/oembetter#main"
    },
  }
```

**b)  use vimeo.com/video/1234567 url format**

**Comment by BoDonkey** [comment]
Fix is out - thanks for adding the heads-up!
