### ISSUE TITLE
max widgets allowed in the area isn't working when expanded:true

### ISSUE THREAD

**Issue by kbusim-icims** [apostrophecms/apostrophe#4737]
Running ^4.5.4 version of Apostrophe

## To Reproduce

Step by step instructions to reproduce the behavior:

- For any given widget whose type is area.
- Case1: set the expanded: true and max: 2
- Case2: set the expanded: false or better remove expanded field, and max:2
- Observe that in case1, max:2 doesn't work, it shouldn't let you add widget after second time.

## Expected behavior
> When configuring an area's options, 'max' field sets the maximum number of widgets allowed in the area.
https://docs.apostrophecms.org/reference/field-types/area.html#max

## Describe the bug
> The max limit (number of widgets) allowed in the area is not working when expanded is set to true.
It works perfectly fine when expanded is set to false, or never set.

## Details
**Code:** 
`columnFooterLayout: {
          label: 'apostrophe:columnFooterLayout',
          type: 'area',
          options: {
            max: 2,
            columns: 2,
            expanded: true,
            widgets: {
              'footer-l-regular-width': {},
              'footer-l-half-and-half': {},
              'footer-l-two-thirds-one': {},
              'footer-l-one-third-two': {},
              'footer-l-thirds': {},
              'footer-l-quarters': {},
            },
          },
          if: {
            footerType: basicFooter,
          },
        }
`

**Version of Node.js:**
20.11.0

**Server Operating System:**
Ubuntu WSL1 (Windows Subsystem for Linux)

**Comment by boutell** [comment]
Thanks. I see that you are a customer, that makes this a warranty issue,
please do open a Zendesk ticket to make sure that we give you timely
support on this.


THOMAS BOUTELL | CHIEF TECHNOLOGY OFFICER
APOSTROPHECMS | apostrophecms.com | he/him/his

**Comment by kbusim-icims** [comment]
https://support.apostrophecms.com/hc/en-us/requests/1014
@boutell I've created the zendesk ticket.
pls do the needful.
Thanks!

**Comment by boutell** [comment]
Appreciate that.
