### ISSUE TITLE
In Rich test editor, can you create </p> returns instead of <br />?

### ISSUE THREAD

**Issue by facultymatt** [apostrophecms/apostrophe#48]
Seems I can't get the text editor to wrap paragraphs in <p> tags. Instead it seems the default behavior is to use <br /> tags.

Is this a setting? Is there a way to over ride this ?

**Comment by alexgleason** [comment]
Was this resolved? There still doesn't seem to be a way to insert paragraph tags.

**Comment by boutell** [comment]
There is a HOWTO now on configuring CKEditor. Changing CKEditor is out of scope for Apostrophe, but hopefully you can arrive at the desired behavior by configuring it.
