### ISSUE TITLE
Please upgrade font awesome, or provide a simple way for end user to upgrade. 

### ISSUE THREAD

**Issue by facultymatt** [apostrophecms/apostrophe#54]
Apostrophe is using #Font Awesome 2.0, but font awesome is on 3.2.1. Please upgrade!

**Comment by Megabyteceer** [comment]
Is it any way to update font awesome to 4.6? Currently i didn't find another way only rename fa classes and fonts and include it all paralelly with old fa.

**Comment by boutell** [comment]
fontawesome has been upgraded in the unstable branch, which will be published as 2.0.0 in the next few days; we have no plans to upgrade fontawesome in A2 0.5.
