### ISSUE TITLE
No way to bootstrap a site without hardcoded groups

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#718]
There is currently no way to bootstrap a site without passing through a phase in which groups are preconfigured for apostrophe-users via the `groups` option. This is tedious if your intention is to have admin-edited groups.

**Comment by useltmann** [comment]
@boutell  I just run into this. Is there a way to circumvent it?

**Comment by boutell** [comment]
`node app apostrophe-groups:add admin admin` is a thing now. That makes a new group called `admin` with the `admin` permission. You can list as many permission names as you want after the group name.

I will add this to the permissions HOWTO.
