### ISSUE TITLE
Placeholders for aposArea

### ISSUE THREAD

**Issue by etodanik** [apostrophecms/apostrophe#84]
Is there any good way to create a placeholder text for aposArea that shows in admin mode?

This is slightly different to if aposAreaIsEmpty, because what I want to do is display something like "Put some great content here..." and have it disappear when the user clicks that area.

**Comment by spacecowboyian** [comment]
Is there a way to make a placeholder that is viewable publicly?

**Comment by boutell** [comment]
That's a different animal from the initialContent option, which is a clue
to the developer. Your solution looks more like this:

```
{% if not page._edit and aposAreaIsEmpty(page, 'areaname') %}
  do alternate thing
{% else %}
  call aposArea normally
{% endif %}
```



On Wed, May 25, 2016 at 4:19 PM, Ian Jennings <notifications@github.com>
wrote:

> Is there a way to make a placeholder that is viewable publicly?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe/issues/84#issuecomment-221694644>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
true
