### ISSUE TITLE
Extra joins in the schema for apostrophe-pieces-widgets should work without extra code

### ISSUE THREAD

**Issue by boutell** [apostrophecms/apostrophe#854]
The current implementation does not call schemas.join at all. Instead, it should call schemas.join with a subset of the schema that excludes `_pieces`.

**Comment by boutell** [comment]
cc @grdunn

**Comment by abea** [comment]
I just came across this as a problem as well while trying to set a link to the piece's index page even if there aren't pieces to display (no upcoming events in `apos-events-widgets` in this case).

**Comment by boutell** [comment]
This was fixed in 2.61.0.
