### ISSUE TITLE
user._permissions.edit causes problems with the adminBar

### ISSUE THREAD

**Issue by fotisp** [apostrophecms/apostrophe#869]
We have a use case where we have 2 different apostrophe-pieces, lets say "piece-a" and "piece-b". The menu to manage these are available in the admin bar, as they should be. 

Then I have a group called "groups-a" which adds **edit** permission to "piece-a" and "groups-b" which adds **edit** permission to "piece-b". 

If I add user "A" to "groups-a" then he can still see the menu item in the adminBar for "piece-b" and this is because:

* When the admin bar [filters the items](https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-admin-bar/index.js#L94)

* The [code in](https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-permissions/lib/api.js#L199) ```apostrophe-permissions/libs/api.js``` makes a check for either **edit** or **edit-[verb]** 

* And as it just [so happens in](https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-login/index.js#L115) ```apostrophe-login/index.js```,  *user._permissions.edit* is set to true regardless of the **verb**. 

As a result if you have any **"admin-"** permissions on a snippet, that means you automatically see the all menu items, regardless of whether you have **edit** permission or not.

**Comment by stuartromanek** [comment]
Hey @boutell this seems like a bug .. Can you give us an update on this? Estimate the complexity or give @fotisp a path to a PR?

**Comment by boutell** [comment]
There should be a flag at least to defeat this, although to strip it out completely would be a bc break. Sorry for the delay.

**Comment by abea** [comment]
I ran a test and it looks like a user with one piece edit permission now only sees that one piece type in their admin bar. @fotisp please confirm with the latest version if you're able. Sorry again for the delay on this one.
