### ISSUE TITLE
Tab in array editor needs active state

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe#893]

**Comment by austinstarin** [comment]
`data.active` is `undefined`

https://github.com/punkave/apostrophe/blob/master/lib/modules/apostrophe-schemas/views/arrayItems.html#L3

**Comment by abea** [comment]
It's not clear what this is referring to. Austin, if you recall, was this under particular circumstances? Generally the active state is working. @stuartromanek Any knowledge of this?

Closing until we have replaceable details.
