### ISSUE TITLE
Apos widget UI breaks with long widget label

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe#924]
![apos-ui](https://user-images.githubusercontent.com/4621109/27697610-c91f2ce2-5cc2-11e7-8a25-416d419931a6.png)

**Comment by stuartromanek** [comment]
I don't think it's the label length, it must be your container, right?

![image](https://user-images.githubusercontent.com/1889830/30964566-e0ccbca2-a41f-11e7-9390-95f7b0a0b6c8.png)
