### ISSUE TITLE
Permissions error created by storeCss call (LESS call) from apostrophe-assets gives inability to format rich text input within a modal

### ISSUE THREAD

**Issue by plane007** [apostrophecms/apostrophe#930]
The console reports:
 LESS undefined error : EACCES: permission denied, open '/var/www/vhosts/mapworldlive.com/dev.mapworldlive.com/blog1/public/modules/apostrophe-areas/js/vendor/ckeditor/skins/apostrophe/editor.css'
12|blog    |   LESS File : undefined undefined:undefined

Adding to a clean copy of the Boilerplate app, I added the example of creating People to the main menu up to the point where it says "Customizing the model layer". On actually running "Manage People", the Biography area is a rich text area. However, this error is generated when that field takes focus:

The weird thing is that I changed the file permissions for editor.css and editor.map from rw-r--r-- to rwxr-x-r-x, with no effect. The file permissions on the other files in that directory were rwxr-xr-x from install.

[permserr.txt](https://github.com/punkave/apostrophe/files/1127146/permserr.txt)

**Comment by boutell** [comment]
This is a difficult one to debug at a distance. If you can create a test project that reproduces the problem, though, I'll gladly take a look.

**Comment by plane007** [comment]
I have carefully created a test project here: http://mapworldlive.com:4000 using code as described by the tutorial to create People records.  I have added one person using admin: admin pwd: anchr0r12

You will see that the Person record contains 2 Biography instances (odd), but there is no formatting links seen or made available for use, although they seem to be present in the DOM.

If you want source, I can attach a zip file. Would you want the node_modules directory?

**Comment by plane007** [comment]
Sorry, browser was playing up when it closed.

**Comment by boutell** [comment]
Does this issue still relate to the original concern about a permissions error?

**Comment by plane007** [comment]
I mentioned above that the Person record contains Biography instances (odd), but there is no formatting links seen or made available for use, although they seem to be present in the DOM. It seems that this is true for pieces widgets where the user is supposed to be able to enter Rich Text, but not formatting is available.

**Comment by boutell** [comment]
Closed as we have no way of reproducing it locally.
