### ISSUE TITLE
Server code does not validate against required fields

### ISSUE THREAD

**Issue by bobclewell** [apostrophecms/apostrophe#937]
Currently when a field is identified in the schema as "required" it is only checked on the client-side of the application. This means that it is possible to add a required field to a document with a value as null if this client-side code is not run. We need to check on the server if a field's required boolean is set to true before it is saved to the database.

Keep in mind that on the client showFields will make sure that all required fields are shown on a form. Confirm that this still applies with this update.

**Comment by boutell** [comment]
the issue with showFields is that it changes the rules for what is really
"required" on the browser side and we must ensure that does not change when
we add server side enforcement.
