### ISSUE TITLE
Create a proper Time picker UI

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe#959]

**Comment by boutell** [comment]
Are there time pickers you like?

I've seen not-terrible time pickers based on an assumption like 15 minute increments. Without that kind of assumption, which we might not be able to safely make, they tend to just be annoying... IMHO... what we have now is a very, very tolerant treatment of what the user types in.

**Comment by stuartromanek** [comment]
A quick look around doesn't point to anything obvious .. will throw it out to the team

**Comment by boutell** [comment]
I did some research on this... seven years, ago, wow:

https://punkave.basecamphq.com/projects/3018369-apostrophe-product/posts/33174158/comments

A lot of which is still apropos I think, although there may be solutions out there that clear some of the bars I identified then.
