### ISSUE TITLE
Inserting nested areas or widgets in Mongo

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe#974]
When inserting nested areas or widgets in Mongo it would be nice to get errors or some sort of feedback if missing properties or nesting is incorrect.

**Comment by boutell** [comment]
Just in case it's unclear later, this is about programmatically inserting areas. Some kind of optional linting would be cool to have, or a method that helps you build an area correctly and supports nesting well through some kind of simplified jsonic syntax.
